### PR TITLE
Closes #3097: Show notification for fatal crashes on Android Q+.

### LINKED ISSUE #3097: Crash reporter triggers Android Q warning about background activity starts
When GeckoView or Fennec crashes on Android Q, a toast notification appears warning of a background activity start. To avoid the warning and ensure the crash reporter runs to completion, the crash reporter should use a foreground service instead of an Activity.

https://developer.android.com/preview/privacy/background-activity-starts

This bug was originally reported by @kbrosnan in Bugzilla for Fennec's crash reporter:
https://bugzilla.mozilla.org/show_bug.cgi?id=1550291

### PR DESCRIPTION
**Pull request by pocmo**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

File: components/lib/crash/src/test/java/mozilla/components/lib/crash/notification/CrashNotificationTest.kt [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+        assertFalse(CrashNotification.shouldShowNotificationInsteadOfPrompt(exceptionCrash, sdkLevel = 25))
+        assertFalse(CrashNotification.shouldShowNotificationInsteadOfPrompt(exceptionCrash, sdkLevel = 26))
+        assertFalse(CrashNotification.shouldShowNotificationInsteadOfPrompt(exceptionCrash, sdkLevel = 27))
+        assertFalse(CrashNotification.shouldShowNotificationInsteadOfPrompt(exceptionCrash, sdkLevel = 28))
+        assertTrue(CrashNotification.shouldShowNotificationInsteadOfPrompt(exceptionCrash, sdkLevel = 29))
+    }
+
+    @Test
+    fun `Showing notification`() {
+        val notificationManager = ApplicationProvider
```
Comment (dector) [inline components/lib/crash/src/test/java/mozilla/components/lib/crash/notification/CrashNotificationTest.kt]: nit: `testContext`? :sweat_smile:

File: components/lib/crash/src/test/java/mozilla/components/lib/crash/notification/CrashNotificationTest.kt [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+    @Test
+    fun shouldShowNotificationInsteadOfPrompt() {
+        val nonFatalNativeCrash = Crash.NativeCodeCrash(
+            minidumpPath = "",
+            minidumpSuccess = true,
+            extrasPath = "",
+            isFatal = false
+        )
+
+        assertFalse(CrashNotification.shouldShowNotificationInsteadOfPrompt(nonFatalNativeCrash, sdkLevel = 21))
```
Comment (dector) [inline components/lib/crash/src/test/java/mozilla/components/lib/crash/notification/CrashNotificationTest.kt]: nit: What do you think about generalizing this assertion (with using failing message)? Something like:

```kotlin
verifyNotificationInsteadOfPrompt(
    crash = crash,
	shouldPreferIf = { sdkVersion -> sdkVersion >= 29 }
)

fun verifyNotificationInsteadOfPrompt(...) {
    for (sdkVersion in minSdk..targetSdk) {
	    val expected = shouldPreferIf(sdkVersion)
	    val actual = shouldShowNotificationInsteadOfPrompt(nonFatalNativeCrash, sdkLevel = sdkVersion)
		assertEquals("Verifying for SDK: $sdkVersion", expected, actual)
	}
}
```

This way has it's own downsides but it would be nice to test full range of app enabled sdk versions.

File: components/lib/crash/src/test/java/mozilla/components/lib/crash/notification/CrashNotificationTest.kt (hunk 1 above)
Comment (pocmo) [reply components/lib/crash/src/test/java/mozilla/components/lib/crash/notification/CrashNotificationTest.kt]: Ah, yes :D

File: components/lib/crash/src/test/java/mozilla/components/lib/crash/notification/CrashNotificationTest.kt (hunk 2 above)
Comment (pocmo) [reply components/lib/crash/src/test/java/mozilla/components/lib/crash/notification/CrashNotificationTest.kt]: I think some repetition is okay in tests. I don't want to end up in a situation where my test code contains complex logic so that it requires tests itself :)
