### PR TITLE
Closes #4172: MediaService: Always, always, ALWAYS call startForeground()

### LINKED ISSUE #4172: MediaService: Did not call startForeground().
Fenix: https://github.com/mozilla-mobile/fenix/issues/4853

```
RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{df2820b u0 org.mozilla.fenix/mozilla.components.feature.media.service.MediaService}
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1872)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7050)
    at java.lang.reflect.Method.invoke(Method.java)
...
(2 additional frame(s) were not displayed)

Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{df2820b u0 org.mozilla.fenix/mozilla.components.feature.media.service.MediaService}
```

### PR DESCRIPTION
**Pull request by pocmo**
---

On top of #4169 (ignore first commit).

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaService.kt [hunk 1]
```diff
@@ -93,14 +95,22 @@ internal class MediaService : Service() {
 
         val notification = notification.create(state, mediaSession)
 
-        if (state is MediaState.Playing) {
-            startForeground(notificationId, notification)
-        } else {
+        // Android wants us to always, always, ALWAYS call startForeground() if
```
Comment (Amejia481) [inline components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaService.kt]: Do not forget **Always!!!!** XD

**Comment by Amejia481** [comment]
I rebased as this branch had a commit already merged on https://github.com/mozilla-mobile/android-components/pull/4169

bors r+

**Comment by pocmo** [comment]
Thank you for rebasing and landing this :)
