### PR TITLE
For #12804 - Catch the exception when querying activities

### LINKED ISSUE #12804: [Bug] TransactionTooLargeException from "Open links in apps"
Issue seen on Fenix - https://github.com/mozilla-mobile/fenix/issues/27042
Seems like [queryIntentActivities from AppLinksUseCases](https://github.com/mozilla-mobile/android-components/blob/6431cfeee9987337ff9d9260f5a7ac6188bf6160/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt#L58) can throw this error.
Could not reproduce locally, the issue depends on the specific configuration of app and other installed apps on the device - with the functionality querying which of the currently installed apps have declared components with intent filters for the current url.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21614)

### PR DESCRIPTION
**Pull request by Mugurell**
Speculative fix. A simple try-catch over an error that we cannot do anything else about.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: Could not test / reproduce locally.
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### GitHub Automation
Fixes #12804

### CODE REVIEW

File: components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt [hunk 1]
```diff
@@ -51,11 +51,19 @@ class AppLinksUseCases(
...
+        "TooGenericExceptionCaught",
+    )
     @VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
     internal fun findActivities(intent: Intent): List<ResolveInfo> {
-        return context.packageManager
-            .queryIntentActivities(intent, PackageManager.GET_RESOLVED_FILTER)
+        return try {
+            context.packageManager
+                .queryIntentActivities(intent, PackageManager.GET_RESOLVED_FILTER)
+        } catch (e: RuntimeException) {
```
Comment (rocketsroger) [inline components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt:63]: Should we just catch `ActivityNotFoundException` here?

Comment (rocketsroger) [inline components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt:63]: I'm not sure about this.  The [documentation](https://developer.android.com/reference/android/content/pm/PackageManager#queryIntentActivities(android.content.Intent,%20android.content.pm.PackageManager.ResolveInfoFlags)) doesn't show that it can throw an error.  Do we have any crash reporting that tells us what error it could be throwing?

Comment (rocketsroger) [reply components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt:63]: I see the original issue.  Maybe we just catch the `TransactionTooLargeException` exception?

Comment (Mugurell) [reply components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt:63]: Based on the report from https://github.com/mozilla-mobile/fenix/issues/27042 it seems to me like there is a `RuntimeException` wrapping the `TransactionTooLargeException`?

**Review by csadilek — APPROVED** [review]
