### PR TITLE
Close #12538: Crash notification will always trigger the crash prompt dialog

### LINKED ISSUE #12538: Crash notification will always trigger the crash prompt dialog
Currently, when user taps on report in a crash notification, we report the crash right away.  But if the user taps on the notification, then we show the crash reporting prompt.  Update the report button so it also shows the crash reporting prompt.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21097)

### PR DESCRIPTION
**Pull request by rocketsroger**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### GitHub Automation
Fixes #12538

### CODE REVIEW

**Comment by rocketsroger** [comment]
Waiting for the 104 release branch cut before landing.

File: components/lib/crash/src/main/java/mozilla/components/lib/crash/handler/CrashHandlerService.kt [hunk 1]
```diff
@@ -49,10 +49,7 @@ class CrashHandlerService : Service() {
             val channel = CrashNotification.ensureChannelExists(this)
             val notification = NotificationCompat.Builder(this, channel)
                 .setContentTitle(
-                    getString(
-                        R.string.mozac_lib_crash_dialog_title,
-                        crashReporter.promptConfiguration.appName
-                    )
+                    getString(R.string.mozac_lib_gathering_crash_data_in_progress)
```
Comment (sarah541) [inline components/lib/crash/src/main/java/mozilla/components/lib/crash/handler/CrashHandlerService.kt:52]: For context, what was the intent behind changing the title?

Comment (rocketsroger) [reply components/lib/crash/src/main/java/mozilla/components/lib/crash/handler/CrashHandlerService.kt:52]: The original string was confusing users thinking that we were sending the crash report automatically.  This is not the case, we were just collecting the crash information to store locally for user to look at in "about:crashes" and in case we failed to send it with crash reporter.

**Review by csadilek — APPROVED** [review]
Thanks for talking through yesterday and making the changes we discussed! 

👍 

Let's land on Monday :)

**Comment by rocketsroger** [comment]
> Thanks for talking through yesterday and making the changes we discussed!
> 
> 👍
> 
> Let's land on Monday :)

Agreed.  I'll land this on Monday.
