### PR TITLE
Closes #7181 - Do not crash on nonimplemented select login prompt

### LINKED ISSUE #7181: [Bug] Fenix crashes when tapping on the email/password fields from zoom the webpage
## Steps to reproduce
1. Launch Fenix.
2. Access the zoom webpage.
3. tap on the hamburger menu and tap on sign in or tap on the host.
4. Tap on the email/password fields.
### Expected behavior
Nothing happens and the email/password can be added in order to log in.
### Actual behavior
Fenix crashes when tapping on the email/password fields from zoom webpage
### Device information

* Android device: **Google Pixel 4 XL (10).**
* Fenix version: **Nightly 5/29.**
<details>
<summary>Logcat</summary>

```Kotlin
--------- beginning of crash
2020-05-29 13:16:21.521 27754-27754/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.nightly, PID: 27754
    java.lang.IllegalStateException: origin must not be null
        at androidx.transition.CanvasUtils.checkExpressionValueIsNotNull(CanvasUtils.java:1)
        at mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegate.toLogin(GeckoPromptDelegate.kt:3)
        at mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegate.access$toLogin(GeckoPromptDelegate.kt:1)
        at -$$LambdaGroup$ks$hn0Qifo2sAuTkYiPOrS3tHhq-z4.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:21)
        at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:4)
        at mozilla.components.concept.engine.EngineSession.notifyObservers(Unknown Source:4)
        at mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegate.onLoginSelect(GeckoPromptDelegate.kt:4)
        at org.mozilla.geckoview.GeckoSession.handlePromptEvent(GeckoSession.java:14)
        at org.mozilla.geckoview.GeckoSession$Listener.handleMessage(GeckoSession.java:4)
        at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:1)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2020-05-29 13:16:21.521 27754-27754/? I/mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=java.lang.IllegalStateException: origin must not be null, breadcrumbs=[Breadcrumb(message=Changing to fragment homeFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Fri May 29 12:54:40 GMT+03:00 2020), Breadcrumb(message=Changing to fragment browserFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Fri May 29 12:54:41 GMT+03:00 2020), Breadcrumb(message=Changing to fragment trackingProtectionPanelDialogFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Fri May 29 12:54:45 GMT+03:00 2020), Breadcrumb(message=Changing to fragment trackingProtectionFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Fri May 29 12:54:46 GMT+03:00 2020), Breadcrumb(message=Changing to fragment browserFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Fri May 29 12:55:02 GMT+03:00 2020), Breadcrumb(message=Changing to fragment webExtensionActionPopupFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Fri May 29 12:55:08 GMT+03:00 2020), Breadcrumb(message=Changing to fragment browserFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Fri May 29 12:55:10 GMT+03:00 2020), Breadcrumb(message=Changing to fragment addonsManagementFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Fri May 29 13:05:15 GMT+03:00 2020), Breadcrumb(message=Changing to fragment installedAddonDetailsFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Fri May 29 13:05:17 GMT+03:00 2020), Breadcrumb(message=Changing to fragment addonsManagementFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Fri May 29 13:05:17 GMT+03:00 2020), Breadcrumb(message=Changing to fragment installedAddonDetailsFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Fri May 29 13:05:18 GMT+03:00 2020), Breadcrumb(message=Changing to fragment addonsManagementFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Fri May 29 13:05:19 GMT+03:00 2020), Breadcrumb(message=Changing to fragment installedAddonDetailsFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Fri May 29 13:05:19 GMT+03:00 2020), Breadcrumb(message=Changing to fragment addonsManagementFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Fri May 29 13:05:20 GMT+03:00 2020), Breadcrumb(message=Changing to fragment installedAddonDetailsFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Fri May 29 13:05:21 GMT+03:00 2020), Breadcrumb(message=Changing to fragment addonsManagementFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Fri May 29 13:05:21 GMT+03:00 2020), Breadcrumb(message=Changing to fragment browserFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Fri May 29 13:05:22 GMT+03:00 2020), Breadcrumb(message=Changing to fragment homeFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Fri May 29 13:05:41 GMT+03:00 2020), Breadcrumb(message=Changing to fragment browserFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Fri May 29 13:16:16 GMT+03:00 2020)], uuid=5e4af669-1153-491a-931d-cc7eb5b6a8c1)
2020-05-29 13:16:21.527 27754-27754/? I/mozac/CrashReporter: Showing notification
2020-05-29 13:16:21.533 1337-30168/? I/DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
2020-05-29 13:16:21.533 1337-3050/? W/ActivityTaskManager:   Force finishing activity org.mozilla.fenix.nightly/.App
2020-05-29 13:16:21.554 1337-1372/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
2020-05-29 13:16:21.554 1337-1372/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
2020-05-29 13:16:21.572 27754-27754/? I/Process: Sending signal. PID: 27754 SIG: 9
2020-05-29 13:16:21.592 2084-2098/? W/s.nexuslaunche: Reducing the number of considered missed Gc histogram windows from 146 to 100
2020-05-29 13:16:21.594 2084-2100/? W/System: A resource failed to call release. 
2020-05-29 13:16:21.594 1811-1823/? W/ndroid.systemu: Reducing the number of considered missed Gc histogram windows from 145 to 100
2020-05-29 13:16:21.594 2084-2100/? W/System: A resource failed to call release. 
2020-05-29 13:16:21.621 27835-28274/? I/Gecko: Exiting due to channel error.
2020-05-29 13:16:21.621 1337-1581/? W/InputDispatcher: channel '796f209 org.mozilla.fenix.nightly/org.mozilla.fenix.nightly.App (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
2020-05-29 13:16:21.622 1337-1581/? E/InputDispatcher: channel '796f209 org.mozilla.fenix.nightly/org.mozilla.fenix.nightly.App (server)' ~ Channel is unrecoverably broken and will be disposed!
2020-05-29 13:16:21.641 1811-1811/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|org.mozilla.fenix.nightly|1|mozac.lib.crash.notification|10329
2020-05-29 13:16:21.670 1337-2939/? I/ActivityManager: Process org.mozilla.fenix.nightly:tab0 (pid 27835) has died: fore BTOP
2020-05-29 13:16:21.671 1337-2939/? W/ActivityManager: Scheduling restart of crashed service org.mozilla.fenix.nightly/org.mozilla.gecko.process.GeckoChildProcessServices$tab0 in 1000ms
2020-05-29 13:16:21.672 809-809/? I/Zygote: Process 27835 exited cleanly (0)
2020-05-29 13:16:21.717 1337-1374/? I/libprocessgroup: Successfully killed process cgroup uid 10329 pid 27835 in 46ms
2020-05-29 13:16:21.744 1337-8960/? D/ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=2531, [ Transports: WIFI Capabilities: NOT_RESTRICTED&TRUSTED&NOT_VPN&FOREGROUND Uid: 10329] ], android.os.BinderProxy@6b22167)
2020-05-29 13:16:21.744 1337-8960/? D/AutofillSession: handling death of Token{bb7e7ba ActivityRecord{f27d0e5 u0 org.mozilla.fenix.nightly/.App t889 f}} when saving=false
2020-05-29 13:16:21.744 1337-2939/? I/ActivityManager: Process org.mozilla.fenix.nightly (pid 27754) has died: fore TOP 
2020-05-29 13:16:21.744 1337-3052/? I/WindowManager: WIN DEATH: Window{796f209 u0 org.mozilla.fenix.nightly/org.mozilla.fenix.nightly.App}
2020-05-29 13:16:21.744 1337-3052/? W/InputDispatcher: Attempted to unregister already unregistered input channel '796f209 org.mozilla.fenix.nightly/org.mozilla.fenix.nightly.App (server)'
2020-05-29 13:16:21.746 809-809/? I/Zygote: Process 27754 exited due to signal 9 (Killed)
2020-05-29 13:16:21.748 1337-2939/? W/ActivityManager: Scheduling restart of crashed service org.mozilla.fenix.nightly/mozilla.components.lib.crash.service.SendCrashTelemetryService in 1000ms
2020-05-29 13:16:21.752 1337-1374/? I/libprocessgroup: Successfully killed process cgroup uid 10329 pid 27754 in 7ms
2020-05-29 13:16:21.779 808-808/? I/netd: firewallSetUidRule(2, 10202, 2) <0.04ms>
2020-05-29 13:16:21.779 2210-2210/? I/AndroidIME: AbstractIme.onDeactivate():145 PasswordIme.onDeactivate()
2020-05-29 13:16:21.830 28960-28960/? W/ThreadPoolDumper: Queue length for executor EventBus is now 11. Perhaps some tasks are too long, or the pool is too small.
2020-05-29 13:16:21.859 28960-29068/? W/LocationOracle: No location history returned by ContextManager
2020-05-29 13:16:21.917 28960-28960/? I/StreamRenderer: cleanUpRendererScope(nowcards-15-52adb21e-9c78)
2020-05-29 13:16:21.935 28960-29030/? I/MicroDetectionState: Should stop hotword detection immediately - false
2020-05-29 13:16:21.936 28960-28960/? I/BgTaskExecutorImpl: Starting EXCLUSIVE background task TNG_MINUS_ONE_SYNC.
2020-05-29 13:16:21.939 2394-2394/? I/GsaVoiceInteractionSrv: Handling ACTION_START_DSP_HOTWORD
2020-05-29 13:16:21.941 28960-28960/? I/StreamRenderer: maybeRegisterNowCardsScope(nowcards-15-52d3bfa9-5ce9, com.google.android.sidekick.shared.remoteapi.CardRenderingContext@8b4bf3e)
2020-05-29 13:16:21.951 824-824/? D/SoundTriggerHAL: stdev_start_recognition stdev 0xe9c32000, sound model 0
2020-05-29 13:16:21.951 824-824/? D/SoundTriggerHAL: reg_hal_event_session: ST_EVENT_SESSION_REGISTER capture_handle 110 model 0xe9c3205c
2020-05-29 13:16:21.951 824-824/? D/SoundTriggerHAL: stdev_start_recognition: Is capture requested 1
2020-05-29 13:16:21.951 824-824/? D/SoundTriggerHALUtil: +setup_buffer_package+
2020-05-29 13:16:21.969 28960-29030/? I/TngMinusOneSync: Syncing TNG:-1
2020-05-29 13:16:21.976 1337-3052/? I/ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.google.android.music/com.android.music.activitymanagement.TopLevelActivity bnds=[48,546][317,966]} from uid 10156
2020-05-29 13:16:21.988 844-844/? D/android.hardware.power@1.3-service.pixel-libperfmgr: LAUNCH: 1
2020-05-29 13:16:22.012 1337-1361/? E/system_server: Invalid ID 0x00000000.
2020-05-29 13:16:22.016 1337-1360/? W/ActivityManager: setHasOverlayUi called on unknown pid: 27754
2020-05-29 13:16:22.018 809-809/? D/Zygote: Forked child process 30186
2020-05-29 13:16:22.020 1337-1373/? I/ActivityManager: Start proc 30186:com.google.android.music:ui/u0a304 for activity {com.google.android.music/com.android.music.activitymanagement.TopLevelActivity}
2020-05-29 13:16:22.032 30186-30186/? E/ndroid.music:u: Not starting debugger since process cannot load the jdwp agent.
2020-05-29 13:16:22.033 1337-1360/? W/ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{f27d0e5 u0 org.mozilla.fenix.nightly/.App t-1 f}
2020-05-29 13:16:22.057 28960-29030/? W/CollectionEntryAdapter: Server did not send DisplayProperties
2020-05-29 13:16:22.059 808-808/? I/netd: firewallSetUidRule(2, 10304, 1) <0.03ms>
2020-05-29 13:16:22.059 28960-29030/? W/ErrorReporter: reportError [type: 29, code: 917507, bug: 78227467]: null
2020-05-29 13:16:22.064 30186-30186/? I/ndroid.music:u: The ClassLoaderContext is a special shared library.
2020-05-29 13:16:22.101 28960-29030/? I/MicroDetectionState: Should stop hotword detection immediately - false
2020-05-29 13:16:22.107 30186-30186/? I/MultiDex: VM with version 2.1.0 has multidex support
2020-05-29 13:16:22.107 30186-30186/? I/MultiDex: install
2020-05-29 13:16:22.107 30186-30186/? I/MultiDex: VM has multidex support, MultiDex support library is disabled.
2020-05-29 13:16:22.115 30186-30186/? D/ProcessNameProvider: Content provider UiProcessTypeInitializerContentProvider created for process UI
2020-05-29 13:16:22.123 30186-30186/? D/MusicLifecycle: com.google.android.music.ui.PhoneMusicApplication generated event: Application created
2020-05-29 13:16:22.123 30186-30186/? I/AndroidMusic: Application start. Process=UI
2020-05-29 13:16:22.127 605-605/? E/RenderEngine: GL error 0x0501
2020-05-29 13:16:22.145 809-809/? D/Zygote: Forked child process 30215
2020-05-29 13:16:22.151 1337-1373/? I/ActivityManager: Start proc 30215:com.google.android.music:main/u0a304 for content provider {com.google.android.music/com.google.android.music.store.ConfigContentProvider}
2020-05-29 13:16:22.154 30215-30215/? E/roid.music:mai: Not starting debugger since process cannot load the jdwp agent.```
</details>

### PR DESCRIPTION
**Pull request by ekager**
---

Once I actually implement the select login prompt in #7134 (probably next week) I'll make sure this STR doesn't crash then, but for now, let's make sure we aren't crashing on this nonimplemented feature 

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt [hunk 1]
```diff
@@ -115,7 +115,7 @@ internal class GeckoPromptDelegate(private val geckoEngineSession: GeckoEngineSe
         geckoEngineSession.notifyObservers {
             onPromptRequest(
                 PromptRequest.SelectLoginPrompt(
-                    logins = prompt.options.map { it.value.toLogin() },
```
Comment (Amejia481) [inline components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt:118]: Can we link the issues for the working in progress ? :)
