### PR TITLE
Closes #5215: Send crash report on IO Thread with SendCrashReportService

### LINKED ISSUE #5215: NetworkOnMainThread when reporting crash from notification (RB)
In Reference Browser whenever I click the "report" button in the crash notification then it immediately crashes again. I think I saw NetworkOnMainThread in the logs, but I couldn't really read them on my phone.

### PR DESCRIPTION
**Pull request by rocketsroger**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by rocketsroger** [comment]
bors r=Amejia481

**Comment by rocketsroger** [comment]
bors retry

**Comment by rocketsroger** [comment]
bors retry

File: components/lib/crash/src/test/java/mozilla/components/lib/crash/CrashReporterTest.kt [hunk 1]
```diff
@@ -198,7 +199,7 @@ class CrashReporterTest {
         reporter.onCrash(
             mock(),
             Crash.UncaughtExceptionCrash(RuntimeException(), arrayListOf()))
-
+        sleep(100)
```
Comment (Amejia481) [inline components/lib/crash/src/test/java/mozilla/components/lib/crash/CrashReporterTest.kt]: Could we use `runBlocking` as `sleep(N) `could make the test unreliable?

File: components/lib/crash/src/test/java/mozilla/components/lib/crash/CrashReporterTest.kt [hunk 2]
```diff
@@ -208,12 +209,14 @@ class CrashReporterTest {
             Crash.NativeCodeCrash("", true, "", false, arrayListOf())
         )
 
+        sleep(100)
```
Comment (Amejia481) [inline components/lib/crash/src/test/java/mozilla/components/lib/crash/CrashReporterTest.kt]: The same as above ^

File: components/lib/crash/src/test/java/mozilla/components/lib/crash/CrashReporterTest.kt [hunk 3]
```diff
@@ -208,12 +209,14 @@ class CrashReporterTest {
...
         assertFalse(exceptionCrash)
         assertTrue(nativeCrash)
         assertFalse(caughtException)
 
         reporter.submitCaughtException(RuntimeException()).joinBlocking()
 
+        sleep(100)
```
Comment (Amejia481) [inline components/lib/crash/src/test/java/mozilla/components/lib/crash/CrashReporterTest.kt]: The same as above ^

File: components/lib/crash/src/test/java/mozilla/components/lib/crash/CrashReporterTest.kt (hunk 1 above)
Comment (rocketsroger) [reply components/lib/crash/src/test/java/mozilla/components/lib/crash/CrashReporterTest.kt]: Agreed. I'll look into another way to do this better.  Thanks,

File: components/lib/crash/src/test/java/mozilla/components/lib/crash/CrashReporterTest.kt (hunk 2 above)
Comment (rocketsroger) [reply components/lib/crash/src/test/java/mozilla/components/lib/crash/CrashReporterTest.kt]: Agreed.

File: components/lib/crash/src/test/java/mozilla/components/lib/crash/CrashReporterTest.kt (hunk 3 above)
Comment (rocketsroger) [reply components/lib/crash/src/test/java/mozilla/components/lib/crash/CrashReporterTest.kt]: Agreed.

File: components/lib/crash/src/test/java/mozilla/components/lib/crash/handler/CrashHandlerServiceTest.kt [hunk 4]
```diff
@@ -69,6 +70,7 @@ class CrashHandlerServiceTest {
         doNothing().`when`(service).kill()
         service.onHandleIntent(intent)
 
+        sleep(100)
```
Comment (Amejia481) [inline components/lib/crash/src/test/java/mozilla/components/lib/crash/handler/CrashHandlerServiceTest.kt]: Do we still need this one?

Comment (rocketsroger) [reply components/lib/crash/src/test/java/mozilla/components/lib/crash/handler/CrashHandlerServiceTest.kt]: Yes, I don't think I can avoid this one.

Comment (Amejia481) [reply components/lib/crash/src/test/java/mozilla/components/lib/crash/handler/CrashHandlerServiceTest.kt]: Let's try to find an alternative, as this could cause a lot of flakiness in the tests. Later in the day I will take a closer look

Comment (Amejia481) [reply components/lib/crash/src/test/java/mozilla/components/lib/crash/handler/CrashHandlerServiceTest.kt]: Sorry, I don't want to be picky, I just want to find a better alternative :)

Comment (rocketsroger) [reply components/lib/crash/src/test/java/mozilla/components/lib/crash/handler/CrashHandlerServiceTest.kt]: I understand.  I don't like it as well.  The test might have to be changed to not use the sleep.  The `onHandleIntent` API can't be modified to return the job.

Comment (rocketsroger) [reply components/lib/crash/src/test/java/mozilla/components/lib/crash/handler/CrashHandlerServiceTest.kt]: Created issue to track this https://github.com/mozilla-mobile/android-components/issues/5480

Comment (csadilek) [reply components/lib/crash/src/test/java/mozilla/components/lib/crash/handler/CrashHandlerServiceTest.kt]: @rocketsroger @Amejia481 let's not land the test with the `sleep`, please. :) Here's an alternative version of the test and change that should work reliably: https://github.com/csadilek/android-components/commit/fd57536ea59ab4250c8ea88e8618e798b159628a

Comment (Amejia481) [reply components/lib/crash/src/test/java/mozilla/components/lib/crash/handler/CrashHandlerServiceTest.kt]: Thanks!

Comment (rocketsroger) [reply components/lib/crash/src/test/java/mozilla/components/lib/crash/handler/CrashHandlerServiceTest.kt]: Thanks! I've applied your changes to this PR.  I'll close the created issue.

**Comment by rocketsroger** [comment]
bors r=Amejia481
