### PR TITLE
Issue #11844: Take the correct number of Provided top sites

### LINKED ISSUE #11844: [Bug]: Two Sponsored tiles are displayed even if there are already 7 pinned tiles available
### Prerequisites
- Have 7 pinned top sites.

### Steps to reproduce

1. Open the Nightly browser.
3. Tap the "Customize homepage.
4. Enable the "Sponsored shortcuts" option.
5. Return to the homepage and observe the top sites section.

### Expected behaviour

- Only one Sponsored tile is displayed and the 7 pinned tiles are in view.

### Actual behaviour

- Two sponsored tiles are displayed and the last pinned tile is pushed to the second page.

### Device name

One Plus 8 Pro

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1

### Device logs

_No response_

### Additional information

- Based on the [Contile Mobile Technical Requirements](https://docs.google.com/document/d/1t3p4B_RD3I1b-GPWSU-ouWd_ukL1lYEnxv4yro46yrk/edit#) only one Sponsored tile should be displayed if there are already 7 pinned tiles.
- Also based on [FNXV2-18722](https://mozilla-hub.atlassian.net/browse/FNXV2-18722), it is mentioned that: "Sponsored topsites should not push out sites that users have explicitly added to their homepage".

https://user-images.githubusercontent.com/19226534/157474678-8ddcacf1-f0af-4bce-b4e1-f124f252a848.mp4

### PR DESCRIPTION
**Pull request by gabrielluong**
Fixes #11844
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/DefaultTopSitesStorage.kt [hunk 1]
```diff
@@ -102,7 +102,7 @@ class DefaultTopSitesStorage(
             try {
                 providerTopSites = topSitesProvider
                     .getTopSites(allowCache = true)
-                    .take(numSitesRequired)
+                    .take(providerConfig.maxThreshold - pinnedSites.size)
```
Comment (MozillaNoah) [inline components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/DefaultTopSitesStorage.kt:105]: just to make sure I'm on the same page, the math here is to ensure enough top sites are grabbed so long as there's room for them?

Comment (gabrielluong) [reply components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/DefaultTopSitesStorage.kt:105]: So, the maxThreshold is 8 (meaning we don't want to take any provided top sites if there are more than 8 pinned sites). The prior if statements guarantee that we have less pinned sites than the maxThreshold. On Fenix, we want to ensure provided top sites are only shown in the first page (within the first 8 top sites). So, if there are 8 pinned sites, we show no provided top sites. If it's 7 pinned sites, we only show 1 provided top sites. So, the math ends up being maxThreshold - pinnedSites.size

Comment (gabrielluong) [reply components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/DefaultTopSitesStorage.kt:105]: `take(n)` with a negative number would error, but it's not possible because of the check in the if statement to ensure pinnedSites.size is less than the maxThreshold

**Review by MozillaNoah — APPROVED** [review]
