### PR TITLE
Closes #8619: Add maximum length for Socorro crash report stack trace

### LINKED ISSUE #8619: Add maximum length for Socorro crash report stack trace
In some cases stack trace to Socorro is too big to store in the database.  Add maximum length as a parameter so limit can be set to avoid exceptions.

### PR DESCRIPTION
**Pull request by rocketsroger**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/support/base/src/main/java/mozilla/components/support/base/ext/Throwable.kt [hunk 1]
```diff
@@ -8,14 +8,15 @@ import java.io.PrintWriter
 import java.io.StringWriter
 
 private const val STACK_TRACE_INITIAL_BUFFER_SIZE = 256
+private const val STACK_TRACE_MAX_LENGTH = 100000
```
Comment (rocketsroger) [inline components/support/base/src/main/java/mozilla/components/support/base/ext/Throwable.kt:11]: Is this a good default?

**Review by pocmo — COMMENTED** [review]
I thought this was primarily about our own local database:
https://github.com/mozilla-mobile/android-components/blob/master/components/lib/crash/src/main/java/mozilla/components/lib/crash/db/CrashEntity.kt#L27-L32

**Review by pocmo — APPROVED** [review]
