### PR TITLE
Close #6963: Sync account when SyncedTabsFeature is started

### LINKED ISSUE #6963: Use account sync to trigger a Sync Tabs refresh in feature start
Use `FxaAccountManager.syncNowAsync` to trigger a sync tabs refresh in the presenter instead of a direct sync tabs poll. Currently, we're using `controller.syncTabs()` which can fail for edge cases.

We should put this in the controller since we invoke this in the `onRefresh` call as well.

### PR DESCRIPTION
**Pull request by jonalmeida**
Instead of syncing tabs on start, we refresh the devices and sync the account. The allows our mechanism to sync tabs once that is complete to be triggered where we know we're in the most current state we can be in.

---

Closes #6963 

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by jonalmeida** [comment]
> Merging [#7114](https://codecov.io/gh/mozilla-mobile/android-components/pull/7114?src=pr&el=desc) into [master](https://codecov.io/gh/mozilla-mobile/android-components/commit/0f6e197c573757d904597960ffe248758862b9dd&el=desc) will **increase** coverage by `0.35%`.
> The diff coverage is `90.00%`.

This is some quality feel-good content, right here.

**Comment by grigoryk** [comment]
It may be worth expanding the `syncNow` API to allow specifying not just a reason, but which engine you want to be synced. `appservices.SyncManager` can be configured to request syncing specific engines via `SyncParams`, currently we just tell it to always sync everything.

I'm assuming that the synced tabs feature will be started when you open up some synced-tabs UI? Depending on what else is happening w/ sync on other clients, you could greatly speed-up how quickly tabs are actually synced when you ask for a sync. E.g. if there's lots of changes to history/bookmarks, or just a bad connection, a full sync could take a while.

This is what Fennec did when you'd pull-to-refresh the synced tabs UI - it'll just sync the tabs collection.

**Comment by jonalmeida** [comment]
> I'm assuming that the synced tabs feature will be started when you open up some synced-tabs UI?

We actually have both. A user-initiated sync (in Fenix this is a pull-to-refresh) and the other is the `onStart` of the feature.

I've filed https://github.com/mozilla-mobile/android-components/issues/7119 for adding more `SyncReason`s.

**Comment by grigoryk** [comment]
> and the other is the onStart of the feature.

When does that happen in Fenix?

**Comment by jonalmeida** [comment]
> When does that happen in Fenix? We'll run a sync while first initializing account manager, which will be pretty closely after app startup.

We would start the feature (and therefore sync account) when the view is visible. In R-B, this is a separate UI view, which can happen before or long after an account sync happens. We can be a stale state if we don't sync. 

Being able to sync individual engines sounds like a neat idea! In the Sync Tabs case, would that solve the problem of new devices that are added/removed if we would sync the engine? I assume we would still need to refresh the device constellation first?

File: components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/controller/DefaultController.kt [hunk 1]
```diff
@@ -45,4 +49,16 @@ internal class DefaultController(
             }
         }
     }
+
+    /**
+     * See [SyncedTabsController.syncAccount]
+     */
+    override fun syncAccount() {
+        scope.launch {
+            accountManager.withConstellation {
```
Comment (grigoryk) [inline components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/controller/DefaultController.kt:58]: Not for this PR, but just thinking out-loud:

This makes me think if it's worth consolidating these two things, perhaps as a flag once can pass into `syncNowAsync`.

e.g. this will be a nice entry point:
`syncNowAsync(reason = SyncReason.User, engines = [Tabs], updateConstellation = true)`

Comment (grigoryk) [inline components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/controller/DefaultController.kt:58]: `accountManager.withConstellation` is potentially misleading. If account isn't logged-in, this is a no-op, but just glancing at this code doesn't make it obvious.

I much prefer the long-form `authenticatedAccount()?.deviceConstellation()?.refreshDevicesAsync()?.await()` for that reason, it makes things obvious at a glance even if it's a little clumsy; perhaps we can add `constellation(): DeviceConstellation?` to the account manager? Then this would become `accountManager.constellation()?.refreshDevicesAsync()?.await()`.

File: components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/interactor/DefaultInteractor.kt [hunk 2]
```diff
@@ -33,11 +27,6 @@ internal class DefaultInteractor(
     }
 
     override fun onRefresh() {
-        CoroutineScope(coroutineContext).launch {
-            accountManager.withConstellation {
-                refreshDevicesAsync()
-            }
-            accountManager.syncNowAsync(SyncReason.User, true)
-        }
+        controller.syncAccount()
```
Comment (grigoryk) [inline components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/interactor/DefaultInteractor.kt:30]: So if i'm reading this correctly, this is just a refactor? You were already requesting a syncNow before this PR.

File: components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/controller/DefaultController.kt [hunk 3]
```diff
@@ -45,4 +49,16 @@ internal class DefaultController(
...
+                refreshDevicesAsync().await()
+            }
+            accountManager.syncNowAsync(SyncReason.User)
```
Comment (grigoryk) [inline components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/controller/DefaultController.kt:61]: Before this used `debounce=true`, now it's `debounce=false`. Any reason for changing this?

Comment (jonalmeida) [reply components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/controller/DefaultController.kt:61]: Yes, it's due to this bug: https://github.com/mozilla-mobile/android-components/issues/6878

File: components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/interactor/DefaultInteractor.kt (hunk 2 above)
Comment (jonalmeida) [reply components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/interactor/DefaultInteractor.kt:30]: Before we were calling `syncTabs` which pulls the tabs from the last sync. Now, we're calling `syncAccount` which is what we were doing when a user activated sync from the UI. When the account syncs and the account manager is idle, we do the `syncTabs` call.

File: components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/controller/DefaultController.kt (hunk 1 above)
Comment (jonalmeida) [reply components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/controller/DefaultController.kt:58]: > I much prefer the long-form `authenticatedAccount()?.deviceConstellation()?.refreshDevicesAsync()?.await()` for that reason, it makes things obvious at a glance even if it's a little clumsy; perhaps we can add `constellation(): DeviceConstellation?` to the account manager? Then this would become `accountManager.constellation()?.refreshDevicesAsync()?.await()`.

I've found handling the device constellation a bit clumsy at times to get into the right state, I had filed https://github.com/mozilla-mobile/android-components/issues/6879 to address that.

> `accountManager.withConstellation` is potentially misleading. If account isn't logged-in, this is a no-op, but just glancing at this code doesn't make it obvious.

Would an intermediate fix be to change the naming of the extension function to suggest it's a "maybe" action.

`withConstellationIfExists` for example?

Comment (jonalmeida) [reply components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/controller/DefaultController.kt:58]: I filed https://github.com/mozilla-mobile/android-components/issues/7139 to address this in a follow-up.

**Comment by jonalmeida** [comment]
bors r=grigoryk

Since we have follow-ups issues already filed, I think we can merge this.
