### PR TITLE
Close #6953: Report native fatal crash to Sentry as level FATAL

### LINKED ISSUE #6953: Native fatal crashes should be reported to Sentry as level fatal
Currently we're reporting all native code crashes as level info to Sentry.  This is incorrect.  The level should be fatal when the crash is fatal, error when the crash is non fatal.

### PR DESCRIPTION
**Pull request by rocketsroger**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SentryService.kt [hunk 1]
```diff
@@ -90,13 +90,18 @@ class SentryService(
...
+            }
+
             crash.breadcrumbs.forEach {
                 client.context.recordBreadcrumb(it.toSentryBreadcrumb())
             }
 
             val eventBuilder = EventBuilder()
                 .withMessage(createMessage(crash))
-                .withLevel(Event.Level.INFO)
+                .withLevel(level)
```
Comment (pocmo) [inline components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SentryService.kt:104]: The initial idea here was that this is just a "log message" as opposed to an actual crash report that we can act on. But I guess we can also send it with "error" level if you think that is more helpful.

Comment (rocketsroger) [reply components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SentryService.kt:104]: I agree.  But there are some issues where other teams thought native crashes are not actual crashes.  Because caught exceptions are also sent as INFO.  This will make it easier to spot real crashes in Sentry. 👍

**Comment by rocketsroger** [comment]
bors r=pocmo
