### PR TITLE
Close #6903: Caught exception with no stack trace will be reported as UnexpectedlyMissingStacktrace

### LINKED ISSUE #6903: a-c files busted crash reports to crash-stats
While looking into [GeckoView Bug 1633786](https://bugzilla.mozilla.org/show_bug.cgi?id=1633786), I noticed the crashes have a "CrashType" set to "caught excepetion". This seems to be a string from the a-c crash reporter. It looks like a-c is sending either malformed or incomplete reports in some cases.

### PR DESCRIPTION
**Pull request by rocketsroger**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt [hunk 1]
```diff
@@ -139,11 +140,19 @@ class CrashReporter(
...
      */
     override fun submitCaughtException(throwable: Throwable): Job {
-        logger.info("Caught Exception report submitted to ${services.size} services")
+        /*
+         * if stacktrace is empty, replace throwable with invalid parameter exception so we can
+         * figure out which module is submitting caught exception reports without a stacktrace.
+         */
+        var reportThrowable = throwable
+        if (throwable.stackTrace.isEmpty()) {
+            reportThrowable = InvalidParameterException()
```
Comment (pocmo) [inline components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt:149]: * If this is for debugging purposes: Maybe create a custom exception for this case?
* Let's also add the original throwable as `cause` of the new exception, so that we get the original one too?

Comment (rocketsroger) [reply components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt:149]: Sure, I'll update.  Thanks,
