### PR TITLE
Closes #3567: BrowserStore/SessionManager: Make result of "nearby" tab selection match.

### LINKED ISSUE #3567: BrowserStore/SessionManager: Make result of "nearby" tab selection match
We use the same oscillating algorithm in both. However since `SessionManager` has custom tabs in the same list the result can vary.

The following unit test fails currently:

```kotlin
    @Test
    fun `Remove session will not select custom tab`() {
        val session1 = Session(id = "session1", initialUrl = "https://www.firefox.com").apply {
            customTabConfig = mock() }
        val session2 = Session(id = "session2", initialUrl = "https://developer.mozilla.org/en-US/")
        val session3 = Session(id = "session3", initialUrl = "https://www.mozilla.org/en-US/internet-health/").apply {
            customTabConfig = mock() }
        val session4 = Session(id = "session4", initialUrl = "https://www.mozilla.org/en-US/technology/")
        val session5 = Session(id = "session5", initialUrl = "https://example.org/555").apply {
            customTabConfig = mock() }
        val session6 = Session(id = "session6", initialUrl = "https://example.org/Hello").apply {
            customTabConfig = mock() }
        val session7 = Session(id = "session7", initialUrl = "https://example.org/World").apply {
            customTabConfig = mock() }
        val session8 = Session(id = "session8", initialUrl = "https://example.org/JustTestingThings").apply {
            customTabConfig = mock() }
        val session9 = Session(id = "session9", initialUrl = "https://example.org/NoCustomTab")

        val state = BrowserState()
        val store = BrowserStore(state)

        val manager = SessionManager(engine = mock(), store = store)
        manager.add(session1)
        manager.add(session2)
        manager.add(session3)
        manager.add(session4)
        manager.add(session5)
        manager.add(session6)
        manager.add(session7)
        manager.add(session8)
        manager.add(session9)

        manager.select(session4)
        assertEquals(session4, manager.selectedSession)
        assertEquals("session4", store.state.selectedTabId)

        //---------------------------------------------------------
        // The following assertion fails:
        // -> SessionManager selects tab 2
        // -> BrowserStore selects tab 9
        //---------------------------------------------------------
        manager.remove(session4)
        assertEquals(session2, manager.selectedSession)
        assertEquals("session2", store.state.selectedTabId)

        manager.remove(session2)
        assertEquals(session9, manager.selectedSession)
        assertEquals("session9", store.state.selectedTabId)

        manager.remove(session9)
        assertNull(manager.selectedSession)
        assertNull(store.state.selectedTabId)
    }
```

For `BrowserStore` tab 9 is a direct neighbor of the previous tab. For `SessionManager` it's far away since there are a bunch of custom tabs between them. A fix may be to oscillate in `SessionManager` without the custom tabs and then re-calculate the index for the full list.

### PR DESCRIPTION
**Pull request by pocmo**
This is a bit crazy. But `browser-session` is going away eventually....

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

File: components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerMigrationTest.kt [hunk 1]
```diff
@@ -339,4 +339,116 @@ class SessionManagerMigrationTest {
...
+     * - Selects a random tab
+     * - Randomly removes tabs
+     * - Verifies that the selected tabs in BrowserStore and SessionManager match
+     *
+     * The `println` statements have been commented out to not spam the CI log. However they are helpful in case someone
+     * needs to actually debug a problem here.
+     */
+    @Test
+    fun `Remove session from randomized set will keep store and manager in sync`() {
+        repeat(10000) {
```
Comment (jhugman) [inline components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerMigrationTest.kt]: 😻

File: components/browser/session/src/main/java/mozilla/components/browser/session/LegacySessionManager.kt [hunk 2]
```diff
@@ -398,20 +399,44 @@ class LegacySessionManager(
...
+    @Suppress("LongMethod") // Yes, this method is pretty long. I hope we can delete it soon.
     private fun findNearbySession(index: Int, predicate: (Session) -> Boolean): Int {
-        val maxSteps = max(values.lastIndex - index, index)
+        // Okay, this is a bit stupid and complex. This implementation intends to implement the same behavior we use in
+        // BrowserStore - which is operating on a list without custom tabs. Since LegacySessionManager uses a list with
+        // custom tabs mixed in, we need to shift the index around a bit.
+
+        // First we need to determine the number of custom tabs that are *before* the index we removed from. This is
+        // later needed to calculate the index we would have removed from in a list without custom tabs.
+        var numberOfCustomTabsBeforeRemovedIndex = 0
```
Comment (csadilek) [inline components/browser/session/src/main/java/mozilla/components/browser/session/LegacySessionManager.kt]: nit: could write as `sublist.filter.size` but not sure that's much easier to read.

File: components/browser/session/src/main/java/mozilla/components/browser/session/LegacySessionManager.kt [hunk 3]
```diff
@@ -398,20 +399,44 @@ class LegacySessionManager(
         return findNearbySession(index) { !it.isCustomTabSession() }
     }
 
+    @Suppress("LongMethod") // Yes, this method is pretty long. I hope we can delete it soon.
     private fun findNearbySession(index: Int, predicate: (Session) -> Boolean): Int {
```
Comment (jhugman) [inline components/browser/session/src/main/java/mozilla/components/browser/session/LegacySessionManager.kt]: This needs a doc comment.

File: components/browser/session/src/main/java/mozilla/components/browser/session/LegacySessionManager.kt [hunk 4]
```diff
@@ -398,20 +399,44 @@ class LegacySessionManager(
...
+            listOf(indexWithoutCustomTabs - steps, indexWithoutCustomTabs + steps).forEach { current ->
                 if (current >= 0 &&
-                    current <= values.lastIndex &&
-                    predicate(values[current])) {
-                    return current
+                    current <= sessionsWithoutCustomTabs.lastIndex &&
+                    predicate(sessionsWithoutCustomTabs[current])) {
+                    // Now that we have a match we need to re-calculate the index in the list that includes custom tabs.
+                    val session = sessionsWithoutCustomTabs[current]
+                    return values.indexOf(session)
```
Comment (jhugman) [inline components/browser/session/src/main/java/mozilla/components/browser/session/LegacySessionManager.kt]: I'm a bit confused how this re-write helps. Is `predicate` necessary?

This `predicate` is only specified twice: once where it's checking we're not in a custom tab, and the other to check that we're in `private` browsing or not.

Comment (jhugman) [reply components/browser/session/src/main/java/mozilla/components/browser/session/LegacySessionManager.kt]: I wonder if this code could be clearer if it were moar functional.

File: components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerMigrationTest.kt [hunk 5]
```diff
@@ -339,4 +339,116 @@ class SessionManagerMigrationTest {
...
+        manager.add(session6)
+        manager.add(session7)
+        manager.add(session8)
+        manager.add(session9)
+
+        manager.select(session4)
+        assertEquals(session4, manager.selectedSession)
+        assertEquals("session4", store.state.selectedTabId)
+
+        println("Remove session 4")
```
[the remark this answers is not in the document]
Comment (pocmo) [reply components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerMigrationTest.kt]: Oh, I can remove those now. That was only for debugging.

File: components/browser/session/src/main/java/mozilla/components/browser/session/LegacySessionManager.kt (hunk 2 above)
Comment (pocmo) [reply components/browser/session/src/main/java/mozilla/components/browser/session/LegacySessionManager.kt]: Tried `sublist.filter.size` and I like it! Also with that this can be `val` instead of `var`.

It doesn't like an invalid range though (e.g. `fromIndex(0) > toIndex(-1)`)

However with `take(max(0, ....))` that works. It's not easier to read though. :D

Comment (pocmo) [reply components/browser/session/src/main/java/mozilla/components/browser/session/LegacySessionManager.kt]: Oh, mh, now I have a test failure. I'll change it back. Don't want to look at that code any longer... :)

File: components/browser/session/src/main/java/mozilla/components/browser/session/LegacySessionManager.kt (hunk 4 above)
Comment (pocmo) [reply components/browser/session/src/main/java/mozilla/components/browser/session/LegacySessionManager.kt]: The goal of the rewrite was to have the same behavior here as in `TabListReducer` of `browser-state` so that the new test (see #3567) passes.

I agree that this could be rewritten in a way more sane way. But I tried to write as little code as possible since this is the old code that is going away and I didn't want to refactor all that. So yeah, this legacy code is now a bit stupid and does definitely not optimized.

The same code in `TabListReducer` is thankfully much simpler:
https://github.com/mozilla-mobile/android-components/blob/master/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TabListReducer.kt#L171
