### PR TITLE
Close #6799: Add url info in metadata for media notification

### LINKED ISSUE #6799: Missing URL info in lockscreen while playing media
Related to https://github.com/mozilla-mobile/fenix/issues/9883.
Media notification is showing "Unknown" in lock screen with Samsung devices.
On Pixel 3 Media notification is missing URL information in lock screen.

### LINKED ISSUE #9883: Throwing error while generating android type declaration file
I am trying to generate type declaration files using dts-generator and I am getting below error:

```
Error executing Typescript Definitions Generator: Bad method signature: (Lcom/android/builder/model/DimensionAware;:Lorg/gradle/api/Named;)V
java.lang.IllegalArgumentException: Bad method signature: (Lcom/android/builder/model/DimensionAware;:Lorg/gradle/api/Named;)V
        at edu.umd.cs.findbugs.ba.generic.GenericSignatureParser.<init>(GenericSignatureParser.java:155)
        at edu.umd.cs.findbugs.ba.generic.GenericUtilities.getType(GenericUtilities.java:263)
        at com.telerik.dts.TypeDefinition.setTypeGenerics(TypeDefinition.java:101)
        at com.telerik.dts.TypeDefinition.checkSignature(TypeDefinition.java:70)
        at com.telerik.dts.TypeDefinition.<init>(TypeDefinition.java:47)
        at com.telerik.dts.DtsApi.generateDtsContent(DtsApi.java:99)
        at com.telerik.dts.Generator.generateDts(Generator.java:57)
        at com.telerik.dts.Generator.start(Generator.java:42)
        at com.telerik.Main.main(Main.java:38)

```

Could you please help me on this?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8371)

### PR DESCRIPTION
**Pull request by rocketsroger**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaServiceDelegate.kt [hunk 1]
```diff
@@ -125,6 +126,9 @@ internal class MediaServiceDelegate(
                 .putString(
                     MediaMetadataCompat.METADATA_KEY_TITLE,
                     state.getActiveMediaTab().getTitleOrUrl(context))
+                .putString(
+                    MediaMetadataCompat.METADATA_KEY_ARTIST,
+                    state.getActiveMediaTab().nonPrivateUrl)
```
Comment (pocmo) [inline components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaServiceDelegate.kt:131]: `getTitleOrUrl(context))` is not an option here?

Comment (rocketsroger) [reply components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaServiceDelegate.kt:131]: No, then on the lock screen it will have the same line twice.  The title above is already using `getTitleOrUrl`.  The "artist" part is the same as the subtitle of the media notification.

**Comment by rocketsroger** [comment]
bors r=pocmo
