### PR TITLE
Closes #8681: Do not retry to update an extension when an unrecoverable exception happens

### LINKED ISSUE #8681: Add updates could be running more frequent than expected
Related bug https://bugzilla.mozilla.org/show_bug.cgi?id=1670503

### PR DESCRIPTION
**Pull request by Amejia481**
Before adding a completed solution, I wanted to show you this approach and see what do you think.

The issue that the GV team described on [bug 1670503](https://bugzilla.mozilla.org/show_bug.cgi?id=1670503), was caused because, we were incrementally retrying to update when we were trying to update an exception that required an extra permission and as a result user's interaction, subsequently this caused that multiple files were created in the intent and never got purged. 

The approach here it's just to only retry if we get an exception code that indicates that the failure was due to a 
situational thing like an network error. The whole list of exceptions can be found [here](https://searchfox.org/mozilla-central/source/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/WebExtension.java#1385 ), so far this is the only one that I think we can recover from.
 
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt [hunk 1]
```diff
@@ -180,6 +181,13 @@ abstract class WebExtension(
      * available icon to the provided size.
      */
     abstract suspend fun loadIcon(size: Int): Bitmap?
+
+    /**
+     * An error that occur trying to perform an action like installing, removing or updating
+     * an [WebExtension] that is not recoverable.
+     */
+    class UnRecoverableError(throwable: Throwable) : Error(throwable)
```
Comment (csadilek) [inline components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt:189]: I wouldn't nest this under `WebExtension`. It can be in the same file, but also a top-level type.

File: components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt [hunk 2]
```diff
@@ -267,7 +269,13 @@ class GeckoEngine(
             onSuccess(updatedExtension)
             GeckoResult<Void>()
         }, { throwable ->
-            onError(extension.id, throwable)
+
+            val exception = if (throwable is InstallException && throwable.code != ERROR_NETWORK_FAILURE) {
```
Comment (csadilek) [inline components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt:273]: Looks like ERROR_USER_CANCELED and ERROR_POSTPONED should also be treated as recoverable? For the former we don't have UI, but seems worth handling regardless.

File: components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt (hunk 1 above)
Comment (csadilek) [reply components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt:189]: An alternative could be to have a top-level `GeckoWebExtensionUpdateError` or `GeckoWebExtensionInstallError` which wraps/contains the underlying exception. Then we can add a `isRecoverable` function to it directly?

**Review by csadilek — COMMENTED** [review]
👍 some comments/suggestions below, but I think this is a good idea.

File: components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt (hunk 1 above)
Comment (Amejia481) [reply components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt:189]: I thought that Errors were meant to express a [situation where an app should not try to recover from](https://docs.oracle.com/javase/7/docs/api/java/lang/Error.html), if that is correct the `Error` post-fix implies that the situation is not recoverable, for using an `isRecoverable` property  then we would  need an more generic exception `WebExtensionException` that could be useful for both cases recoverable and not recoverable. I omitted `Gecko` prefix as these type of exceptions can be handle in higher level component that is not aware of the Gecko or other engine implementation.

Comment (Amejia481) [reply components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt:189]: `WebExtensionException` is a more generic as allows to cover installation/update

Comment (csadilek) [reply components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt:189]: Right, yeah, which is why I am suggesting we have a `WebExtension[Install|Update]Exception` with a `isRecoverable` function, instead of a type for a special case.

Comment (csadilek) [reply components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt:189]: The `Gecko` prefix you will need as the exception will wrap Gecko's, similar to how `GeckoWebExtension` is a `WebExtension` and wraps a native GeckoView extension.

Comment (csadilek) [reply components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt:189]: Higher up in the stack you would handle `WebExtensionException` (or `WebExtensionInstallException` if you want to call it that).

Comment (Amejia481) [reply components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt:189]: > Right, yeah, which is why I am suggesting we have a WebExtension[Install|Update]Exception with a isRecoverable function, instead of a type for a special case.
👍🏽

**Comment by Amejia481** [comment]
@csadilek this is ready for view :)

**Review by csadilek — APPROVED** [review]
🚢
