### PR TITLE
Close #9011: Unsubscribe before subscribing to fix FxA push

### LINKED ISSUE #9011: Call unsubscribe first when fixing FxA push subscription and subscription has expired
From the changes in https://github.com/mozilla-mobile/android-components/issues/8846, we now know that just calling "subscribe" is not good enough to fix the bug.

Looking at the logs we can see that we still get the same endpoint as before:
```
11-18 10:52:37.294 10457 10493 I FxaDeviceConstellation: Refreshing device list...
11-18 10:52:37.294 10457 10493 I FxaDeviceConstellation: Executing: fetching all devices
11-18 10:52:37.634 10457 10493 I FxaDeviceConstellation: Successfully executed: fetching all devices
11-18 10:52:37.634 10457 10493 I FxaDeviceConstellation: Current device needs push endpoint registration
11-18 10:52:37.634 10457 10493 I FxaDeviceConstellation: Refreshed device list; saw 3 device(s).
11-18 10:52:37.634 10457 10493 I FxaDeviceConstellation: Notifying observer about constellation updates.
11-18 10:52:37.634 10457 10493 I ConstellationObserver: onDevicesUpdate triggered.
11-18 10:52:37.634 10457 10493 I ConstellationObserver: Proceeding to renew registration
11-18 10:52:37.634 10457 10493 I ConstellationObserver: We have been notified that our push subscription has expired; re-subscribing.
11-18 10:52:37.636 10457 10493 I ConstellationObserver: Incrementing verifier
11-18 10:52:37.638 10457 10493 I ConstellationObserver: Verifier state before: timestamp=1605656389093, count=1
11-18 10:52:37.638 10457 10493 I ConstellationObserver: Verifier state after: timestamp=1605656389093, count=2
11-18 10:52:37.638 10457 10493 I FxaDeviceConstellation: Notifying observer about constellation updates.
11-18 10:52:37.639 10457 10503 I FxaDeviceConstellation: Executing: polling for device commands
11-18 10:52:37.643 10457 10513 I ConstellationObserver: Created a new subscription: AutoPushSubscription(scope=fxa_push_scope_a883246ee2f64d86b5bc689c753bbb13, endpoint=https://updates.push.services.mozilla.com/wpush/v1/gAAAAABe_4aOtJAHlUeCfFVs2uw_TcWnKIuW0l3eNyP_wOrHIUjxNyu_2jMg5e3SPgp44429O11qUIcZXRapoID0_CJ1k329YQpKPbwuFHqlFHAXnZWUJ8iolOhosOUvyqAptbgDCl1G, publicKey=BGO-fmuG3LhseVGb1ufq1lxrv9dVVv5U0yjFg4PC3AOkhIaK47TInbRpKLIipdHg-_oXpcWldNKWV8CfGrTqn-4, authKey=hXzoVZNKYnodQcUj9QnYuA, appServerKey=null)
11-18 10:52:37.644 10457 10513 W ConstellationObserver: Push endpoints match!
11-18 10:52:37.644 10457 10513 W ConstellationObserver: java.lang.IllegalStateException: New push endpoint matches existing one
11-18 10:52:37.644 10457 10513 W ConstellationObserver: 	at mozilla.components.feature.accounts.push.ConstellationObserver.onSubscribe$feature_accounts_push_release(FxaPushSupportFeature.kt:6)
11-18 10:52:37.644 10457 10513 W ConstellationObserver: 	at mozilla.components.feature.accounts.push.ConstellationObserver$onDevicesUpdate$2.invoke(FxaPushSupportFeature.kt:3)
11-18 10:52:37.644 10457 10513 W ConstellationObserver: 	at mozilla.components.feature.push.AutoPushFeature$subscribe$$inlined$ifInitialized$lambda$2.invokeSuspend(AutoPushFeature.kt:7)
11-18 10:52:37.644 10457 10513 W ConstellationObserver: 	at mozilla.components.feature.push.AutoPushFeature$subscribe$$inlined$ifInitialized$lambda$2.invoke(Unknown Source:10)
11-18 10:52:37.644 10457 10513 W ConstellationObserver: 	at mozilla.components.feature.push.ext.CoroutineScopeKt$launchAndTry$2.invokeSuspend(CoroutineScope.kt:5)
11-18 10:52:37.644 10457 10513 W ConstellationObserver: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
11-18 10:52:37.644 10457 10513 W ConstellationObserver: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
11-18 10:52:37.644 10457 10513 W ConstellationObserver: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-18 10:52:37.644 10457 10513 W ConstellationObserver: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-18 10:52:37.644 10457 10513 W ConstellationObserver: 	at java.lang.Thread.run(Thread.java:923)
11-18 10:52:37.644 10457 10513 W ConstellationObserver: Caused by: java.lang.Throwable: New endpoint: https://updates.push.services.mozilla.com/wpush/v1/gAAAAABe_4aOtJAHlUeCfFVs2uw_TcWnKIuW0l3eNyP_wOrHIUjxNyu_2jMg5e3SPgp44429O11qUIcZXRapoID0_CJ1k329YQpKPbwuFHqlFHAXnZWUJ8iolOhosOUvyqAptbgDCl1G
11-18 10:52:37.644 10457 10513 W ConstellationObserver: Old endpoint: https://updates.push.services.mozilla.com/wpush/v1/gAAAAABe_4aOtJAHlUeCfFVs2uw_TcWnKIuW0l3eNyP_wOrHIUjxNyu_2jMg5e3SPgp44429O11qUIcZXRapoID0_CJ1k329YQpKPbwuFHqlFHAXnZWUJ8iolOhosOUvyqAptbgDCl1G
11-18 10:52:37.644 10457 10513 W ConstellationObserver: 	at mozilla.components.feature.accounts.push.ConstellationObserver.onSubscribe$feature_accounts_push_release(FxaPushSupportFeature.kt:5)
11-18 10:52:37.644 10457 10513 W ConstellationObserver: 	... 9 more
11-18 10:52:37.645 10457 10497 I FxaDeviceConstellation: Executing: updating device push subscription
11-18 10:52:37.905 10457 10497 I FxaDeviceConstellation: Successfully executed: updating device push subscription
11-18 10:52:37.933 10457 10503 I FxaDeviceConstellation: Successfully executed: polling for device commands
```

What we should do, is call unsubscribe first.

See also: https://github.com/mozilla-mobile/android-components/issues/8846#issuecomment-729813615

### PR DESCRIPTION
**Pull request by jonalmeida**
We know now from snorp's testing and the logs we retrieved that calling subscribe alone isn't enough.

JR confirmed that calling unsubscribe first will guarantee that we get a new subscription when we call subscribe. So let's do that first!

Ignoring changelog since this would go with the previous entry.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/feature/accounts-push/src/main/java/mozilla/components/feature/accounts/push/FxaPushSupportFeature.kt [hunk 1]
```diff
@@ -203,6 +203,11 @@ internal class ConstellationObserver(
         }
 
         logger.info("We have been notified that our push subscription has expired; re-subscribing.")
+        push.unsubscribe(
+            scope = scope,
+            onUnsubscribeError = { logger.warn("Un-subscribing failed; subscribe may return the same endpoint", it) },
```
Comment (grigoryk) [inline components/feature/accounts-push/src/main/java/mozilla/components/feature/accounts/push/FxaPushSupportFeature.kt:208]: Can we leave a sentry breadcrumb here? Ideally this would also be a failed assertion in sentry (submit caught exception) for cases that aren't network related.

**Review by grigoryk — APPROVED** [review]

File: components/feature/accounts-push/src/main/java/mozilla/components/feature/accounts/push/FxaPushSupportFeature.kt (hunk 1 above)
Comment (jonalmeida) [reply components/feature/accounts-push/src/main/java/mozilla/components/feature/accounts/push/FxaPushSupportFeature.kt:208]: Good point!

**Comment by jonalmeida** [comment]
Offline review:
 - Add breadcrumb.
 - Don't log the full endpoint (URI strip the last part?).

**Comment by jonalmeida** [comment]
> Offline review:
> 
>     * Add breadcrumb.
> 
>     * Don't log the full endpoint (URI strip the last part?).

Done!

Added `String.redactPartialUri()` to remove the end (!) of the endpoint.
