### PR TITLE
Fixes #9584 - Catch all the exceptions from Nimbus Rust SDK

### LINKED ISSUE #9573: Duplicate line in Nimbus init
As a followup to https://github.com/mozilla-mobile/fenix/pull/17684 we noticed that #9021 introduced a duplicate line initializing `dataDir`.

This issue is to remove the duplicate line and either: remove the property already, or remove the local variable.

### LINKED ISSUE #9584: Improve error reporting during Nimbus startup.
As follow on from https://github.com/mozilla-mobile/fenix/pull/17684 we should further decrease the likelihood of errors by catching and logging errors.

### PR DESCRIPTION
**Pull request by jhugman**
Fixes #9584
Fixes https://github.com/mozilla-mobile/fenix/issues/17762
Fixes #9573

This is a hotfix, to enable nightly shipping and perf testing.

We should file a followup issue to utilize a CrashReporter.

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Review by Amejia481 — APPROVED** [review]

File: components/service/nimbus/src/main/java/mozilla/components/service/nimbus/Nimbus.kt [hunk 1]
```diff
@@ -320,13 +337,22 @@ class Nimbus(
 
     @WorkerThread
     @VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
-    private fun setExperimentsLocallyOnThisThread(payload: String) {
```
Comment (csadilek) [inline components/service/nimbus/src/main/java/mozilla/components/service/nimbus/Nimbus.kt:323]: Looks like the caller https://github.com/mozilla-mobile/android-components/blob/cbc512c1fa61d2e43589fc59decc1167d8b4d130/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/Nimbus.kt#L325 does IO and needs to catch to?

**Review by csadilek — APPROVED** [review]
One comment below re: setExperimentsLocally, but 👍
