### PR TITLE
Fixes #5685 & Fixes #5686: Fixes SSL button in error pages & removes css

### LINKED ISSUE #5685: Error page SSL advanced button always shown
We're doing an incorrect evaluation in the JS file

### LINKED ISSUE #5686: Remove redundant CSS resource in `createUrlEncodedErrorPage`
We're not currently using it and consumers can just pass in an HTML page that uses whatever CSS it wants.

### PR DESCRIPTION
**Pull request by sblatz**
---

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/browser/errorpages/src/main/assets/errorPageScripts.js [hunk 1]
```diff
@@ -43,11 +43,11 @@ var advancedVisible = false;
  * Used to show or hide the "advanced" button based on the validity of the SSL certificate
  */
 function updateShowSSL(queryMap) {
-    const showSSL = queryMap.showSSL
+    const showSSL = queryMap.showSSL;
```
Comment (NotWoods) [inline components/browser/errorpages/src/main/assets/errorPageScripts.js]: We should have some comment indicating the intended values of this variable.
```suggestion
    /** @type {'true' | 'false'} */
    const showSSL = queryMap.showSSL;
```

**Comment by NotWoods** [comment]
bors r=NotWoods

**Comment by sblatz** [comment]
bors retry
