### PR TITLE
Close #6421: Download try again should not crash when download does not exist

### LINKED ISSUE #6421: IllegalStateException: download must not be null
https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/7663623/

```
IllegalStateException: download must not be null
    at mozilla.components.feature.downloads.manager.FetchDownloadManager.tryAgain(FetchDownloadManager.kt:3)
    at mozilla.components.feature.downloads.DownloadsFeature.tryAgain(DownloadsFeature.kt:1)
    at org.mozilla.fenix.browser.BaseBrowserFragment$initializeUI$$inlined$also$lambda$7$1.invoke(BaseBrowserFragment.kt:3)
    at -$$LambdaGroup$js$vSvBtMcliXwjaE59xzbJRgV9aME.onClick(java-style lambda group:148)
    at android.view.View.performClick(View.java:5721)
...
(9 additional frame(s) were not displayed)

download must not be null
```

### PR DESCRIPTION
**Pull request by rocketsroger**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/FetchDownloadManager.kt [hunk 1]
```diff
@@ -76,7 +76,7 @@ class FetchDownloadManager<T : AbstractFetchDownloadService>(
     }
 
     override fun tryAgain(downloadId: Long) {
-        val download = queuedDownloads[downloadId]
+        val download = queuedDownloads[downloadId] ?: return
```
Comment (Amejia481) [inline components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/FetchDownloadManager.kt:79]: Are there any steps to reproduce this issue? I want to find the root cause, If we do that, are we just preventing the crash, but the notification is going to persist, without any behaviour? I noticed in [unregisterListeners](https://github.com/mozilla-mobile/android-components/blob/ba60c8df899b4e6fd32341fc6a2fc011b1009376/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/FetchDownloadManager.kt#L91), we are clearing the `queuedDownloads`, should we also remove all the pending notifications too, as the `downloads` in the downloads notification are not going to be valid anymore?

Comment (rocketsroger) [reply components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/FetchDownloadManager.kt:79]: I didn't find any good way to reproduce it.  I can only hard code the failure locally in my testing.  You bring up a good point.  Since `unregisterListeners` clears the download queue we should also clear all download notifications.  I'll look more into this.  Thanks,

Comment (Amejia481) [reply components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/FetchDownloadManager.kt:79]: 👍 
We have to be careful if we clear notifications as they could be in a downloading state

Comment (rocketsroger) [reply components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/FetchDownloadManager.kt:79]: Sure, I'll confirm if clearing notification is doable.

Comment (rocketsroger) [reply components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/FetchDownloadManager.kt:79]: I think this requires a different fix.  I'm only fixing the symptoms here but not the cause.  The more I look the more issues I see with this download queue.  I'll find a different solution to fix this.  Thanks,

Comment (Amejia481) [reply components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/FetchDownloadManager.kt:79]: Don't worry, proceed with this patch. I'm working on a related issue https://github.com/mozilla-mobile/fenix/issues/9884 and I believe I found the source of the issue.  👍

**Comment by rocketsroger** [comment]
bors r=Amejia481
