### PR TITLE
Fixes #2976 - Implement feature-app-links

### LINKED ISSUE #2974: Implement feature-app-links to support in page app banners.
Connected: #2936 

This feature component `feature-app-links` should listen to the URL changing in a session and [attempt to open in as a native app, or launch a fallback, or launch the Play store][docs].

This should only be the result of a user interaction.

This is to support web pages that implement their own app banners.

The fallback is implemented thus:

* Checks to see if it's a URL scheme that Fennec can handle — do so here.
* If not, then [parses the `custom://` URLs based upon schemes only and checks it against the OS scheme handlers][fennec-ask]
* if not, then [fallbacks if no app deals with that scheme][fennec-noHandler], either by going to the market place or a fallback URL supplied in the URL.
 * Finally, checking the time since last user interation (as a proxy for whether the user clicked on the link), then fail silently or display an unknown protocol error.

[docs]: https://developer.chrome.com/multidevice/android/intents
[fennec-ask]: https://dxr.mozilla.org/mozilla-central/source/mobile/android/components/ContentDispatchChooser.js#51
[fennec-noHandler]: https://dxr.mozilla.org/mozilla-central/source/mobile/android/base/java/org/mozilla/gecko/IntentHelper.java#491
[android-queryIntentActivities]: https://developer.android.com/reference/kotlin/android/content/pm/PackageManager.html#queryIntentActivities(android.content.Intent,%20int)

### LINKED ISSUE #2976: Add API for showing if the current page can be opened in a native app.
Connected #2936 .
Depends on #2974.

 * Add API for session observers to observe if the session's URL can be opened by a native app (this is more generic intent filtering, not just `custom://` protocols.
   - Ensure that we're filtering out generic browsers from this list.
   - Add API/UI for choosing the app to open from a filtered list of apps.

### PR DESCRIPTION
**Pull request by jhugman**
Fixes #2976.

This PR introduces a new feature component: `feature-app-links`.

It provides use cases for testing and opening a link in an external/non-browser app. 

Some of the UI for #2975 and the link interception in #2974 is also here, but turned off by a boolean flag.

### Pull Request checklist

- [X] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [X] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

File: components/feature/app-links/src/main/java/mozilla/components/feature/app/links/RedirectDialogFragment.kt [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+ * to show a dialog before an external link is opened.
+ * If [SimpleRedirectDialogFragment] is not flexible enough for your use case you should inherit for this class.
+ * Be mindful to call [onConfirmRedirect] when you want to start the download.
+ */
+abstract class RedirectDialogFragment : DialogFragment() {
+
+    /**
+     * A callback to trigger a download, call it when you are ready to start a download. For instance,
+     * a valid use case can be in confirmation dialog, after the positive button is clicked,
+     * this callback must be called.
```
Comment (Amejia481) [inline components/feature/app-links/src/main/java/mozilla/components/feature/app/links/RedirectDialogFragment.kt]: >       * A callback to trigger a download, call it when you are ready to start a download. For instance,

See the comment above.

File: components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinkRedirect.kt [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+ * This Source Code Form is subject to the terms of the Mozilla Public
+ * License, v. 2.0. If a copy of the MPL was not distributed with this
+ * file, You can obtain one at http://mozilla.org/MPL/2.0/.
+ */
+
+package mozilla.components.feature.app.links
+
+import android.content.Intent
+
+data class AppLinkRedirect(
```
Comment (Amejia481) [inline components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinkRedirect.kt]: Could we add some docs here?

File: components/feature/app-links/src/main/res/values/strings.xml [hunk 3]
```diff
@@ -0,0 +1,13 @@
+<?xml version="1.0" encoding="utf-8"?>
+<!--
+  ~ This Source Code Form is subject to the terms of the Mozilla Public
+  ~ License, v. 2.0. If a copy of the MPL was not distributed with this
+  ~ file, You can obtain one at http://mozilla.org/MPL/2.0/.
+  -->
+
+<resources>
```
Comment (Amejia481) [inline components/feature/app-links/src/main/res/values/strings.xml]: I think we need add this file to the `l10n.toml`file to get these strings translated.

File: components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt [hunk 4]
```diff
@@ -0,0 +1,147 @@
...
+                }
+
+                override fun cancel() {
+                    dismiss()
+                }
+            })
+
+            dialog.show(fragmentManager, FRAGMENT_TAG)
+
+            // TODO check that the user has made a choice.
```
Comment (Amejia481) [inline components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt]: I think we also have to take into consideration when the app gets kill by the OS, to reattach the callbacks. You can see an example on [DownloadsFeature](https://github.com/mozilla-mobile/android-components/blob/79ca1f4915b806d6292f57e527d93062ca036064/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt#L59).

File: components/feature/app-links/src/androidTest/java/mozilla/components/feature/app/links/PlaceholderTests.kt [hunk 5]
```diff
@@ -0,0 +1,9 @@
+/*
+ * This Source Code Form is subject to the terms of the Mozilla Public
+ * License, v. 2.0. If a copy of the MPL was not distributed with this
+ * file, You can obtain one at http://mozilla.org/MPL/2.0/.
+ */
+
+package mozilla.components.feature.app.links
+
+class PlaceholderTests
```
Comment (Amejia481) [inline components/feature/app-links/src/androidTest/java/mozilla/components/feature/app/links/PlaceholderTests.kt]: Is this mean that test will come in the future ? :)

File: components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt [hunk 6]
```diff
@@ -0,0 +1,46 @@
...
+ * In the case of Android Intents that are not installed, and with no fallback, the user is prompted
+ * to search the installed market place.
+ *
+ * It provides use cases to detect and open links openable in third party non-browser apps.
+ *
+ * It provides a [RequestInterceptor] to do the detection and asking of consent.
+ *
+ * It requires: a [Context], and a [FragmentManager].
+ */
+class AppLinksFeature(
```
Comment (Amejia481) [inline components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt]: I'm not quite sure if this is a feature. Normally feature starts and stops. Here we're only  exposing the interceptor and a use case @pocmo  what do you think?

File: components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt [hunk 7]
```diff
@@ -0,0 +1,141 @@
...
```
Comment (Amejia481) [inline components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt]: I think we should add the url issue that links to the pending `//TODO` work.

**Comment by Amejia481** [comment]
@jhugman  Also, I will be pretty cool 😎 , if we showcase this component in the sample browser, this will help to see how everything gets wire up together.

File: components/feature/app-links/src/main/java/mozilla/components/feature/app/links/RedirectDialogFragment.kt [hunk 8]
```diff
@@ -0,0 +1,46 @@
...
+package mozilla.components.feature.app.links
+
+import android.os.Bundle
+import androidx.fragment.app.DialogFragment
+
+/**
+ * This is a general representation of a dialog meant to be used in collaboration with [AppLinksFeature]
+ * to show a dialog before an external link is opened.
+ * If [SimpleRedirectDialogFragment] is not flexible enough for your use case you should inherit for this class.
+ * Be mindful to call [onConfirmRedirect] when you want to start the download.
```
[the remark this answers is not in the document]
Comment (jhugman) [reply components/feature/app-links/src/main/java/mozilla/components/feature/app/links/RedirectDialogFragment.kt]: Sure, this was copy pasta. Will fix.

File: components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt [hunk 9]
```diff
@@ -0,0 +1,147 @@
+/*
+ * This Source Code Form is subject to the terms of the Mozilla Public
+ * License, v. 2.0. If a copy of the MPL was not distributed with this
+ * file, You can obtain one at http://mozilla.org/MPL/2.0/.
+ */
+
+/*
```
[the remark this answers is not in the document]
Comment (jhugman) [reply components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt]: :+1:

File: components/feature/app-links/build.gradle [hunk 10]
```diff
@@ -0,0 +1,64 @@
...
+            minifyEnabled false
+            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
+        }
+    }
+
+    packagingOptions {
+        exclude 'META-INF/proguard/androidx-annotations.pro'
+    }
+
+    sourceSets {
```
[the remark this answers is not in the document]
Comment (jhugman) [reply components/feature/app-links/build.gradle]: :+1:

File: components/feature/app-links/src/main/java/mozilla/components/feature/app/links/RedirectDialogFragment.kt (hunk 8 above)
[the remark this answers is not in the document]
Comment (jhugman) [reply components/feature/app-links/src/main/java/mozilla/components/feature/app/links/RedirectDialogFragment.kt]: :+1:

[the remark this answers is not in the document]
Comment (Amejia481) [reply components/feature/app-links/src/main/java/mozilla/components/feature/app/links/RedirectDialogFragment.kt]: 🍝

File: docs/api/package-list [hunk 11]
```diff
@@ -150,6 +150,7 @@ mozilla.components.concept.sync
 mozilla.components.concept.tabstray
 mozilla.components.concept.toolbar
 mozilla.components.feature.accounts
+mozilla.components.feature.app.links
```
[the remark this answers is not in the document]
Comment (jhugman) [reply docs/api/package-list]: Should this not be? What is the `package-list` for, and which components make it on to the list?

File: components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt [hunk 12]
```diff
@@ -0,0 +1,147 @@
...
+import androidx.fragment.app.FragmentManager
+import mozilla.components.concept.engine.EngineSession
+import mozilla.components.feature.app.links.RedirectDialogFragment.Companion.FRAGMENT_TAG
+import mozilla.components.support.ktx.android.net.isHttpOrHttps
+import java.util.UUID
+
+private const val EXTRA_BROWSER_FALLBACK_URL = "browser_fallback_url"
+private const val MARKET_INTENT_URI_PACKAGE_PREFIX = "market://details?id="
+
+class AppLinksUseCases(
```
[the remark this answers is not in the document]
Comment (jhugman) [reply components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt]: :+1:

File: components/feature/app-links/src/main/res/values/strings.xml (hunk 3 above)
Comment (jhugman) [reply components/feature/app-links/src/main/res/values/strings.xml]: 👍

File: components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt (hunk 4 above)
Comment (jhugman) [reply components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt]: :+1:

File: components/feature/app-links/README.md [hunk 13]
```diff
@@ -0,0 +1,20 @@
...
+### Setting up the dependency
+
+Use Gradle to download the library from [maven.mozilla.org](https://maven.mozilla.org/) ([Setup repository](../../../README.md#maven-repository)):
+
+```Groovy
+implementation "org.mozilla.components:feature-app-links:{latest-version}"
+```
+
+## Usage
+
```
Comment (pocmo) [inline components/feature/app-links/README.md]: nit: Looks like "Setting up the dependency" moved above "Usage" here :)

File: components/feature/app-links/build.gradle [hunk 14]
```diff
@@ -0,0 +1,61 @@
...
+
+    implementation project(':support-ktx')
+    implementation project(':support-base')
+
+    implementation Dependencies.kotlin_stdlib
+    implementation Dependencies.kotlin_coroutines
+
+    implementation Dependencies.androidx_paging
+    implementation Dependencies.androidx_lifecycle_extensions
+    kapt Dependencies.androidx_lifecycle_compiler
```
Comment (pocmo) [inline components/feature/app-links/build.gradle]: At least `paging` seems to be unused here.

File: components/browser/session/src/main/java/mozilla/components/browser/session/Session.kt [hunk 15]
```diff
@@ -196,6 +197,13 @@ class Session(
         }
     }
 
+    /**
+     * Set when a load request is received, indicating if the user was involved in the interaction.
+     */
+    var triggeredByUserInteraction: Boolean by Delegates.observable(false) {
+        _, _, new -> notifyObservers { onLoadRequest(this@Session, new) }
```
Comment (pocmo) [inline components/browser/session/src/main/java/mozilla/components/browser/session/Session.kt]: nit: Technically we are a bit "misusing" `Session` to forward events happening in `Engine.Observer`. Usually this here is a callback to notify subscribers to `Session` that a value has changed - however here we are always triggering an `onLoadRequest`.

File: components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt [hunk 16]
```diff
@@ -0,0 +1,124 @@
...
+    private val context: Context,
+    private val sessionManager: SessionManager,
+    private val sessionId: String? = null,
+    private val interceptLinkClicks = false,
+    private val fragmentManager: FragmentManager? = null,
+    private var dialog: RedirectDialogFragment = SimpleRedirectDialogFragment.newInstance(),
+    private val useCases = AppLinksUseCases(context)
+) : SelectionAwareSessionObserver(sessionManager), LifecycleAwareFeature {
```
Comment (pocmo) [inline components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt]: nit: I often prefer to implement `SelectionAwareSessionObserver` has a property instead of extending it from a feature. Extending it will expose all the methods from `SessionManager.Observer` and `Session.Observer` on this feature class - potentially confusing consumers using autocomplete.

File: components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt [hunk 17]
```diff
@@ -0,0 +1,124 @@
...
+ *
+ * It provides a [RequestInterceptor] to do the detection and asking of consent.
+ *
+ * It requires: a [Context], and a [FragmentManager].
+ *
+ * A [Boolean] flag is provided at construction to allow the feature and use cases to be landed without
+ * adjoining UI. The UI will be activated in https://github.com/mozilla-mobile/android-components/issues/2974
+ * and https://github.com/mozilla-mobile/android-components/issues/2975.
+ */
+class AppLinksFeature(
```
Comment (pocmo) [inline components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt]: This class doesn't seem to be covered by tests. Could it be if we mock some of the fragment stuff?

File: components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt [hunk 18]
```diff
@@ -0,0 +1,124 @@
...
+        if (interceptLinkClicks) {
+            observeIdOrSelected(sessionId)
+        }
+        findPreviousDialogFragment()?.let {
+            reAttachOnStartDownloadListener(it)
+        }
+    }
+
+    @SuppressLint("MissingPermission")
+    private fun showDialog(redirect: AppLinkRedirect, session: Session) {
```
Comment (pocmo) [inline components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt]: The name of this method has confused me while reading the code: In some cases it doesn't actually show a dialog but instead opens the app directly. :)

File: components/browser/session/src/main/java/mozilla/components/browser/session/Session.kt [hunk 19]
```diff
@@ -196,6 +197,13 @@ class Session(
         }
     }
 
+    /**
+     * Set when a load request is received, indicating if the user was involved in the interaction.
+     */
+    var triggeredByUserInteraction: Boolean by Delegates.observable(false) {
```
[the remark this answers is not in the document]
Comment (jhugman) [reply components/browser/session/src/main/java/mozilla/components/browser/session/Session.kt]: 👍

File: components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt (hunk 16 above)
Comment (jhugman) [reply components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt]: :+1:

File: components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt (hunk 18 above)
Comment (jhugman) [reply components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt]: :+1:

File: components/feature/app-links/README.md (hunk 13 above)
Comment (jhugman) [reply components/feature/app-links/README.md]: 👍

**Comment by jonalmeida** [comment]
@jhugman we've added the strings for this feature in another component for the strings freeze deadline. You can move them over to this PR later on. See https://github.com/mozilla-mobile/android-components/issues/3113

File: components/feature/app-links/build.gradle (hunk 14 above)
Comment (jhugman) [reply components/feature/app-links/build.gradle]: :+1:

File: components/browser/session/src/main/java/mozilla/components/browser/session/Session.kt (hunk 15 above)
Comment (jhugman) [reply components/browser/session/src/main/java/mozilla/components/browser/session/Session.kt]: 👍

File: components/feature/app-links/src/androidTest/java/mozilla/components/feature/app/links/PlaceholderTests.kt (hunk 5 above)
Comment (pocmo) [inline components/feature/app-links/src/androidTest/java/mozilla/components/feature/app/links/PlaceholderTests.kt]: I guess we can remove that one now? :)

File: components/feature/app-links/README.md [hunk 20]
```diff
@@ -0,0 +1,40 @@
+# [Android Components](../../../README.md) > Feature > App-Links
+
+A session components to support opening non-browser apps and `intent://` style URLs.
```
Comment (pocmo) [inline components/feature/app-links/README.md]: "components"

File: components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinkRedirect.kt [hunk 21]
```diff
@@ -0,0 +1,24 @@
...
+    val appIntent: Intent?,
+    val webUrl: String?,
+    val isFallback: Boolean
+) {
+    fun hasExternalApp() = appIntent != null
+
+    fun hasFallback() = webUrl != null && isFallback
+
+    fun isRedirect() = hasExternalApp() || hasFallback()
+}
```
Comment (pocmo) [inline components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinkRedirect.kt]: I wonder if in a future iteration (not this PR) we could put this `AppLinkRedirect` into `Session` instead of a flag? Code (like the feature) could then react based on this high-level data class instead of just the flag (e.g. `AppLinksFeature` listens to a Redirect object in the Session).

**Comment by jhugman** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1555337 to get more better reporting of a link coming out of GeckoView.

Changed `triggeredByUserInteraction` to match GeckoView docs (`triggeredByRedirect`), and added a `triggeredByWebContent`, to differentiate between the user tapping a link and entering something in the URL bar.

**Comment by jhugman** [comment]
@pocmo @Amejia481 please could you re-review?

File: components/feature/app-links/README.md (hunk 20 above)
Comment (jhugman) [reply components/feature/app-links/README.md]: :+1:

File: components/feature/app-links/src/androidTest/java/mozilla/components/feature/app/links/PlaceholderTests.kt (hunk 5 above)
Comment (jhugman) [reply components/feature/app-links/src/androidTest/java/mozilla/components/feature/app/links/PlaceholderTests.kt]: :+1:

File: components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt [hunk 22]
```diff
@@ -0,0 +1,132 @@
...
+        val redirect = useCases.interceptedAppLinkRedirect.invoke(url)
+
+        if (redirect.isRedirect()) {
+            handleRedirect(redirect, session)
+        }
+    }
+
+    @SuppressLint("MissingPermission")
+    @VisibleForTesting
+    fun handleRedirect(redirect: AppLinkRedirect, session: Session) {
```
[the remark this answers is not in the document]
Comment (jhugman) [reply components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt]: :+1:
