### PR TITLE
Close #9829: Move IO work in FxaPushSupportFeature to a coroutine

### LINKED ISSUE #9829: FxaPushSupportFeature reads IO at initialization
We need to change this to happen lazily and off the main thread.

```
2021-03-04 21:37:18.857 7930-9079/? E/AndroidRuntime: FATAL EXCEPTION: pool-9-thread-2
    Process: org.mozilla.fenix.debug, PID: 7930
    java.lang.RuntimeException: StrictMode ThreadPolicy violation
        at org.mozilla.fenix.perf.ThreadPenaltyDeathWithIgnoresListener.penaltyDeath(ThreadPenaltyDeathWithIgnoresListener.kt:44)
        at org.mozilla.fenix.perf.ThreadPenaltyDeathWithIgnoresListener.onThreadViolation(ThreadPenaltyDeathWithIgnoresListener.kt:38)
        at android.os.StrictMode$AndroidBlockGuardPolicy.lambda$onThreadPolicyViolation$1(StrictMode.java:1827)
        at android.os.-$$Lambda$StrictMode$AndroidBlockGuardPolicy$FxZGA9KtfTewqdcxlUwvIe5Nx9I.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1596)
        at android.app.SharedPreferencesImpl.awaitLoadedLocked(SharedPreferencesImpl.java:275)
        at android.app.SharedPreferencesImpl.contains(SharedPreferencesImpl.java:353)
        at mozilla.components.feature.accounts.push.FxaPushSupportFeature$fxaPushScope$2.invoke(FxaPushSupportFeature.kt:78)
        at mozilla.components.feature.accounts.push.FxaPushSupportFeature$fxaPushScope$2.invoke(FxaPushSupportFeature.kt:55)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at mozilla.components.feature.accounts.push.FxaPushSupportFeature.getFxaPushScope(Unknown Source:2)
        at mozilla.components.feature.accounts.push.FxaPushSupportFeature.<init>(FxaPushSupportFeature.kt:89)
        at mozilla.components.feature.accounts.push.FxaPushSupportFeature.<init>(FxaPushSupportFeature.kt:61)
        at org.mozilla.fenix.components.BackgroundServices.makeAccountManager(BackgroundServices.kt:160)
        at org.mozilla.fenix.components.BackgroundServices$accountManager$2.invoke(BackgroundServices.kt:114)
        at org.mozilla.fenix.components.BackgroundServices$accountManager$2.invoke(BackgroundServices.kt:55)
        at org.mozilla.fenix.perf.LazyMonitored$lazyValue$1.invoke(LazyMonitored.kt:36)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.mozilla.fenix.perf.LazyMonitored.getValue(LazyMonitored.kt:43)
        at org.mozilla.fenix.components.BackgroundServices.getAccountManager(Unknown Source:2)
        at org.mozilla.fenix.components.toolbar.BrowserToolbarView.<init>(BrowserToolbarView.kt:166)
        at org.mozilla.fenix.browser.BaseBrowserFragment.initializeUI$app_debug(BaseBrowserFragment.kt:350)
        at org.mozilla.fenix.browser.BrowserFragment.initializeUI$app_debug(BrowserFragment.kt:59)
        at org.mozilla.fenix.browser.BaseBrowserFragment.initializeUI(BaseBrowserFragment.kt:248)
        at org.mozilla.fenix.browser.BaseBrowserFragment.onViewCreated(BaseBrowserFragment.kt:227)

```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8334)

### PR DESCRIPTION
**Pull request by jonalmeida**
The `FxaPushSupportFeature` needs to generate, read and write a push
scope (identifier) to disk. This work was meant to be done lazily and
not during app startup. However, if a Sync account is setup then the IO
work is done immediately during the initial account manager
initialization at startup.

In this patch, we delegate this IO work to a new `PushScopeProperty`
that retrieves the value from disk using a provided `CoroutineScope`.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### GitHub Automation
Fixes #9829

### CODE REVIEW

**Comment by bendk** [comment]
I tried testing this on Fenix using the following changes:
```
diff --git a/app/src/debug/res/values/fenix_firebase.xml b/app/src/debug/res/values/fenix_firebase.xml
new file mode 100644
index 000000000..d6f3f4dcd
--- /dev/null
+++ b/app/src/debug/res/values/fenix_firebase.xml
@@ -0,0 +1,17 @@
[firebase keys content]
diff --git a/app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt b/app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt
index b32d28408..22cf21923 100644
--- a/app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt
+++ b/app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt
@@ -182,7 +182,8 @@ class BackgroundServices(
 
         // Enable push if it's configured.
         push.feature?.let { autoPushFeature ->
-            FxaPushSupportFeature(context, accountManager, autoPushFeature, crashReporter)
+            val feature = FxaPushSupportFeature(context, accountManager, autoPushFeature, crashReporter)
+            feature.initialize()
         }
 
         SendTabFeature(accountManager) { device, tabs ->

```

However, Fenix crashed and I saw the following exception in the log:

```
08-24 15:49:24.005 15627 15682 E ExceptionHandler: Uncaught exception handled: 
08-24 15:49:24.005 15627 15682 E ExceptionHandler: java.lang.IllegalStateException: Method addObserver must be called on the main thread
08-24 15:49:24.005 15627 15682 E ExceptionHandler: 	at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:317)
08-24 15:49:24.005 15627 15682 E ExceptionHandler: 	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:172)
08-24 15:49:24.005 15627 15682 E ExceptionHandler: 	at mozilla.components.support.base.observer.ObserverRegistry.register(ObserverRegistry.kt:72)
08-24 15:49:24.005 15627 15682 E ExceptionHandler: 	at mozilla.components.feature.push.AutoPushFeature.register(Unknown Source:12)
08-24 15:49:24.005 15627 15682 E ExceptionHandler: 	at mozilla.components.feature.accounts.push.FxaPushSupportFeature$initialize$1.invokeSuspend(FxaPushSupportFeature.kt:91)
08-24 15:49:24.005 15627 15682 E ExceptionHandler: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-24 15:49:24.005 15627 15682 E ExceptionHandler: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
08-24 15:49:24.005 15627 15682 E ExceptionHandler: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
08-24 15:49:24.005 15627 15682 E ExceptionHandler: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
08-24 15:49:24.005 15627 15682 E ExceptionHandler: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
08-24 15:49:24.005 15627 15682 E ExceptionHandler: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
08-24 15:49:24.005 15627 15682 E ExceptionHandler: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
08-24 15:49:24.005 15627 15682 E ExceptionHandler: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
08-24 15:49:24.005 15627 15682 E ExceptionHandler: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2f2dd09, Dispatchers.IO]

```

It looks like there's a threading issue to me, although I'm very over my head.  I can try to run some more tests if it would be helpful.

**Comment by jonalmeida** [comment]
@bendk thanks for testing, that was super helpful! I made the mistake of not updating my Fenix patch to use the new `initialize` call so I notice this earlier.

> It looks like there's a threading issue to me, although I'm very over my head. I can try to run some more tests if it would be helpful.
The fix here is to ensure that the account manager and push observers are added to those features _only_ on the Main thread. Since any feature that touches the account manager would end up initializing Fenix, we may end up adding these observers off the main thread and we've been getting pretty lucky so far.

This change made it very explicit that we run into this situation, so I've updated my patch to switch the main dispatcher when adding the above observers:
```kotlin
coroutineScope.launch(Main) {
    accountManager.register(accountObserver)

    pushFeature.register(autoPushObserver, owner, autoPause)
}
```

**Comment by bendk** [comment]
Just tested with the new changes and it worked great.  I don't think I'm qualified to review the patch in general, but it seems good to me.

File: components/feature/accounts-push/src/main/java/mozilla/components/feature/accounts/push/FxaPushSupportFeature.kt [hunk 1]
```diff
@@ -48,61 +49,49 @@ internal const val PREF_FXA_SCOPE = "fxa_push_scope"
...
-        prefs.getString(PREF_FXA_SCOPE, scope) as String
-    }
-
-    init {
-        val autoPushObserver = AutoPushObserver(accountManager, pushFeature, fxaPushScope)
+    /**
+     * Initialize the support feature to launch the appropriate observers.
+     */
+    fun initialize() = coroutineScope.launch {
+        val autoPushObserver = AutoPushObserver(accountManager, pushFeature, pushScope.value())
```
Comment (csadilek) [inline components/feature/accounts-push/src/main/java/mozilla/components/feature/accounts/push/FxaPushSupportFeature.kt:79]: nit: Let's assign `pushScope.value` to a `val` here? We're calling it twice right now, and it unconditionally generates a UUID and scope internally because you're using it as a default in `getString`.

**Review by csadilek — APPROVED** [review]
Just one nit below. I like that we now have an explicit `initialize` call and all this work doesn't happen as a side effect of the feature's constructor.
