### PR TITLE
Closes #7255 - Optionally submit errors as caught exceptions in RustLog

### LINKED ISSUE #7255: Submit errors observed via RustLog as Sentry 'info' reports
If we had this in place, we would have caught https://github.com/mozilla-mobile/android-components/issues/7233#issuecomment-639157815 much earlier.

### PR DESCRIPTION
**Pull request by grigoryk**
As it says on the lid!

---

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by grigoryk** [comment]
iOS does this, too: https://github.com/mozilla-mobile/firefox-ios/blob/fbc369e71110768c25ba71c7868d9e9bd2decad1/Providers/Profile.swift#L241-L258

File: components/support/rustlog/src/main/java/mozilla/components/support/rustlog/RustLog.kt [hunk 1]
```diff
@@ -29,10 +32,20 @@ object RustLog {
...
      */
-    fun enable() {
+    fun enable(crashReporter: CrashReporting? = null) {
         RustLogAdapter.enable { level, tagStr, msgStr ->
-            Log.log(levelToPriority(level), tagStr, null, msgStr)
+            val priority = levelToPriority(level)
+
+            crashReporter?.let {
+                if (priority == Log.Priority.ERROR) {
+                    it.submitCaughtException(RustErrorException(tagStr, msgStr))
```
Comment (pocmo) [inline components/support/rustlog/src/main/java/mozilla/components/support/rustlog/RustLog.kt:44]: @grigoryk Is it fair to assume those log messages won't contain any PII? I'll still approve and land since this won't do anything until we actually pass in a `CrashReporting` instance.
