### PR TITLE
Closes #5677: Catch all known non-fatal push errors

### LINKED ISSUE #5677: CryptoError: Error(
https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/7131337/

```
CryptoError: Error(

Crypto error: Error(

Crypto error: Decryption error))
    at mozilla.appservices.push.RustError.intoException(RustError.kt:14)
    at mozilla.appservices.push.PushManager.decrypt(PushManager.kt:16)
    at mozilla.components.feature.push.RustPushConnection.decrypt(Connection.kt:3)
    at mozilla.components.feature.push.AutoPushFeature$onMessageReceived$1.invokeSuspend(AutoPushFeature.kt:15)
    at mozilla.components.feature.push.AutoPushFeature$onMessageReceived$1.invoke
...
(6 additional frame(s) were not displayed)

Error(

Crypto error: Error(

Crypto error: Decryption error))
```

### PR DESCRIPTION
**Pull request by jonalmeida**
Previously, we wanted to throw on all unknown push errors so that we
were notified on them. Since this seems to be more common than
originally expected, we should just catch them and in a future version,
we should log them without crashing.

All of these push errors can be considered recoverable except
for InternalPanic.

---

Spoke offline with @jrconlin, and it's safe to not crash on these errors.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt [hunk 1]
```diff
@@ -359,7 +361,21 @@ internal fun CoroutineScope.launchAndTry(
...
+                is CommunicationError,
+                is CommunicationServerError,
+                is AlreadyRegisteredError,
+                is StorageError,
+                is MissingRegistrationTokenError,
+                is StorageSqlError,
+                is TranscodingError,
+                is RecordNotFoundError,
+                is UrlParseError -> false
+                else -> true
```
Comment (grigoryk) [inline components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt]: So, new exception types will throw? Not sure that's worth creating us extra work in the future (to keep this list up-to-date). Either way, these exceptions will end-up in Sentry - either as `info`s, or as `fatal`.

There's an idea in building robust software systems - be lenient with what you accept, and strict with what you send out. I think it applies here. We're handling an external message, subject to all sorts of unexpected issues outside of our control. If we crash here in response to a bad message, we're not gaining much! So, maybe our push stack got into a pickle and doesn't function correctly (either due to a server issue, or a client issue, or some network corruption, or..) - what do we gain by crashing here? The rest of the app is, most likely, perfectly functional. You'll just be getting in a user's way.

As long as we're aware of these problems, we can hopefully fix them - and that's what `submitCaughtException` already buys you. Submit these would-be crashes as `info`s, and let the app live :)

Comment (jonalmeida) [reply components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt]: From [the original discussion](https://github.com/mozilla-mobile/android-components/pull/4936#discussion_r341782953), we wanted to crash on newly added exceptions but we had to list them all out, so we opted for a whitelist instead. Now that we know that we don't need to crash on fatal errors, we're just catching and submitting them and we're at least aware of changes to the system this way.

Are you suggesting we don't crash at all? The exceptions that would go through here would be non-push specific (besides InternalPanic) since we're only logging them with `submitCaughtException`.

File: components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt [hunk 2]
```diff
@@ -184,15 +191,7 @@ class AutoPushFeature(
...
-        // Submit via our configured CrashReporter, as well.
-        when (error) {
-            is PushError.Rust -> {
-                crashReporter?.submitCaughtException(error.cause)
-            }
-            else -> {
-                crashReporter?.submitCaughtException(GenericPushError(error.desc))
-            }
-        }
+        crashReporter?.submitCaughtException(error)
```
[the remark this answers is not in the document]
Comment (jonalmeida) [reply components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt]: These questions were answered offline. I've overridden the `message` for extra certainty and for the RustError we override the `throwable` as well.

File: components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt (hunk 1 above)
Comment (grigoryk) [reply components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt]: Let's differentiate between error handling for `onMessageReceived` and for other types of exceptions (one way is to add `onMessageReceivedError` to AutoPushFeature in addition to `onError` - but see last paragraph).

And not crash at all (but rather, log and submit via crash reporter) in case of those types of errors. The other errors we can be more crashy with, I think.

Underlying idea is that it doesn't feel right to me to crash in case of a failure of a fairly isolated system due to an external event.

Also, you'll probably notice that there's currently a bit of a circle dance around error handling - e.g. AbstractFirebasePushService.onMessageReceived -> AutopushFeature.onMessageReceived -> throws -> AbstractFirebasePushService catches -> AutopushFeature.onError.

It seems like this could be simplified. e.g. AutopushFeature.onMessageReceived can just deal with exceptions directly, and if it throws, consumers should re-throw.

**Comment by jonalmeida** [comment]
> LGTM, our conversation about never throwing in `onMessageReceived` notwithstanding :) I'm fine with either direction, but would prefer to never see `fatal` crashes coming out of that method.

I've filed https://github.com/mozilla-mobile/android-components/issues/5691 as follow-up.

**Comment by jonalmeida** [comment]
bors r=grigoryk

**Comment by jonalmeida** [comment]
bors status
