### PR TITLE
Closes #9636: Narrow exception to ImageProcessingException

### LINKED ISSUE #9636: Narrow exception to ImageProcessingException
As agreed, GeckoView will throw `ImageProcessingException extends RuntimeException` when fails to process image.
https://bugzilla.mozilla.org/show_bug.cgi?id=1691072.  Update A-C when this is ready.

### PR DESCRIPTION
**Pull request by rocketsroger**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/mediasession/GeckoMediaSessionDelegate.kt [hunk 1]
```diff
@@ -43,8 +43,7 @@ internal class GeckoMediaSessionDelegate(
                     withTimeoutOrNull(ARTWORK_RETRIEVE_TIMEOUT) {
                         it.getBitmap(ARTWORK_IMAGE_SIZE).await()
                     }
-                } catch (e: RuntimeException) {
-                    // TODO https://bugzilla.mozilla.org/show_bug.cgi?id=1689745
+                } catch (e: ImageProcessingException) {
                     null
```
Comment (Amejia481) [inline components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/mediasession/GeckoMediaSessionDelegate.kt:47]: Should we add log statement ? :)

**Review by Amejia481 — APPROVED** [review]
👍🏽
