### PR TITLE
Fixes #3516 - Use response to determine file name

### LINKED ISSUE #3516: Downloaded images from Twitter or Google Images save with .bin format
Copied from: https://github.com/mozilla-mobile/fenix/issues/3624

Also see: https://github.com/mozilla-mobile/fenix/issues/2809

Same bug in Focus that a contributor tried to fix IIRC: 
https://github.com/mozilla-mobile/focus-android/issues/2743

---------------

## Steps to reproduce
1. Go to twitter.com
2. Long tap on an image and save image.

### Expected behavior
The image has a .jpg file format.

### Actual behavior
The image has a .bin file format. A saved image from Wikipedia articles is saved with .jpg file format.

### Device information
* Android device: ?
* Fenix version: 1.0.1926 (#11750611)

### Note
Bug filed from https://github.com/webcompat/web-bugs/issues/33424

### PR DESCRIPTION
**Pull request by NotWoods**
Changes `Download` so that the filename is determined when the download begins rather than when the request is made. 

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.

### CODE REVIEW

File: components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt [hunk 1]
```diff
@@ -506,13 +505,11 @@ class GeckoEngineSession(
...
         override fun onExternalResponse(session: GeckoSession, response: GeckoSession.WebResponseInfo) {
             notifyObservers {
-                val fileName = response.filename
-                    ?: DownloadUtils.guessFileName("", response.uri, response.contentType)
                 onExternalResource(
                         url = response.uri,
                         contentLength = response.contentLength,
                         contentType = response.contentType,
-                        fileName = fileName)
+                        fileName = response.filename)
```
Comment (Amejia481) [inline components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt]: Before starting the download, we use the `filename` to show a dialog to [confirm if the user wants to start the download or not](https://github.com/mozilla-mobile/android-components/blob/c6e58ae709f4f3f3284565b317529e9ac390c2f2/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt#L94). Could this change affect the name displayed to the user? As we used `DownloadUtils.guessFileName` for edge case where the `filename` wasn't provided.

Screenshot_20190719-094716

Comment (NotWoods) [reply components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt]: Unfortunately the name doesn't match in that case. However, we only don't have the filename for image downloads and the popup will eventually be removed (#2325)

Comment (Amejia481) [reply components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt]: 👍

File: docs/changelog.md [hunk 2]
```diff
@@ -17,12 +17,15 @@ permalink: /changelog/
 * **browser-icons**
   * Added `BrowserIcons.loadIntoView` to automatically load an icon into an `ImageView`.
 
+* **feature-downloads**
+  * Download filenames are now more accurate when `FetchDownloadManager` is used.
```
Comment (Amejia481) [inline docs/changelog.md]: nit: Could we add a bit more info for consumer to know why Download filenames are now more accurate? :)

**Comment by NotWoods** [comment]
TC issues should now be fixed 😄
