### PR TITLE
Closes #6372: Ignore JobCancellationException for add-on workers

### LINKED ISSUE #6372: Ignore JobCancellationException for add-on workers
`JobCancellationException` is one of the top reported [exceptions in sentry](https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/7512699/?query=is:unresolved), this happens when a worker takes a long time to process a request. In our case, this is not very meaningful neither actionable from our side.

```
mozilla.components.feature.addons.AddonManagerException: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@a8dcedd
    at mozilla.components.feature.addons.AddonManager.getAddons(AddonManager.kt:58)
    at mozilla.components.feature.addons.AddonManager$getAddons$1.invokeSuspend
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:14)
```

### PR DESCRIPTION
**Pull request by Amejia481**
---

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/worker/Extensions.kt [hunk 1]
```diff
@@ -0,0 +1,12 @@
...
+ * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
+
+package mozilla.components.feature.addons.worker
+
+import java.io.IOException
+import kotlinx.coroutines.CancellationException
+/**
+ * Indicates if an exception should be reported to the crash reporter.
+ */
+internal fun Exception.shouldReport(): Boolean = cause is IOException || this is CancellationException
```
Comment (Amejia481) [inline components/feature/addons/src/main/java/mozilla/components/feature/addons/worker/Extensions.kt]: [ JobCancellationException is an internal class](https://github.com/Kotlin/kotlinx.coroutines/blob/3bb3e55a53359ebe268c7def40c6b016ca0e5f9a/kotlinx-coroutines-core/jvm/src/Exceptions.kt#L29) for this reason we have to use it parent class `CancellationException`

File: components/feature/addons/src/test/java/mozilla/components/feature/addons/worker/ExtensionsTest.kt [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+import junit.framework.TestCase.assertTrue
+import java.io.IOException
+import kotlinx.coroutines.CancellationException
+import org.junit.Test
+import org.junit.runner.RunWith
+
+/**
+ * Indicates if an exception should be reported to the crash service.
+ */
+internal fun Exception.shouldReport(): Boolean = cause is IOException || this is CancellationException
```
Comment (csadilek) [inline components/feature/addons/src/test/java/mozilla/components/feature/addons/worker/ExtensionsTest.kt]: I assume you meant to import this function? Otherwise you're testing the test code :).

Comment (Amejia481) [reply components/feature/addons/src/test/java/mozilla/components/feature/addons/worker/ExtensionsTest.kt]: 🤦‍♂  it is there by mistake

Comment (Amejia481) [reply components/feature/addons/src/test/java/mozilla/components/feature/addons/worker/ExtensionsTest.kt]: I updated the pr 👍

**Comment by Amejia481** [comment]
bors r=csadilek
