### PR TITLE
Closes #8967 prevent handling invalid requests in FilePicker

### LINKED ISSUE #8967: FilePicker should only process PromptRequest.File
As we can see in this stack trace provided in https://github.com/mozilla-mobile/fenix/issues/16537, `FilePicker` is trying to process a `PromptRequest` that doesn't belong to it, not sure how we entered in that state, but it looks like a race condition were a  `PromptRequest.File` was requested but before it was proceeded an `PromptRequest$Alert` replaced it. We have to prevent processing invalid request in `FilePicker`

```
java.lang.ClassCastException: mozilla.components.concept.engine.prompt.PromptRequest$Alert cannot be cast to mozilla.components.concept.engine.prompt.PromptRequest$File
    at mozilla.components.feature.prompts.file.FilePicker$onActivityResult$1.invoke(FilePicker.kt:3)
    at androidx.core.app.AppOpsManagerCompat.consumePromptFrom(AppOpsManagerCompat.java:5)
    at androidx.core.app.AppOpsManagerCompat.consumePromptFrom$default(AppOpsManagerCompat.java:1)
    at mozilla.components.feature.prompts.file.FilePicker.onActivityResult(FilePicker.kt:1)
    at mozilla.components.feature.prompts.PromptFeature.onActivityResult(PromptFeature.kt:1)
    at org.mozilla.fenix.browser.BaseBrowserFragment$onActivityResult$1.invoke(BaseBrowserFragment.kt:3)
    at mozilla.components.support.base.feature.ViewBoundFeatureWrapper.withFeature(ViewBoundFeatureWrapper.kt:1)
    at org.mozilla.fenix.browser.BaseBrowserFragment.onActivityResult(BaseBrowserFragment.kt:1)
    at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:7)
    at android.app.Activity.dispatchActivityResult(Activity.java:7454)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:4384)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:4433)
    at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1836)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6702)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=203721, result=-1, data=null} to activity {org.mozilla.fenix/org.mozilla.fenix.App}: java.lang.ClassCastException: mozilla.components.concept.engine.prompt.PromptRequest$Alert cannot be cast to mozilla.components.concept.engine.prompt.PromptRequest$File
    at android.app.ActivityThread.deliverResults(ActivityThread.java:4391)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:4433)
    at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1836)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6702)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
```

### PR DESCRIPTION
**Pull request by Amejia481**
Details in https://github.com/mozilla-mobile/android-components/issues/8967 
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/feature/prompts/src/main/java/mozilla/components/feature/prompts/file/FilePicker.kt [hunk 1]
```diff
@@ -107,19 +111,24 @@ internal class FilePicker(
...
-
                 if (resultCode == RESULT_OK) {
                     handleFilePickerIntentResult(intent, request)
                 } else {
                     request.onDismiss()
                 }
             }
         }
+        if (request !is File) {
+            logger.debug("Invalid PromptRequest expected File but $request was provided")
```
Comment (csadilek) [inline components/feature/prompts/src/main/java/mozilla/components/feature/prompts/file/FilePicker.kt:125]: Let's log this as at least `warn` or even `error`. Since we don't know how we end up in this state and really shouldn't...

File: components/feature/prompts/src/main/java/mozilla/components/feature/prompts/file/FilePicker.kt [hunk 2]
```diff
@@ -107,19 +111,24 @@ internal class FilePicker(
      * @param intent The result of the request.
      */
     fun onActivityResult(requestCode: Int, resultCode: Int, intent: Intent?) {
-        if (requestCode == FILE_PICKER_ACTIVITY_REQUEST_CODE) {
+        val request = getActivePromptRequest() ?: return
+        if (requestCode == FILE_PICKER_ACTIVITY_REQUEST_CODE && request is File) {
             store.consumePromptFrom(sessionId) {
```
Comment (csadilek) [inline components/feature/prompts/src/main/java/mozilla/components/feature/prompts/file/FilePicker.kt:116]: So looking at this flow, what could happen here (and be the cause of the problem) is that the selected session changed and we're now processing a prompt request from a different session. It's one possibility. I think, ideally, we should make this impossible by creating a `FilePicker` instance for the specific session/prompt request (and store the sessionId of the selected session or custom tab), instead of using a "global" file picker instance which looks up the prompt request for the selected session which could have changed...

Comment (Amejia481) [reply components/feature/prompts/src/main/java/mozilla/components/feature/prompts/file/FilePicker.kt:116]: Yes that could be the issue, we request the OS to show the file picker but it took a lot of time, the user select a new session, and this session has another dialog, and then the file picker appears, the user select the file and we end up trying to consume a different prompt request.

It's a bit tricky to store the `sessionId` in the in the file picker dialog, because we don't own it, we request the OS to provide us an app that can handle the file picker functionality ([here](https://github.com/mozilla-mobile/android-components/blob/0c856f9584cadd3d57081b5c0304595a4974291c/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/file/FilePicker.kt#L74) and [here](https://github.com/mozilla-mobile/android-components/blob/0c856f9584cadd3d57081b5c0304595a4974291c/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/file/FilePicker.kt#L100)), via an intent, but there is not an additional information that we can use to identify the session when the OS replies back to `onActivityResult`, some information that is replied back from [startActivityForResult](https://developer.android.com/reference/android/app/Activity#startActivityForResult(android.content.Intent,%20int)) to [onActivityResult](https://developer.android.com/reference/android/app/Activity#onActivityResult(int,%20int,%20android.content.Intent)) is the `requestCode` we could use the `sessionId` instead of the [FILE_PICKER_ACTIVITY_REQUEST_CODE](https://github.com/mozilla-mobile/android-components/blob/0c856f9584cadd3d57081b5c0304595a4974291c/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/file/FilePicker.kt#L100).

Comment (csadilek) [reply components/feature/prompts/src/main/java/mozilla/components/feature/prompts/file/FilePicker.kt:116]: @Amejia481 

> It's a bit tricky to store the sessionId in the in the file picker dialog

Ah no, I meant storing it as a field in `FilePicker` similar to how it stores the `customTabSessionId`: https://github.com/mozilla-mobile/android-components/blob/master/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt#L218.

Comment (Amejia481) [reply components/feature/prompts/src/main/java/mozilla/components/feature/prompts/file/FilePicker.kt:116]: Got it, I will take a look!

**Comment by Amejia481** [comment]
This is not a fix, it will prevent the crash, but some functionality could be broken for some pages, @csadilek and me were chatting about doing a follow up to do a permanent solution, I opened https://github.com/mozilla-mobile/android-components/issues/8989 to continue the work.

**Review by csadilek — APPROVED** [review]
