### PR TITLE
Closes #8653: Send structured java stack trace in crash reports to Socorro

### LINKED ISSUE #8653: send structured java stack trace in crash reports to Socorro
Currently, the crash reporter sends a `JavaStackTrace` crash annotation to Socorro which is a single string containing the exception and traceback. I'm pretty sure the structure of that string has changed over the years, I don't have a good parser for it, and it's really hard to extract useful data from it to have parity with C/C++/Rust crashes on Crash Stats.

It'd be great to have a structured form for Java stack traces.

The Sentry Java client sends exception information in a structured form:

* format: https://develop.sentry.dev/sdk/event-payloads/exception/
* stack trace format: https://develop.sentry.dev/sdk/event-payloads/stacktrace/
* notes on variable sizes: https://develop.sentry.dev/sdk/data-handling/#variable-size

Maybe we can re-use that format as a JSON-encoded crash annotation value?

If we add a new crash annotation with a JSON-encoded structure, then we could do things like display the stack better (links to source files?), generate better crash signatures ([bug 1541120](https://bugzilla.mozilla.org/show_bug.cgi?id=1541120)), support Android mappings and retracing ([bug 1642655](https://bugzilla.mozilla.org/show_bug.cgi?id=1642655)), and possibly other things.

### PR DESCRIPTION
**Pull request by rocketsroger**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by rocketsroger** [comment]
Example crash report https://crash-stats.mozilla.org/report/index/04d0e260-180d-41e0-a389-429920201015#tab-metadata

File: buildSrc/src/main/java/Dependencies.kt [hunk 1]
```diff
@@ -82,6 +83,7 @@ object Dependencies {
     const val testing_coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-test:${Versions.coroutines}"
     const val testing_maven_ant_tasks = "org.apache.maven:maven-ant-tasks:${Versions.maven_ant_tasks}"
     const val testing_leakcanary = "com.squareup.leakcanary:leakcanary-android-instrumentation:${Versions.leakcanary}"
+    const val testing_json = "org.json:json:${Versions.json}"
```
Comment (pocmo) [inline buildSrc/src/main/java/Dependencies.kt:86]: Instead of importing this you may want to run the test with the `AndroidJUnit4` runner, which will make this and other APIs available.

Comment (rocketsroger) [reply buildSrc/src/main/java/Dependencies.kt:86]: Ah, that's what I've missed.  Thanks I'll update.

**Review by pocmo — APPROVED** [review]
