### PR TITLE
Closes #5407: If intent have packet name then always send to marketplace if package is not installed

### LINKED ISSUE #5407: Market app not open when an app is not installed for a particular link
The BiP Messenger link is not working correctly.  To reproduce, click on the BiP button in the page:
http://www.milliyet.com.tr/galeri/son-dakika-korkutan-goruntuler-gelmeye-devam-ediyor-once-yukseldi-sonra-ise-6108205/1

This works on both Chrome and Fennec

### PR DESCRIPTION
**Pull request by rocketsroger**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinkRedirectTest.kt [hunk 1]
```diff
@@ -74,5 +74,6 @@ class AppLinkRedirectTest {
         var appLink = AppLinkRedirect(appIntent = null, fallbackUrl = null, marketplaceIntent = mock())
         assertTrue(appLink.hasMarketplaceIntent())
         assertTrue(appLink.isRedirect())
+        assertTrue(appLink.hasMarketplaceIntent())
     }
 }
```
Comment (psymoon) [inline components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinkRedirectTest.kt]: nit: `\n`? Not sure how lint check didn't call this out :)

Comment (rocketsroger) [reply components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinkRedirectTest.kt]: Thanks for catching this.  I'll add the `\n`

**Comment by rocketsroger** [comment]
bors r=psymoon
