### PR TITLE
Closes #6627: Add default local property to Addon

### LINKED ISSUE #6627: Add default locale to unsupported addons
When we create a unsupported add-on, we are adding the current local, but we are not adding a fallback and when users switch languages we are crashing because we don't have a fallback locale see https://github.com/mozilla-mobile/android-components/issues/6496

https://github.com/mozilla-mobile/android-components/blob/d433836f0bce2793165ed60c2712a9af5f3b5b64/components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt#L86

### PR DESCRIPTION
**Pull request by Amejia481**
Fenix pr https://github.com/mozilla-mobile/fenix/pull/9886, RB pr https://github.com/mozilla-mobile/reference-browser/pull/1119

---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt [hunk 1]
```diff
@@ -47,7 +48,8 @@ data class Addon(
     val rating: Rating? = null,
     val createdAt: String = "",
     val updatedAt: String = "",
-    val installedState: InstalledState? = null
+    val installedState: InstalledState? = null,
+    val defaultLocal: String = DEFAULT_LOCALE
```
Comment (csadilek) [inline components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt:52]: nit: `defaultLocale`

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt [hunk 2]
```diff
@@ -30,6 +30,7 @@ import kotlinx.android.parcel.Parcelize
  * @property updatedAt The date of the last time the add-on was updated by its developer(s).
  * @property installedState Holds the state of the installed web extension for this add-on. Null, if
  * the [Addon] is not installed.
+ * @property defaultLocal Indicates which local will be always available to display translatable fields.
```
Comment (csadilek) [inline components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt:33]: nit: defaultLocale...indicates which locale will...

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt [hunk 3]
```diff
@@ -185,5 +188,10 @@ data class Addon(
         fun localizePermissions(permissions: List<String>): List<Int> {
             return permissions.mapNotNull { permissionToTranslation[it] }
         }
+
+        /**
+         * The default fallback local in case the [Addon] do not have its own [Addon.defaultLocal].
```
Comment (csadilek) [inline components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt:193]: nit: locale...in case the [Addon] does not have its own...

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/Extensions.kt [hunk 4]
```diff
@@ -19,14 +19,24 @@ import java.util.Locale
...
+
+/**
+ * A shortcut to get the localized description of an add-on.
+ */
+val Addon.translatedDescription: String get() = translatableDescription.translate(this)
+
+/**
+ * Try to find the default language on the map otherwise defaults to [Addon.DEFAULT_LOCALE].
+ */
+fun Map<String, String>.translate(addon: Addon): String {
```
Comment (csadilek) [inline components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/Extensions.kt:37]: Ah and let's make this one internal, if it's no longer needed :).

Comment (Amejia481) [reply components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/Extensions.kt:37]: 👍

**Comment by Amejia481** [comment]
bors r=csadilek
