### PR TITLE
Close #5866: Pass Uri to handleNewWindowRequestError when failed to open a new window request in custom tab

### LINKED ISSUE #5866: ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW cat=[mozilla.components.pwa.c...
https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/7183008/

```
ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW cat=[mozilla.components.pwa.category.SHORTCUT] dat= pkg=org.mozilla.fennec_aurora (has extras) }
    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2014)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1675)
    at android.app.Activity.startActivityForResult(Activity.java:4586)
    at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:6)
    at android.app.Activity.startActivityForResult(Activity.java:4544)
...
(17 additional frame(s) were not displayed)

No Activity found to handle Intent { act=android.intent.action.VIEW cat=[mozilla.components.pwa.category.SHORTCUT] dat= pkg=org.mozilla.fennec_aurora (has extras) }
```

### PR DESCRIPTION
**Pull request by rocketsroger**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabWindowFeature.kt [hunk 1]
```diff
@@ -32,7 +33,7 @@ class CustomTabWindowFeature(
     private val activity: Activity,
     private val store: BrowserStore,
     private val sessionId: String,
-    @VisibleForTesting internal val handleError: (Exception) -> Unit
+    @VisibleForTesting internal val handleNewWindowRequestError: (Uri) -> Unit
```
Comment (csadilek) [inline components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabWindowFeature.kt:36]: nit: Not super convinced about the name. Maybe `onFailedWindowRequest`? Both are not ideal though, as it's not the window request failing. We just failed to launch an intent for the URL and want to try something else. Maybe `onLaunchUrlFallback`?

Comment (rocketsroger) [reply components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabWindowFeature.kt:36]: Sure, I'll rename to onLaunchUrlFallback.

**Comment by rocketsroger** [comment]
bors r=csadilek
