### PR TITLE
Closes #5042: Save state of migration immediately after every migration run.

### LINKED ISSUE #5042: Fennec migration: Open tabs are duplicated
## Preconditions:
Have Firefox Release installed, logged in and 2-3 opened tabs.
## Steps to reproduce
1. Replace Fennec with Fenix using a build from https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration;
2. Launch Fenix;
3. Tap on Start browsing;
4. Observe the open tabs.
### Expected behavior
The opened tabs are displayed.
### Actual behavior
The opened tabs are duplicated. The visited pages are also duplicated in history.
### Notes:
The number of duplicated tabs is related with the numbers of time the app crashes (bug https://github.com/mozilla-mobile/android-components/issues/5041).
Screenshot_20191113-103153
### Device information

* Android device: Google Pixel 2 (Android 9) - ARM64, ARM.
* Fenix version: Nightly 191109 GV 71

### PR DESCRIPTION
**Pull request by pocmo**
Closes #5042.

### CODE REVIEW

File: components/support/migration/src/main/java/mozilla/components/support/migration/FennecMigrator.kt [hunk 1]
```diff
@@ -462,10 +463,14 @@ class FennecMigrator private constructor(
                     MigrationRun(versionedMigration.version, true)
                 }
             }
+
+            // Save result of this migration immediately, so that we keep it even if we crash later
+            // in the process and do not rerun this migration version.
+            migrationStore.setOrUpdate(mapOf(versionedMigration.migration to migrationRun))
```
Comment (grigoryk) [inline components/support/migration/src/main/java/mozilla/components/support/migration/FennecMigrator.kt]: Double checked, and `migrationStore` will do the right thing here - it'll augment what's currently cached, and not just overwrite existing values.

Comment (pocmo) [reply components/support/migration/src/main/java/mozilla/components/support/migration/FennecMigrator.kt]: Yeah, checked and tested that too.. :)
