### PR TITLE
On memory pressure close engine sessions and keep state for restoring later.

### LINKED ISSUE #5933: SessionManager never closes opened sessions, leading to OOMs
See [Fenix #4151](https://github.com/mozilla-mobile/fenix/issues/4151)
See attempted fix PR https://github.com/mozilla-mobile/android-components/pull/5919 (with [several problems](https://github.com/mozilla-mobile/android-components/pull/5919#pullrequestreview-358056532))

Any `EngineSession`s that are actively opened (I _**believe**_ the only way to 'open' an `EngineSession` is to select and load its tab during the current user session) will never be closed.  If too many are opened (on my device ~20) this will cause an OOM crash.  I haven't measured, but presumably there is a perf impact before that point is reached.

It's on GVs roadmap to handle this memory pressure intelligently, but it hasn't been prioritized.  For now, they recommend that we open/close `EngineSession`s ourselves.
[Riot conversation](https://matrix.to/#/!kgzqJPKsBZFakDVGxV:mozilla.org/$FRkgsypkk5TWgICW28a25EIAacze0uBUyDI_e_zdmrw?via=mozilla.org&via=matrix.org)
[BZ1](https://bugzilla.mozilla.org/show_bug.cgi?id=1587853)
[BZ2](https://bugzilla.mozilla.org/show_bug.cgi?id=1454752)

A very basic solution here could be:
- `SessionManager#onLowMemory` closes all `EngineSession`s except for the currently selected one.
- When a new tab is selected, more than MAX_SESSIONS are open, close the LRU `EngineSession`

### PR DESCRIPTION
**Pull request by pocmo**
Unfortunately the implementation for this needs to live in SessionManager as long as it keeps
references to EngineSession instances and thumbnails. Therefore we determine what to trim in
SessionManager and notify BrowserStore to perform the same changes.

Hopefully in a not to distant future we can move that to BrowserStore.

Closes #5933.

---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [x] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [x] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt [hunk 1]
```diff
@@ -62,17 +67,22 @@ class SessionManager(
...
+                engineSession.unregister(observer)
             }
 
+            session.engineSessionHolder.engineSession = null
+            session.engineSessionHolder.engineObserver = null
+            session.engineSessionHolder.engineSessionState = null
+
             store?.syncDispatch(UnlinkEngineSessionAction(session.id))
+
+            // Closing the engine session after updating the store so that neither session manager
```
Comment (csadilek) [inline components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt]: nit: I misread this comment a few times: Should this be "Closing the engine session after updating *now* that neither the session manager nor the store keep a reference anymore."?

File: components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt [hunk 2]
```diff
@@ -318,9 +328,55 @@ class SessionManager(
...
+                        it.engineSessionHolder.engineSessionState = state
+                        states[it.id] = state
+                    }
+
+                    unlinkedEngineSessions++
+                }
+            }
+        }
+
+        logger.debug("Cleared $clearThumbnails thumbnail(s) and unlinked $unlinkedEngineSessions engine sessions()")
```
Comment (csadilek) [inline components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt]: This should be $clearedThumbnails (not the $clearThumbnails boolean).

Comment (csadilek) [inline components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt]: Also nit: don't need to end sentence in `()` :)

File: components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt [hunk 3]
```diff
@@ -318,9 +328,55 @@ class SessionManager(
...
+                }
+
+                if (closeEngineSessions) {
+                    val state = it.engineSessionHolder.engineSession?.saveState()
+                    linker.unlink(it)
+
+                    if (state != null) {
+                        it.engineSessionHolder.engineSessionState = state
+                        states[it.id] = state
+                    }
```
Comment (csadilek) [inline components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt]: We're doing this on `TRIM_MEMORY_RUNNING_CRITICAL,` but presumably `saveState` is also requiring some memory. Just wondering if we might fail to do this because there's not enough memory left in which case `TRIM_MEMORY_RUNNING_LOW` would be better for clearing engine sessions as well? 🤔 Of course, that would happen more often then. Just a thought. +1 for landing as is.

File: components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt (hunk 2 above)
Comment (pocmo) [reply components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt]: @jonalmeida doesn't like me to end my sentences with `.` - now you are telling me `()` is also not an option?? :)

Comment (pocmo) [reply components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt]: (That should have been `session(s)` - plurals, yay!)

Comment (jonalmeida) [reply components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt]: Only commit messages! 😅

File: components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt (hunk 3 above)
Comment (pocmo) [reply components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt]: You are right in theory, but: The implementation of `saveState` has changed in the past. Nowadays `GeckoEngineSession` always has a reference to the last state (since GV pushes it to us) and `saveState()` only returns that reference :)

File: components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt (hunk 2 above)
Comment (csadilek) [reply components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt]: 😆

**Comment by pocmo** [comment]
Updated!

bors r=csadilek
