### PR TITLE
Closes #4298 Add Timestamp Support in lib-crash BreadCrumbs

### LINKED ISSUE #4298: lib-crash BreadCrumbs Should Preserve Timestamp
Currently lib-crash bread crumb implementation will record all bread crumbs right before submitting the crash.  The reason is Sentry context can be lost on Android Q or above when notification is used to report crashes.  lib-crash should try to preserve the bread crumbs timestamp if possible.

### PR DESCRIPTION
**Pull request by rocketsroger**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SentryService.kt [hunk 1]
```diff
@@ -35,21 +35,21 @@ class SentryService(
...
-        addTag("ac.version", Build.version)
-        addTag("ac.git", Build.gitHash)
-        addTag("ac.as.build_version", Build.applicationServicesVersion)
-    }
+            // Add default tags
+            addTag("ac.version", Build.version)
+            addTag("ac.git", Build.gitHash)
+            addTag("ac.as.build_version", Build.applicationServicesVersion)
+        }
     }
```
Comment (pocmo) [inline components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SentryService.kt]: nit: This indentation change seems to be unrelated?

Comment (rocketsroger) [reply components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SentryService.kt]: Yes, unrelated.  I just wanted to fix it for readability.  Thanks,

**Comment by rocketsroger** [comment]
bors r=pocmo
