### PR TITLE
Closes #314: Automate Nightly GeckoView dependency update

### LINKED ISSUE #314: Automate Nightly GeckoView dependency update
Background:
* We want to track the latest Nightly version of GeckoView as much as possible
* We do not want to use version wildcards because then builds break randomly when the GV APIs change. We still want to pin a specific version that is known to work.

Could we write a script that:
* Determines the latest nightly version from taskclusters index service.
* Updates the build.gradle file (or another to-be-created file where we define the versions)
* Builds the components to see if everything still works
* If build successful: Opens a PR with the changes
* If build fails: Opens an issue linking to the failure so that we can update (and fix) manually

### PR DESCRIPTION
**Pull request by Amejia481**
There're two plugins:

## 1.GVNightlyVersionVerifierPlugin
Updates to the last version of gecko view nightly.

#### Parameters:

**gvVersionFile** [_optional_] 
  _default_ ["buildSrc/src/main/java/Gecko.kt"](#)
The file where it will update the version of GV version.

**gvMavenVersionURL** [_optional_] 
_default_ "https://maven.mozilla.org/maven2"
The repository where is fetching the last version of GV

#### Example:
` ./gradlew updateGVNightlyVersion`

#### Parameters:

**title** [_required_] 
Title of the PR

**body** [_optional_] 
_default_ [""](#)
The text that goes in the body of the PR

**branch** [required] 
The branch that you want to merge e.g your _feature branch_

**baseBranch**[_optional_] 
_default_ ["master"](#)
The branch with you want to merge with e.g _master_

**owner**[_optional_] 
_default_ ["mozilla-mobile"](#)
The repo where you want to open the PR

**repo**[_optional_] 
_default_ ["android-components"](#)
The repo where you want to open the PR

**botUser**[_optional_] 
_default_ ["MickeyMoz"](#)

**tokenFile**[_optional_] 
_default_ [".github_token"](#)
The file where the token must be. The content of the file should be `toke=<token>`

#### Example:
` ./gradlew openPR -Ptitle="GV Nightly version Updated" -Pbranch="newBranchName"`

#### Parameters:

**title** [_required_] 
Title of the issue

**body** [_optional_] 
_default_ [""](#)
The text that goes in the body of the issue

**owner**[_optional_] 
_default_ ["mozilla-mobile"](#)
The repo where you want to open the issue

**repo**[_optional_] 
_default_ ["android-components"](#)
The repo where you want to open the issue

#### Example:
`./gradlew openIssue -Ptitle="New GV Nightly version Failing" -Pbody="New Version of GV is failing running tests"`

The final command should look like:
`./gradlew updateGVNightlyVersion && ./gradlew clean assemble test && git checkout -B newBranchName && git add buildSrc/src/main/java/Gecko.kt && git commit -m "Updating Gecko View Nightly Version" && git push -u -f origin newBranchName && ./gradlew openPR -Ptitle="GV Nightly version Updated" -Pbranch="newBranchName"`

### CODE REVIEW

File: buildSrc/src/main/java/GVNightlyVersionVerifier.kt [hunk 1]
```diff
@@ -0,0 +1,210 @@
...
+        fileContent = fileContent.replace(Regex("nightly_version.*=.*"),
+                "nightly_version = \"$newVersion\"")
+        file.writeText(fileContent)
+        println("${file.name} file updated")
+    }
+
+    private fun runTests(): Boolean {
+        println("Running tests")
+
+        val result = "./gradlew clean test".runCommand()
```
Comment (pocmo) [inline buildSrc/src/main/java/GVNightlyVersionVerifier.kt]: It feels a bit weird to run the gradle command from inside a gradle plugin.

I wonder if we could split this into separate tasks:
* update geckoview dependency (just does the update of the file)
* open the PR

The advantage would be:
* I can run the update script locally without opening the PR etc.
* In automation we can run: 
  ```bash
       ./gradlew ....updateGeckoView...    (needs to fail if it couldn't update)
       && ./gradlew clean assemble test 
       && ./gradlew ....openPR...
   ```
* We can use the "open pr" task for other things in the future :)

File: buildSrc/src/main/java/GVNightlyVersionVerifier.kt [hunk 2]
```diff
@@ -0,0 +1,210 @@
...
+        System.setProperty("Drevision", "release")
+    }
+
+    private fun updateConfigFileWithNewGVNightlyVersion(newVersion: String) {
+        val file = File(GV_VERSION_PATH_FILE)
+        var fileContent = file.readText()
+        fileContent = fileContent.replace(Regex("nightly_version.*=.*"),
+                "nightly_version = \"$newVersion\"")
+        file.writeText(fileContent)
+        println("${file.name} file updated")
```
Comment (pocmo) [inline buildSrc/src/main/java/GVNightlyVersionVerifier.kt]: In a future version it would be nice if this task can write a complete Gecko dependency file. We may end up using this plugin in app projects too and for that it would be nice if this just generates the code file (maybe with [kotlinpoet](https://github.com/square/kotlinpoet)?). Can you file this as follow-up?

Comment (Amejia481) [reply buildSrc/src/main/java/GVNightlyVersionVerifier.kt]: Sure 👍 , I took a look at kotlinpoet, and I took this approach because the only thing that was channing in the file was the **const nightly_version**

File: buildSrc/src/main/java/GVNightlyVersionVerifier.kt (hunk 1 above)
Comment (Amejia481) [reply buildSrc/src/main/java/GVNightlyVersionVerifier.kt]: Yes, It felt like the inception movie :P
Nice :)

**Comment by Amejia481** [comment]
What I about if I read it from `"buildSrc/local.properties"`?
Or do you have any specify path in mind?

**Comment by pocmo** [comment]
> What I about if I read it from "buildSrc/local.properties"?
> Or do you have any specify path in mind?

Just invent a file in the root directory (e.g. `.github_token`). It will be easy to grab the token from taskclusters secret service and write it to that file. :)

File: buildSrc/src/main/java/GVNightlyVersionVerifier.kt (hunk 1 above)
Comment (Amejia481) [reply buildSrc/src/main/java/GVNightlyVersionVerifier.kt]: Done :) !

Now there are two plugins, one for just updating the GV version and other for opening pull requests and issues, I updated the PR description with more info.

`./gradlew updateGVNightlyVersion && ./gradlew clean assemble test && git checkout -B newBranchName && git add buildSrc/src/main/java/Gecko.kt && git commit -m "Updating Gecko View Nightly Version" && git push -u -f origin newBranchName && ./gradlew openPR -Ptitle="GV Nightly version Updated" -Pbranch="newBranchName"`

**Comment by pocmo** [comment]
Awesome work, @Amejia481! I'll try to play with the plugins locally today :)

File: buildSrc/src/main/java/Extentions.kt [hunk 3]
```diff
@@ -0,0 +1,5 @@
+import org.gradle.api.Project
```
Comment (pocmo) [inline buildSrc/src/main/java/Extentions.kt]: nit: license header

Comment (Amejia481) [reply buildSrc/src/main/java/Extentions.kt]: Done!
