### PR TITLE
Closes #9109 update tracking protection status when removing an exception by url.

### LINKED ISSUE #9109: Update tracking protection status when removing exception by url
When we are removing a tracking protection exception using [an url](https://github.com/mozilla-mobile/android-components/blob/80bf71b971c204c66f6173c23e4ca7d96ced65dd/components/feature/session/src/main/java/mozilla/components/feature/session/TrackingProtectionUseCases.kt#L73), we have to find the tabs that have the same domain and update their tracking protection status, tracking protection works per domain, right now we are not updating the status for those tabs causing this issue https://github.com/mozilla-mobile/fenix/issues/16670

image

### PR DESCRIPTION
**Pull request by Amejia481**
When we are removing a tracking protection exception using [an url](https://github.com/mozilla-mobile/android-components/blob/80bf71b971c204c66f6173c23e4ca7d96ced65dd/components/feature/session/src/main/java/mozilla/components/feature/session/TrackingProtectionUseCases.kt#L73), we have to find the tabs that have the same domain and update their tracking protection status, (tracking protection works per domain). Right now we are not updating the status for those tabs causing this issue https://github.com/mozilla-mobile/fenix/issues/16670

image

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/feature/session/src/main/java/mozilla/components/feature/session/TrackingProtectionUseCases.kt [hunk 1]
```diff
@@ -71,6 +73,15 @@ class TrackingProtectionUseCases(
          */
         operator fun invoke(exception: TrackingProtectionException) {
             engine.trackingProtectionExceptionStore.remove(exception)
+            // Find all tabs that need to update their tracking protection status.
+            val tabs = store.state.tabs.filter { tab ->
```
Comment (pocmo) [inline components/feature/session/src/main/java/mozilla/components/feature/session/TrackingProtectionUseCases.kt:77]: Would we need to do that for `store.state.customTabs` too?

Comment (Amejia481) [reply components/feature/session/src/main/java/mozilla/components/feature/session/TrackingProtectionUseCases.kt:77]: Thanks for catching it, I thought we have them all mix in tabs. I will update the pr. 👍🏽

Comment (Amejia481) [reply components/feature/session/src/main/java/mozilla/components/feature/session/TrackingProtectionUseCases.kt]: PR update :)

**Review by pocmo — APPROVED** [review]
