### PR TITLE
Closes #9183, #9199: Move SessionStorage from browser-session to browser-session-storage.

### LINKED ISSUE #8600: Introduce RestoreUseCase to restore state/tabs
It would be nice if we had re-usable code to restore tabs and deal with the context switches, so that applications just need to observe that tabs are ready to be used via the store.

We have a block of code for this in both Fenix and R-B, which could be simplified.

### LINKED ISSUE #9183: Move session storage related code out of browser-session
We are close to getting rid of `browser-session`. But there are still some pieces that we want to keep: `SessionStorage`, `AutoSave`, ... Those are partially already migrated to `browser-state`, but for historic reasons they live in `browser-session`. Let's try to move them out of there, so that other components can reference them without depending on `browser-session`.

### LINKED ISSUE #9198: Get rid of SnapshotSerializer.toJSON()
After migrating `feature-tab-collections` (#8873) I think this will not be needed anymore.

### LINKED ISSUE #9292: Crash in BrowserStateSerializer: IllegalArgumentException: Unknown session key: source
Fallout from the feature-collections refactoring and crashing in Nightly. Looks like we forgot to handle `source`?

```
java.lang.IllegalArgumentException: Unknown session key: source
    at mozilla.components.browser.session.storage.BrowserStateSerializerKt.access$tab(BrowserStateSerializer.kt:21)
    at mozilla.components.feature.tab.collections.adapter.TabAdapter.restore(TabAdapter.kt:7)
    at org.mozilla.fenix.home.sessioncontrol.DefaultSessionControlController.handleCollectionOpenTabClicked(SessionControlController.kt:8)
    at org.mozilla.fenix.home.sessioncontrol.SessionControlInteractor.onCollectionOpenTabClicked(SessionControlInteractor.kt:1)
    at org.mozilla.fenix.home.sessioncontrol.viewholders.-$$LambdaGroup$js$CmLMMZGdtRGl-qY2EQsQLG5w5hQ.onClick(java-style lambda group:1)
```

https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/10288164/
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/10295333/

### PR DESCRIPTION
**Pull request by pocmo**
Closes #9198 too. And also closes #8600. And now closes #9292 too.

This is one piece of browser-session that we want to keep and moving it out allows more components to
not depend on browser-session anymore.

Multiple things are in this patch:
* Storage related code moved from browser-session to browser-session-storage
* BrowserStateSerializer gets split into BrowserStateWriter and BrowserStateReader
* SessionManager.Snapshot has been removed and we now save and restore independened from SessionManager.
  We already saved BrowserState. Now we restore into a generic `BrowsingSession`.
* feature-tab-collections no longer depends on browser-session.
* All restore code now goes through TabsUseCases instead of SessionManager directly.

### CODE REVIEW

**Comment by pocmo** [comment]
Do not land: This is for 2021. :)

File: components/browser/session-storage/src/androidTest/java/RestoringBrowsingSessionsTest.kt [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+@RunWith(AndroidJUnit4::class)
+class RestoringBrowsingSessionsTest {
+    private val context: Context
+        get() = ApplicationProvider.getApplicationContext()
+
+    /**
+     * App: Sample Browser
+     * Version: 2020-12-16
+     * GeckoView: 84.0 Beta (3147bf02ca678985f814ea2b091a194a9ac22f71)
+     */
```
Comment (pocmo) [inline components/browser/session-storage/src/androidTest/java/RestoringBrowsingSessionsTest.kt:41]: I want to add some more cases here and grab some serialized states from different versions of Fenix.

**Comment by pocmo** [comment]
Matching Fenix changes:
https://github.com/mozilla-mobile/fenix/pull/17120

File: .buildconfig.yml [hunk 2]
```diff
@@ -223,6 +223,10 @@ projects:
     path: components/browser/session
     description: 'An abstract layer hiding the actual browser engine implementation.'
     publish: true
+  browser-session-storage:
+    path: components/browser/session-storage
+    description: 'Component for saving and restoring a browsing session.'
```
[the remark this answers is not in the document]
Comment (csadilek) [reply .buildconfig.yml:228]: Oh I see, you're considering a browsing session to be a list of (reccoverable) tabs + selected tab ID. I found "session" to be confusing here.

File: components/browser/session-storage/src/androidTest/java/FullRestoreTest.kt [hunk 3]
```diff
@@ -0,0 +1,131 @@
...
+import mozilla.components.support.android.test.rules.WebserverRule
+import org.junit.Assert.assertNotNull
+import org.junit.Assert.assertNull
+import org.junit.Rule
+import org.junit.Test
+import org.junit.runner.RunWith
+import java.util.concurrent.TimeoutException
+
+@RunWith(AndroidJUnit4::class)
+class FullRestoreTest {
```
Comment (csadilek) [inline components/browser/session-storage/src/androidTest/java/FullRestoreTest.kt:29]: nit: Let's put this in a package. It's currently it root.

File: components/browser/session-storage/src/androidTest/java/RestoringBrowsingSessionsTest.kt [hunk 4]
```diff
@@ -0,0 +1,83 @@
...
+ * breaks then this is a strong indication that the restore code changed in a non backwards compatible
+ * way and that users may lose data.
+ *
+ * The tests here do also restore the "engine" state using GeckoView Nightly. Breaking changes in
+ * GeckoView may also cause session restore to break in a non backwards compatible way. Such breakages
+ * need to be reported to the GeckoView team to be fixed before reaching release branches.
+ */
+@Suppress("TestFunctionName")
+@RunWith(AndroidJUnit4::class)
+class RestoringBrowsingSessionsTest {
```
Comment (csadilek) [inline components/browser/session-storage/src/androidTest/java/RestoringBrowsingSessionsTest.kt:33]: nit: package

File: components/browser/session-storage/src/androidTest/java/FullRestoreTest.kt [hunk 5]
```diff
@@ -0,0 +1,131 @@
...
+            // Save state
+            // -------------------------------------------------------------------------------------
+
+            val storage = SessionStorage(context, engine)
+            storage.save(store.state)
+        }
+
+        run {
+            // -------------------------------------------------------------------------------------
+            // Restore into new classes
```
Comment (csadilek) [inline components/browser/session-storage/src/androidTest/java/FullRestoreTest.kt:73]: nit: new classes?

File: components/browser/session-storage/src/androidTest/java/RestoringBrowsingSessionsTest.kt (hunk 1 above)
Comment (csadilek) [reply components/browser/session-storage/src/androidTest/java/RestoringBrowsingSessionsTest.kt:41]: 🔥 awesome to have those tests.

File: components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/BrowsingSession.kt [hunk 6]
```diff
@@ -0,0 +1,15 @@
...
+ * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
+
+package mozilla.components.browser.session.storage
+
+import mozilla.components.browser.state.state.recover.RecoverableTab
+
+/**
+ * A restored browsing session, read from disk.
+ */
+data class BrowsingSession(
```
Comment (csadilek) [inline components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/BrowsingSession.kt:12]: What do you think about renaming this to `RecoverableBrowserState`, similar to `RecoverableTab`? `BrowsingSession` keeps confusing me.

File: components/browser/session-storage/src/test/java/mozilla/components/browser/session/storage/serialize/BrowserStateWriterReaderTest.kt [hunk 7]
```diff
@@ -41,22 +37,24 @@ class BrowserStateSerializerTest {
...
-        val serializer = BrowserStateSerializer()
+        val writer = BrowserStateWriter()
+        val reader = BrowserStateReader()
+
         val file = AtomicFile(
             File.createTempFile(UUID.randomUUID().toString(), UUID.randomUUID().toString())
         )
 
-        assertTrue(serializer.writeTab(tab, file))
+        Assert.assertTrue(writer.writeTab(tab, file))
```
Comment (csadilek) [inline components/browser/session-storage/src/test/java/mozilla/components/browser/session/storage/serialize/BrowserStateWriterReaderTest.kt:47]: nit: static import `Assert.assertTrue`, in all the asserts below too.

File: components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt [hunk 8]
```diff
@@ -299,16 +303,32 @@ class TabsUseCases(
...
+
+        /**
+         * Restores the browsing session from the given [SessionStorage].
+         */
+        suspend operator fun invoke(storage: SessionStorage) = withContext(Dispatchers.IO) {
+            val browsingSession = storage.restore()
+            if (browsingSession != null) {
+                withContext(Dispatchers.Main) {
+                    invoke(browsingSession)
+                }
```
Comment (csadilek) [inline components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt:330]: Nice! This will also close a ticket a filed a while ago: https://github.com/mozilla-mobile/android-components/issues/8600.


Can we also dispatch `RestoreCompleteAction` here which Fenix does itself right now?

File: samples/browser/src/main/java/org/mozilla/samples/browser/SampleApplication.kt [hunk 9]
```diff
@@ -55,6 +56,7 @@ class SampleApplication : Application() {
         Facts.registerProcessor(LogFactProcessor())
 
         components.engine.warmUp()
+        restoreBrowsingSession()
```
Comment (csadilek) [inline samples/browser/src/main/java/org/mozilla/samples/browser/SampleApplication.kt:59]: nit: `restoreBrowserState` would work here too, depending how you decide above.

**Review by csadilek — COMMENTED** [review]
Nice! 🔥 

Just made a few suggestions.

**Review by MihaiTabara — COMMENTED** [review]
LGTM from Taskcluster perspective, looking at `taskcluster/ci/config.yml` and `.buildconfig.yml`. That should automatically inject the component in the build + sign + beetmover jobs.

I was worried about the length name of the component but I see it's 24, below the treshold from [here](https://github.com/mozilla-mobile/android-components/blob/master/taskcluster/ci/build/kind.yml#L128) so I think we should be good. CC @escapewindow

File: components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/serialize/BrowserStateWriter.kt [hunk 10]
```diff
@@ -0,0 +1,118 @@
...
+        value(tab.readerState.active)
+
+        name(Keys.SESSION_LAST_ACCESS)
+        value(tab.lastAccess)
+
+        if (tab.readerState.active && tab.readerState.activeUrl != null) {
+            name(Keys.SESSION_READER_MODE_ACTIVE_URL_KEY)
+            value(tab.readerState.activeUrl)
+        }
+
```
Comment (csadilek) [inline components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/serialize/BrowserStateWriter.kt:98]: I think we also need to re-introduce the `Session.Source` field which we seem to have dropped relative to `SessionManager`? We did add it to the store as `SessionState.Source` but we're no longer serializing/deserializing it here.

See also: https://github.com/mozilla-mobile/android-components/issues/9292

Comment (csadilek) [reply components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/serialize/BrowserStateWriter.kt:98]: Put up a PR: https://github.com/mozilla-mobile/android-components/pull/9293

File: components/browser/session-storage/build.gradle [hunk 11]
```diff
@@ -0,0 +1,77 @@
...
+    implementation Dependencies.androidx_core_ktx
+    implementation Dependencies.kotlin_stdlib
+    implementation Dependencies.kotlin_coroutines
+
+    implementation Dependencies.androidx_browser
+    implementation Dependencies.androidx_lifecycle_runtime
+    implementation Dependencies.androidx_lifecycle_process
+
+    // We expose this as API because we are using Observable in our public API and do not want every
+    // consumer to have to manually import "support-base".
```
[the remark this answers is not in the document]
Comment (pocmo) [reply components/browser/session-storage/build.gradle:50]: Correct! I started with the `browser-session` build.gradle file for this component. Will remove this.

File: components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/BrowsingSession.kt (hunk 6 above)
Comment (pocmo) [reply components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/BrowsingSession.kt:12]: Yeah, makes sense. For the other cases I wonder if we should slowly go away from "Session" and use "Tab".

File: components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/serialize/BrowserStateReader.kt [hunk 12]
```diff
@@ -60,76 +57,62 @@ class BrowserStateSerializer {
...
+    var tabs: List<RecoverableTab>? = null
+    var selectedIndex: Int? = null
+    var selectedTabId: String? = null
 
-    beginArray()
-
-    state.tabs.filter { !it.content.private }.forEachIndexed { _, tab ->
-        tab(tab)
+    while (hasNext()) {
+        when (nextName()) {
```
Comment (csadilek) [inline components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/serialize/BrowserStateReader.kt:74]: Hm we're having a strange crash caused by `nextName`: https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/10295333/

This really shouldn't happen according to docs and after checking `hasNext` 🤔

Comment (pocmo) [reply components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/serialize/BrowserStateReader.kt:74]: I can't currently open that. Can you post part of the stack? In what code is it happening? (Since this here hasn't landed yet)

**Comment by pocmo** [comment]
Addressed all review comments and added additional test cases.

File: components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/serialize/BrowserStateReader.kt (hunk 12 above)
Comment (csadilek) [reply components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/serialize/BrowserStateReader.kt:74]: In our `BrowserStateSerializer`:

```
java.lang.IllegalStateException: Expected a name but was END_OBJECT
    at android.util.JsonReader.nextName(JsonReader.java:390)
    at mozilla.components.browser.session.storage.BrowserStateSerializerKt.access$tab(BrowserStateSerializer.kt:36)
    at mozilla.components.feature.tab.collections.adapter.TabAdapter.restore(TabAdapter.kt:7)
    at org.mozilla.fenix.home.sessioncontrol.DefaultSessionControlController.handleCollectionOpenTabClicked(SessionControlController.kt:8)
    at org.mozilla.fenix.home.sessioncontrol.SessionControlInteractor.onCollectionOpenTabClicked(SessionControlInteractor.kt:1)
    at org.mozilla.fenix.home.sessioncontrol.viewholders.-$$LambdaGroup$js$CmLMMZGdtRGl-qY2EQsQLG5w5hQ.onClick(java-style lambda group:1)
    at android.view.View.performClick(View.java:5646)
    at android.view.View$PerformClick.run(View.java:22473)
    at android.os.Handler.handleCallback(Handler.java:761)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:156)
    at android.app.ActivityThread.main(ActivityThread.java:6517)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

Comment (csadilek) [reply components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/serialize/BrowserStateReader.kt:74]: This happens in latest Nightly too and I can't find any usage of `nextName` that doesn't check for `hasNext`...so it's  weird.

Comment (pocmo) [reply components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/serialize/BrowserStateReader.kt:74]: Does it happen often? Would we want to block this on it?

Comment (csadilek) [reply components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/serialize/BrowserStateReader.kt:74]: Not often 85 events / 28 users. Nothing obvious in the metrics. All kinds of different Android versions and devices.

File: components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/RecoverableBrowserState.kt [hunk 13]
```diff
@@ -0,0 +1,15 @@
+/* This Source Code Form is subject to the terms of the Mozilla Public
+ * License, v. 2.0. If a copy of the MPL was not distributed with this
+ * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
+
+package mozilla.components.browser.session.storage
+
+import mozilla.components.browser.state.state.recover.RecoverableTab
+
+/**
+ * A restored browsing session, read from disk.
```
Comment (csadilek) [inline components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/RecoverableBrowserState.kt:10]: nit: A restored browser state...

File: components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/serialize/BrowserStateReader.kt (hunk 12 above)
Comment (csadilek) [reply components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/serialize/BrowserStateReader.kt:74]: One thing I noticed that could cause this is that we don't guard against concurrent access in tab-collections. In `SessionStorage` and everywhere else we use `AtomicFile`s we guard using a lock, but we don't do that for collections? This seems like a bug? We can fix / investigate separately.

**Review by csadilek — APPROVED** [review]
👍 

One nit and a follow-up below.

File: components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/serialize/BrowserStateReader.kt (hunk 12 above)
Comment (pocmo) [reply components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/serialize/BrowserStateReader.kt:74]: Yeah, sounds like something we could investigate. Not sure how that would actually happen when using the app, but since it is low in volume maybe some users were able to pull it off.

**Comment by pocmo** [comment]
Was doing one last test in Fenix and surprise.... I got this:

```Kotlin
E  Uncaught exception handled:
E  java.lang.IllegalStateException: Expected a name but was END_OBJECT
E      at android.util.JsonReader.nextName(JsonReader.java:390)
E      at mozilla.components.browser.engine.gecko.GeckoEngineSessionState$Companion.from(GeckoEngineSessionState.kt:58)
E      at mozilla.components.browser.engine.gecko.GeckoEngine.createSessionStateFrom(GeckoEngine.kt:172)
E      at mozilla.components.browser.session.storage.serialize.BrowserStateReaderKt.tab(BrowserStateReader.kt:131)
E      at mozilla.components.browser.session.storage.serialize.BrowserStateReaderKt.tabs(BrowserStateReader.kt:107)
E      at mozilla.components.browser.session.storage.serialize.BrowserStateReaderKt.browsingSession(BrowserStateReader.kt:78)
E      at mozilla.components.browser.session.storage.serialize.BrowserStateReaderKt.access$browsingSession(BrowserStateReader.kt:1)
E      at mozilla.components.browser.session.storage.serialize.BrowserStateReader.read(BrowserStateReader.kt:34)
E      at mozilla.components.browser.session.storage.SessionStorage.restore(SessionStorage.kt:48)
E      at mozilla.components.feature.tabs.TabsUseCases$RestoreUseCase$invoke$2.invokeSuspend(TabsUseCases.kt:329)
E      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E      at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E      at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
E      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
E      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
E      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

Will try to figure out how this happened.

**Comment by pocmo** [comment]
Extracted the session storage, created a test from it and fixed it. This could have happened in situations where we couldn't serialize an engine session yet and the JSON contained: `"engineSession": {}`

**Comment by pocmo** [comment]
Looks good now, here and testing in Fenix.

File: components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/serialize/BrowserStateReader.kt (hunk 12 above)
Comment (cadeyrn) [reply components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/serialize/BrowserStateReader.kt:74]: @csadilek @pocmo Please see https://github.com/mozilla-mobile/fenix/issues/17219 - except of the "nextName" line the stack trace looks very similar. And in the Firefox support we also got a similar report from another user. In both cases the crash only happens if you try to access a collection that was created before a certain build with a newer build and it's not reproducible with newly created collections.

Comment (csadilek) [reply components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/serialize/BrowserStateReader.kt:74]: @cadeyrn I think what users have been experiencing here most likely is https://github.com/mozilla-mobile/android-components/issues/9292 which also lines up with the stacktrace in the ticket you linked. This should already be fixed in latest Nightly.
