### PR TITLE
MediaStateMachine: Filter media of paused state and batch state updates.

### LINKED ISSUE #4115: Media notification pause/play button starts wrong video on sites with multiple MediaElements (that have autoplay?)
STR:
1. Go to a site with multiple video elements on it (example: https://shapeshed.com/examples/HTML5-video-element/)
2. Play a video in the list that is not-autoplayed.
3. Pause the video from the media notification.
4. Play the video from the media notification

## Expected
1. The media element of the paused video plays.

## Actual
1. The media element of another video (autoplay enabled video?) starts to play as well.

### PR DESCRIPTION
**Pull request by pocmo**
Closes #4115

---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [x] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [x] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by pocmo** [comment]
I'll go ahead and add some tests that cover this new behavior.

**Comment by pocmo** [comment]
> I'll go ahead and add some tests that cover this new behavior.

Not only this. I also need to fix tests that now need to wait for the state transition to happen. :joy:

**Comment by pocmo** [comment]
Okay, ready!

**Comment by Amejia481** [comment]
Awesome let's review it  :)

File: components/feature/media/src/main/java/mozilla/components/feature/media/state/MediaStateMachine.kt [hunk 1]
```diff
@@ -118,9 +132,19 @@ private class MediaSessionObserver(
...
+    @Synchronized
     private fun updateState() {
-        val state = determineNewState()
-        stateMachine.transitionTo(state)
+        // We delay updating the state here and cancel previous jobs in order to batch multiple
+        // state changes together before updating the state. In addition to reducing the work load
+        // this also allows us to treat multiple pause events as a single pause event that we can
+        // resume from.
+        updateStateJob?.cancel()
+        updateStateJob = GlobalScope.launch {
```
Comment (Amejia481) [inline components/feature/media/src/main/java/mozilla/components/feature/media/state/MediaStateMachine.kt]: Is there any specific reasons to use`GlobalScope`?

File: components/feature/media/src/main/java/mozilla/components/feature/media/state/MediaStateMachine.kt [hunk 2]
```diff
@@ -14,6 +19,8 @@ import mozilla.components.support.base.log.logger.Logger
 import mozilla.components.support.base.observer.Observable
 import mozilla.components.support.base.observer.ObserverRegistry
 
+private const val DELAY_STATE_UPDATE = 250L
```
Comment (Amejia481) [inline components/feature/media/src/main/java/mozilla/components/feature/media/state/MediaStateMachine.kt]: Should we include also include in the unit of the time delays?

File: components/feature/media/src/main/java/mozilla/components/feature/media/state/MediaStateMachine.kt (hunk 1 above)
Comment (pocmo) [reply components/feature/media/src/main/java/mozilla/components/feature/media/state/MediaStateMachine.kt]: Mostly because MediaStateMachine is a singleton object and doesn't have a lifetime. But then again it has start/stop methods. So I could create a scope in start() and cancel it in stop(). I'll update the PR.

File: components/feature/media/src/main/java/mozilla/components/feature/media/state/MediaStateMachine.kt (hunk 2 above)
Comment (pocmo) [reply components/feature/media/src/main/java/mozilla/components/feature/media/state/MediaStateMachine.kt]: Alright. I'll name it `DELAY_STATE_UPDATE_MS`.

**Comment by pocmo** [comment]
PR updated! :)
