### PR TITLE
Closes #11940: Disable auto report crashes on the new SentryService sdk

### LINKED ISSUE #11940: Disable auto report crashes on the new SentryService sdk
After some investigations, we discovered that the new sentry sdk was sending crashes automatically by default, we want to stop that behavior. Related ticket https://github.com/mozilla-mobile/fenix/issues/24403

### PR DESCRIPTION
**Pull request by Amejia481**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/lib/crash-sentry/src/main/java/mozilla/components/lib/crash/sentry/SentryService.kt [hunk 1]
```diff
@@ -121,11 +120,8 @@ class SentryService(
     @VisibleForTesting
     internal fun initSentry() {
         SentryAndroid.init(applicationContext) { options ->
-            options.dsn = Uri.parse(dsn).buildUpon()
-                .appendQueryParameter("uncaught.handler.enabled", "false")
-                .build()
-                .toString()
-
+            options.enableUncaughtExceptionHandler = false
```
Comment (Amejia481) [inline components/lib/crash-sentry/src/main/java/mozilla/components/lib/crash/sentry/SentryService.kt:123]: As interactions with the Sentry sdk are static is hard to create a meaningful unit test

**Review by grigoryk — APPROVED** [review]

**Comment by Amejia481** [comment]
🎉
