### PR TITLE
Closes #2563: Crash in QR scanner when camera no longer available

### LINKED ISSUE #2563: Crash in QR scanner when camera no longer available
This can happen temporarily and needs to be caught / logged. Right now it brings down the app.

```
 android.hardware.camera2.CameraAccessException: CAMERA_DISCONNECTED (2): submitRequestList:137: Camera device no longer alive
        at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:660)
        at android.hardware.camera2.impl.ICameraDeviceUserWrapper.submitRequestList(ICameraDeviceUserWrapper.java:86)
        at android.hardware.camera2.impl.CameraDeviceImpl.submitCaptureRequest(CameraDeviceImpl.java:899)
        at android.hardware.camera2.impl.CameraDeviceImpl.setRepeatingRequest(CameraDeviceImpl.java:938)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl.setRepeatingRequest(CameraCaptureSessionImpl.java:243)
        at mozilla.components.feature.qr.QrFragment$createCameraPreviewSession$$inlined$let$lambda$1.onConfigured(QrFragment.kt:428)
        at java.lang.reflect.Method.invoke(Native Method)
        at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
        at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: android.os.ServiceSpecificException: submitRequestList:137: Camera device no longer alive
        at android.os.Parcel.readException(Parcel.java:1698)
        at android.os.Parcel.readException(Parcel.java:1637)
        at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.submitRequestList(ICameraDeviceUser.java:334)
        at android.hardware.camera2.impl.ICameraDeviceUserWrapper.submitRequestList(ICameraDeviceUserWrapper.java:84)
```

### PR DESCRIPTION
**Pull request by csadilek**
This can happen temporarily e.g. during orientation changes. It doesn't affect the ability to keep scanning and should also not bring down the app as it does now :).

### CODE REVIEW

File: components/feature/qr/src/main/java/mozilla/components/feature/qr/QrFragment.kt [hunk 1]
```diff
@@ -127,7 +128,11 @@ class QrFragment : Fragment() {
         override fun onOpened(cameraDevice: CameraDevice) {
             cameraOpenCloseLock.release()
             this@QrFragment.cameraDevice = cameraDevice
-            createCameraPreviewSession()
+            try {
+                createCameraPreviewSession()
+            } catch (e: CameraAccessException) {
+                Log.log(Log.Priority.ERROR, "mozac-qr", e, message = "Failed to create camera preview session")
```
Comment (pocmo) [inline components/feature/qr/src/main/java/mozilla/components/feature/qr/QrFragment.kt]: nit: You have a bunch of those Log calls. Using `Logger` may be more comfortable. :)

Comment (csadilek) [reply components/feature/qr/src/main/java/mozilla/components/feature/qr/QrFragment.kt]: Ah, yes, will update. Desperately trying to write a test for this too :)

**Comment by csadilek** [comment]
Updated and test added!
