### PR TITLE
Fixes #3900 - Catch download IOExceptions

### LINKED ISSUE #3900: GeckoViewFetchClient: IOException: Request failed.
```
org.mozilla.geckoview.WebRequestError: Request failed, error=0x33, category=0x3
    at org.mozilla.gecko.mozglue.GeckoLoader.nativeRun(GeckoLoader.java)
    at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:476)

java.io.IOException: org.mozilla.geckoview.WebRequestError: Request failed, error=0x33, category=0x3
    at mozilla.components.browser.engine.gecko.fetch.GeckoViewFetchClient.fetch(GeckoViewFetchClient.kt:62)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService$performDownload$2.invokeSuspend(AbstractFetchDownloadService.kt:88)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService$performDownload$2.invoke
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:155)
    at kotlinx.coroutines.BuildersKt.withContext
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.performDownload(AbstractFetchDownloadService.kt:77)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.onStartCommand$feature_downloads_release$suspendImpl(AbstractFetchDownloadService.kt:71)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.onStartCommand$feature_downloads_release
    at mozilla.components.feature.downloads.CoroutineService$onStartCommand$job$1.invokeSuspend(CoroutineService.kt:46)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

From Reference Browser:
https://github.com/mozilla-mobile/reference-browser/issues/847

### PR DESCRIPTION
**Pull request by NotWoods**
Adds notifications for completed and failed downloads. `IOException` is now caught and displays the failed download notification.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.

### CODE REVIEW

File: components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt [hunk 1]
```diff
@@ -38,9 +39,11 @@ class AbstractFetchDownloadServiceTest {
...
         initMocks(this)
-        service = spy(object : AbstractFetchDownloadService(broadcastManager) {
+        service = spy(object : AbstractFetchDownloadService() {
             override val httpClient = client
         })
+        doReturn(broadcastManager).`when`(service).broadcastManager
+        doReturn(testContext).`when`(service).context
     }
 
     @Test
```
Comment (pocmo) [inline components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt]: I wonder if we could add some more tests to this eventually. With a mocked `Client` you can test all those cases where exceptions are thrown or if the download fails. How about we file a follow-up to test more cases here?

File: components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt [hunk 2]
```diff
@@ -156,51 +167,15 @@ abstract class AbstractFetchDownloadService(
             mimeType = download.contentType ?: "*/*",
             path = file.absolutePath,
             length = download.contentLength ?: file.length(),
-            showNotification = true,
+            // Only show notifications if our channel is blocked
+            showNotification = !DownloadNotification.isChannelEnabled(context),
```
Comment (pocmo) [inline components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt]: This change I do not understand, why do we only want to show a notification if the channel is blocked? 🤔

Comment (NotWoods) [reply components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt]: We try to show a custom notification and fall back to the system if our custom one is blocked.

File: components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt (hunk 1 above)
Comment (NotWoods) [reply components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt]: Filed #3917
