### PR TITLE
Handle "no selected session" case. 

### LINKED ISSUE #379: Handling "no sessions" in sample browser.
We need to handle the case where the user closes all tabs.

What happens in this case is probably up to the app. For example in Fennec we open a new tab that points to the start page. The sample browser currently just crashes because it wants to display the selected session which doesn't exist anymore.

### PR DESCRIPTION
**Pull request by pocmo**
Fixes #379 (See issue for details).

### CODE REVIEW

File: components/browser/session/src/main/java/mozilla/components/browser/session/storage/DefaultSessionStorage.kt [hunk 1]
```diff
@@ -109,7 +109,7 @@ class DefaultSessionStorage(
         return try {
             val json = JSONObject()
             json.put(VERSION_KEY, VERSION)
-            json.put(SELECTED_SESSION_KEY, sessionManager.selectedSession.id)
+            json.put(SELECTED_SESSION_KEY, sessionManager.selectedSession?.id)
```
Comment (csadilek) [inline components/browser/session/src/main/java/mozilla/components/browser/session/storage/DefaultSessionStorage.kt]: I think we should put an empty string in here instead of "null". When this value gets restored we're looking up a session with its ID using a non-nullable String.

Comment (pocmo) [reply components/browser/session/src/main/java/mozilla/components/browser/session/storage/DefaultSessionStorage.kt]: 👍

**Comment by csadilek** [comment]
@pocmo it was a minor test change so I went ahead and updated the commit. 😎 

Just need Taskcluster to behave now :).
