### PR TITLE
Closes #9075: Add mechanism to load URL when fails to launch third party app

### LINKED ISSUE #9075: Allow load URL when failed to launched third party apps
Currently there's no simple way to load the URL if app links fails to launch the third party app.  Add a way to load the URL as a fail-safe when launching third party apps fails for any reason.

### PR DESCRIPTION
**Pull request by rocketsroger**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt [hunk 1]
```diff
@@ -44,7 +45,8 @@ class AppLinksFeature(
     private val launchInApp: () -> Boolean = { false },
     private val useCases: AppLinksUseCases = AppLinksUseCases(context, launchInApp),
     private val failedToLaunchAction: () -> Unit = {},
-    private val loadUrlUseCase: SessionUseCases.DefaultLoadUrlUseCase? = null
+    private val loadUrlUseCase: SessionUseCases.DefaultLoadUrlUseCase? = null,
+    private val loadUrlWhenFailed: Boolean = false
```
Comment (pocmo) [inline components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt:49]: Is the `loadUrlWhenFailed` boolean needed? It looks like this can be controlled by `loadUrlUseCase` being `null` or not? 🤔

**Review by pocmo — APPROVED** [review]

File: components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt (hunk 1 above)
Comment (rocketsroger) [reply components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt:49]: Hmm, I see what you mean.  This doesn't really need a choice, as long as we can load the URL we should load it when it fails.  I'll update.  Thanks,
