### PR TITLE
Close #6674: Don't crash in AppLinksUsesCases with illegal Intent URI format

### LINKED ISSUE #6674: URISyntaxException: illegal Intent URI format
> https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/7839465

We probably should just ignore URIs that throw an `URISyntaxException`

```
java.net.URISyntaxException: illegal Intent URI format at index 193: upi://pay?pa=SOMEDETAILREMOVEDHERE/CPI#Intent;
    at android.content.Intent.parseUri(Intent.java:5269)
    at mozilla.components.feature.app.links.AppLinksUseCases$GetAppLinkRedirect.invoke(AppLinksUseCases.kt:7)
    at mozilla.components.feature.app.links.AppLinksInterceptor.onLoadRequest(AppLinksInterceptor.kt:9)
    at org.mozilla.fenix.AppRequestInterceptor.onLoadRequest(AppRequestInterceptor.kt:3)
    at mozilla.components.browser.engine.gecko.GeckoEngineSession$createNavigationDelegate$1.onLoadRequest(GeckoEngineSession.kt:13)
    at org.mozilla.geckoview.GeckoSession$3.handleMessage(GeckoSession.java:41)
    at org.mozilla.geckoview.GeckoSession$3.handleMessage(GeckoSession.java:1)
    at org.mozilla.geckoview.GeckoSessionHandler.handleMessage(GeckoSessionHandler.java:2)
    at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:1)
    at android.os.Handler.handleCallback(Handler.java:836)
    at android.os.Handler.dispatchMessage(Handler.java:103)
    at android.os.Looper.loop(Looper.java:203)
    at android.app.ActivityThread.main(ActivityThread.java:6339)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
```

### PR DESCRIPTION
**Pull request by rocketsroger**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt [hunk 1]
```diff
@@ -63,11 +64,23 @@ class AppLinksUseCases(
         return context.packageManager.resolveActivity(intent, PackageManager.MATCH_DEFAULT_ONLY)
     }
 
+    private fun safeParseUri(uri: String, flags: Int): Intent? {
+        var intent: Intent? = null
+        try {
```
Comment (csadilek) [inline components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt:69]: nit: use
```kotlin
return try { 
  intent = Intent.parseUri(uri, flags)
} catch (e: URISyntaxException) {
  null
}

```

Comment (rocketsroger) [reply components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt:69]: Thanks! Will fix.

**Comment by rocketsroger** [comment]
bors r=csadilek
