### PR TITLE
Closes #8292: DownloadMiddleware uses context.dispatch on wrong thread

### LINKED ISSUE #8292: DownloadMiddleware dispatches on wrong thread via context.dispatch
Cause of: https://github.com/mozilla-mobile/fenix/issues/14486

`restoreDownloads` switches to an IO thread and can't use `context.dispatch` which is synchronous on the store thread.  Regression of: https://github.com/mozilla-mobile/android-components/issues/8271

### PR DESCRIPTION
**Pull request by csadilek**
@Amejia481 when reviewing https://github.com/mozilla-mobile/android-components/issues/8271 I missed that we're switching to an IO thread in `restoreDownloads`. My mistake.

We're not allowing a synchronous dispatch on the store from another thread. Undoing that and adding a fix for the intermittent test failure.

### CODE REVIEW

**Comment by Amejia481** [comment]
I've already put a pr :) https://github.com/mozilla-mobile/android-components/pull/8291/files

**Comment by Amejia481** [comment]
bors retry

File: components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadMiddleware.kt [hunk 1]
```diff
@@ -101,7 +101,7 @@ class DownloadMiddleware(
         downloadStorage.getDownloads().collect { downloads ->
             downloads.forEach { download ->
                 if (!context.state.downloads.containsKey(download.id)) {
-                    context.dispatch(DownloadAction.RestoreDownloadStateAction(download))
+                    context.store.dispatch(DownloadAction.RestoreDownloadStateAction(download))
```
Comment (pocmo) [inline components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadMiddleware.kt:104]: This was the quick fix. But I'd recommend not passing the `MiddlewareContext` to this Coroutine at all since accessing it is not correct in any case.

Comment (Amejia481) [reply components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadMiddleware.kt:104]: Thanks for the feedback, could you further explain to understand better the issue?, what approach do you recommend in this case?

Comment (pocmo) [reply components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadMiddleware.kt:104]: pass the result of `context.store`, a `BrowserStore` around to coroutines like here and not the context object. Just to avoid using the wrong methods completely. :)

Comment (Amejia481) [reply components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadMiddleware.kt:104]: Something like this?
```kotlin
    private fun restoreDownloads(context: MiddlewareContext<BrowserState, BrowserAction>) {
        val store = context.store
        scope.launch {
            downloadStorage.getDownloads().collect { downloads ->
                downloads.forEach { download ->
                    if (!store.state.downloads.containsKey(download.id)) {
                        store.dispatch(DownloadAction.RestoreDownloadStateAction(download))
                        logger.debug("Download restarted from the storage ${download.fileName}")
                    }
                }
            }
        }
    }
```

File: components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadMiddlewareTest.kt [hunk 2]
```diff
@@ -186,6 +214,7 @@ class DownloadMiddlewareTest {
         assertTrue(store.state.downloads.isEmpty())
 
         store.dispatch(DownloadAction.RestoreDownloadsStateAction).joinBlocking()
+        dispatcher.advanceUntilIdle()
```
Comment (csadilek) [inline components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadMiddlewareTest.kt:218]: @Amejia481 I've just noticed we need both a `dispatcher.advanceUntilIdle` and also a `store.waitUnitldle` here to fix the intermittent test failure. The first one to make sure we've launched the coroutine in `restoreDownload` that dispatches the action. The second one to make sure the action has been processed by the store. We should have landed both PRs :).

Right now if we simulate a slow processing of the action the test would still fail.

Comment (Amejia481) [reply components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadMiddlewareTest.kt:218]: Thanks, I will put a pr to fix!

File: components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadMiddleware.kt (hunk 1 above)
Comment (pocmo) [reply components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadMiddleware.kt:104]: I'd move this earlier to the call `restoreDownloads(context.store)`, then you have no way of accessing `context` inside the `launch` block :)

File: components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadMiddlewareTest.kt (hunk 2 above)
Comment (pocmo) [reply components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadMiddlewareTest.kt:218]: P
T
O

File: components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadMiddleware.kt (hunk 1 above)
Comment (Amejia481) [reply components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadMiddleware.kt:104]: That's even nicer!!!

Comment (csadilek) [reply components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadMiddleware.kt:104]: @pocmo @Amejia481 but with this pattern we have the inverse problem. If we pass the store around in the middleware then devs tend to call `store.dispatch` when they really want the synchronous `context.dispatch` in the middleware. (That happened last week too)

Maybe we should rename the latter to `syncDispatch` to make this more obvious.

Comment (pocmo) [reply components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadMiddleware.kt:104]: Oh yeah, I only meant in this specific case where everything the function does is inside a coroutine.

```Kotlin
private fun restoreDownloads(...) = scope.launch {
  ...
}
```
