### PR TITLE
Closes #5097: Add web domain for autofill in authentication dialog

### LINKED ISSUE #5097: Add Site Domain for Autofill to AuthenticationDialogFragment in feature-prompts
Currently the Fenix chrome in `AuthenticationDialogFragment` doesn't know anything about the website underneath, and thus shows only app ID related password autofill suggestions (ie shows only suggestions related to mozilla.org or firefox for every dialog). 

## Steps to reproduce
Using device with 3rd party password manager installed and logged in (Lastpass, Lockwise, etc).
Open `https://jigsaw.w3.org/HTTP/Basic/` in Samples Browser/Fenix/RB

### Expected behavior
Any saved credentials for the `w3.org` website should be shown

### Actual behavior
Saved credentials for `mozilla.org` are shown

See: https://github.com/mozilla-mobile/fenix/issues/4205

In theory we should follow @jhugman 's suggestion there to add the domain to the dialog view so the system password manager's know what to fill.

> This is a missing feature of Fenix's BasicAuth dialog. Android triggers an autofill request when an `EditText` is entered, and guesses at the autofill `ViewStructure` that password managers will use.
> 
> The password managers use the package name to find the account to offer to autofill.
> 
> For browsers, it needs to add the [`webDomain` property](https://developer.android.com/reference/android/view/ViewStructure#setWebDomain(java.lang.String)) for page specific text boxes. GeckoView is already doing this, so this is why it works in web content already, but not in Fenix's chrome.
> 
> You need to implement [`onProvideAutofillStructure`](https://developer.android.com/reference/android/view/View#onProvideAutofillStructure(android.view.ViewStructure,%20int)) on the dialog, and the set the [`webDomain` property](https://developer.android.com/reference/android/view/ViewStructure#setWebDomain(java.lang.String)).
> 
> This will fix the problem in all password managers, including Lockwise. Until then, it's impossible for them to know the correct hostname.
> 
> The Android doc [Optimize your app for autofill](https://developer.android.com/guide/topics/text/autofill-optimize) seems to be pretty comprehensive.

One caveat - I timeboxed this to a few hours and tried to make custom edit texts for the dialog that overrode `onProvideAutofillStructure` and set the domain passed into the dialog, and I couldn't get it to work.

### PR DESCRIPTION
**Pull request by rocketsroger**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/AutofillEditText.kt [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+    internal var sessionUrl: String = ""
+
+    constructor (context: Context) : super(context)
+
+    constructor (context: Context, attrs: AttributeSet?) : super(context, attrs)
+
+    constructor (context: Context, attrs: AttributeSet?, defStyleAttr: Int) : super(context, attrs, defStyleAttr)
+
+    override fun onProvideAutofillStructure(structure: ViewStructure?, flags: Int) {
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
```
Comment (grigoryk) [inline components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/AutofillEditText.kt]: Do you know how this supposed to work prior to 26?

File: components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/AutofillEditText.kt [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+ * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
+package mozilla.components.feature.prompts.dialog
+
+import android.content.Context
+import android.os.Build
+import android.util.AttributeSet
+import android.view.ViewStructure
+import androidx.appcompat.widget.AppCompatEditText
+
+internal class AutofillEditText : AppCompatEditText {
```
Comment (grigoryk) [inline components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/AutofillEditText.kt]: A class comment here would be useful, explaining that this exists to make sure we call `setWebDomain` on the view structure.

File: components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/AuthenticationDialogFragment.kt [hunk 3]
```diff
@@ -80,7 +86,8 @@ internal class AuthenticationDialogFragment : PromptDialogFragment() {
     }
 
     private fun bindUsername(view: View) {
-        val usernameEditText = view.findViewById<EditText>(R.id.username)
+        val usernameEditText = view.findViewById<AutofillEditText>(R.id.username)
+        usernameEditText.sessionUrl = sessionUrl
```
Comment (grigoryk) [inline components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/AuthenticationDialogFragment.kt]: You need this for both `username` and `password` fields, because a "login" might have an empty username and still be legit, right? If so, can you add a comment describing this?

File: components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/AutofillEditText.kt (hunk 1 above)
Comment (rocketsroger) [reply components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/AutofillEditText.kt]: No, Autofill framework was only available starting API 26
https://developer.android.com/guide/topics/text/autofill

File: components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/AutofillEditText.kt (hunk 2 above)
Comment (rocketsroger) [reply components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/AutofillEditText.kt]: Agreed.  I'll add the comment.  Thanks,

File: components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/AuthenticationDialogFragment.kt (hunk 3 above)
Comment (rocketsroger) [reply components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/AuthenticationDialogFragment.kt]: Sure, I'll add comments to clarify why both needs to use `AutofillEditText`

**Comment by rocketsroger** [comment]
bors r=grigoryk
