### PR TITLE
Closes #6022: Let GeckoView prompt user when native code crash is non-fatal

### LINKED ISSUE #6022: Non-fatal crash should not crash the app
When testing with `about:crashcontent` it should not crash the app.  Currently both Reference Browser and Fenix crashes when non-fatal crash occurs in GeckoView.

### PR DESCRIPTION
**Pull request by rocketsroger**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt [hunk 1]
```diff
@@ -153,15 +153,17 @@ class CrashReporter(
...
         if (telemetryServices.isNotEmpty()) {
             sendCrashTelemetry(context, crash)
         }
 
+        // If crash is native code and non fatal then the view will handle the user prompt
+        if (crash is Crash.NativeCodeCrash && !crash.isFatal) {
+            // App has registered a pending intent
+            sendNonFatalCrashIntent(context, crash)
+            return
+        }
```
Comment (pocmo) [inline components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt]: Why do we switch to always doing this? Previously we did this only when we had an intent and that kind of made sense? Currently we explicit allow apps to not provide an Intent if they do not intent to handle crashes in their UI. 🤔

Comment (rocketsroger) [reply components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt]: > Why do we switch to always doing this? Previously we did this only when we had an intent and that kind of made sense? Currently we explicit allow apps to not provide an Intent if they do not intent to handle crashes in their UI. 🤔

You're right.  I'll update so if there's no intent it should continue on to report the crash.
