### PR TITLE
Closes #4824: Throw exceptions on certain Rust errors

### LINKED ISSUE #4824: AutopushFeature: throw exceptions on Rust errors
If we get a Rust error that is NOT `CommunicationError` or `CommunicationServerError`, we should throw on it since those are unrecoverable issues and we need to know about them.

See [RustError.kt][0] for the full list.

[0]: https://github.com/mozilla/application-services/blob/master/components/push/android/src/main/java/mozilla/appservices/push/RustError.kt#L15-L27

### PR DESCRIPTION
**Pull request by jonalmeida**
Moved the internal `CoroutineScope.launchAndTry` extension to be a bit more generic for easier testing.

---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [x] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt [hunk 1]
```diff
@@ -337,6 +335,23 @@ class AutoPushFeature(
...
 
+internal fun CoroutineScope.launchAndTry(
+    block: suspend CoroutineScope.() -> Unit,
+    errorBlock: (Exception) -> Unit
+): Job {
+    return launch {
+        try {
+            block()
+        } catch (e: RustPushError) {
+            if (e !is CommunicationServerError && e !is CommunicationError) {
```
Comment (grigoryk) [inline components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt]: I'd prefer a `when`, but this works. Worst case is that we'll accidentally throw when we shouldn't (e.g. a new "non-terminal" error type is added in the underlying library, and this check degrades), which we should be able to catch in Sentry and resolve.

Perhaps though you can guard against this hypothetical future by forcing an exhaustive `when` treatment? e.g.
```
try {
  block()
} catch (e: RustPushError) {
   if (shouldReThrow(e)) {
     throw e
   }
}

private fun shouldReThrow(e: RustPushError): Boolean {
  return when (e) {
    // Do not re-throw intermittent errors.
    is CommunicationServerError, CommunicationError -> false
    // Re-throw internal errors that are unrecoverable/indicative of bugs. 
    is InternalPanic, CryptoError, AlreadyRegisteredError, StorageError, MissingRegistrationTokenError, StorageSqlError, TranscodingError, UrlParseError -> true
  }
}
```

Comment (jonalmeida) [reply components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt]: You're right, this is a much safer change. I'd rather fail to compile. I was just being a lazy typist.

Comment (grigoryk) [reply components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt]: Well, I did the exact thing as you in my version in FxA... So yeah, we're all lazy :) I'll push a PR to fix up a similar function in FxA.

Comment (jonalmeida) [reply components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt]: Ah, since the Rust errors are just inherited and not a sealed class, we can never truly make this exhaustive; I have to add _every_ exception to make the compiler happy. 

If we take this direction, we would be swallowing up new error types instead of throwing on them i.e. doing the inverse of the worst case you mentioned.

My preference is to throw on a new error type added. If it was added, that means new functionality was added, and that means the new thing is failing already! 😄 

Kotlin when clause still not happy when we've made every error explicit. We should really ask a-s to change the errors, but that's not really worth their time.

Comment (grigoryk) [reply components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt]: Yeah, I just hit that as well.

> My preference is to throw on a new error type added.

Agreed, let's go with that!

**Comment by jonalmeida** [comment]
bors r=grigoryk
