### PR TITLE
Closes #5063: better exception reporting during migrations

### LINKED ISSUE #5063: IllegalStateException in FennecMigrator$runMigrationsAsync
Three different stacktraces with multiple reports:

https://crash-stats.mozilla.com/report/index/c2929c40-54fa-4140-8e99-93bad0191112

https://crash-stats.mozilla.com/report/index/6935abd3-27e1-4805-9f7b-dc39c0191112

https://crash-stats.mozilla.com/report/index/881be396-038a-49f2-aa99-3121b0191112

### PR DESCRIPTION
**Pull request by grigoryk**
Patch 1:
>
    We are logging exceptions when no profile is found, which is actually a legit case.
    There will be no profile on a fresh install, for example.
    
    This patch makes these kinds of exceptions more precise/useful: we'll only send a report
    in case there's a profile but a missing dbPath. We'll now also send an exception in case
    of an IOException while parsing profiles.

Patch 2:
>
    Submit unexpected exceptions during migrations

---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/support/migration/src/main/java/mozilla/components/support/migration/FennecMigrator.kt [hunk 1]
```diff
@@ -334,6 +371,9 @@ class FennecMigrator private constructor(
             logger.debug("Migrated bookmarks.")
             Result.Success(Unit)
         } catch (e: Exception) {
+            crashReporter.submitCaughtException(
+                FennecMigratorException.MigrateBookmarksException(e::class.qualifiedName)
```
Comment (pocmo) [inline components/support/migration/src/main/java/mozilla/components/support/migration/FennecMigrator.kt]: Instead of the `name` (String) parameter... doesn't it make more sense to set the `cause` (Exception) parameter so that we get a nice stacktrace including the stacktrace of the exception that happened here? Much more helpful and doesn't require reflection? :)

Comment (grigoryk) [reply components/support/migration/src/main/java/mozilla/components/support/migration/FennecMigrator.kt]: Done; i've decided to not block on the PII thing right now, and deal with it more generally in a follow-up: https://github.com/mozilla-mobile/android-components/issues/5095
