### PR TITLE
Closes #8567: Prevent crashes when trying to add to the system databases

### LINKED ISSUE #8567: IllegalArgumentException: Unknown URL content://downloads/my_downloads
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/8827103/?query=is%3Aunresolved

```
java.lang.IllegalArgumentException: Unknown URL content://downloads/my_downloads
    at android.content.ContentResolver.insert(ContentResolver.java:1280)
    at android.app.DownloadManager.addCompletedDownload(DownloadManager.java:1753)
    at android.app.DownloadManager.addCompletedDownload(DownloadManager.java:1718)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.addToDownloadSystemDatabaseCompat$feature_downloads_release(AbstractFetchDownloadService.kt:18)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.updateDownloadNotification$feature_downloads_release(AbstractFetchDownloadService.kt:5)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.access$updateDownloadNotification(AbstractFetchDownloadService.kt:5)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService$onStartCommand$2.invokeSuspend(AbstractFetchDownloadService.kt:7)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.AwaitKt.resume(Await.kt:11)
    at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:18)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:5)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:2)
    at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:1)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:7325)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

### PR DESCRIPTION
**Pull request by Amejia481**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt [hunk 1]
```diff
@@ -482,18 +482,22 @@ abstract class AbstractFetchDownloadService : Service() {
...
+                isMediaScannerScannable = isMediaScannerScannable,
+                mimeType = mimeType,
+                path = path,
+                length = length,
+                // Only show notifications if our channel is blocked
+                showNotification = showNotification,
+                uri = uri,
+                referer = referer
+            )
+        } catch (e: IllegalArgumentException) {
```
Comment (grigoryk) [inline components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt:498]: Reading the code a bit, this is coming out of a ContentResolver - as its trying to resolve a ContentProvider for the `downloads` authority (and, fails, obviously, it doesn't seem like a well-formed authority to me). But, it only does that (attempts to resolve a content provider via authority) because the scheme is `content`.

And just above, we already have a check to ensure that url's scheme is `http` or `https` - `val url = if (!download.isScheme(listOf("http", "https"))) null else download.url.toUri()`.

So, it seems like this shouldn't be possible to hit this..? Perhaps the crash reports are before that url scheme check was added? But no - this check was added in https://github.com/mozilla-mobile/android-components/pull/7280 which was 2 years ago, and we've reports from recent versions (sentry says, A-C 98 hit this somehow... e.g. https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/10551720/events/latest/).

So, how can this be..?

nit: i'd also move that `url` check into this method, where we're actually calling into `DownloadManager`.

Comment (csadilek) [reply components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt:496]: @Amejia481 @grigoryk The way I read this is that these are different URLs! Our check here is for the original HTTP URL of the download, but the failing check / crash is for the base URL of all downloads i.e., the URL of the table to insert the download into: https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/content/ContentResolver.java;l=2189?q=ContentResolver.java

Comment (csadilek) [reply components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt:496]: The original download URL is passed along as content values, but the exception is thrown for because `Downloads.Impl.CONTENT_URI` doesn't resolve on those devices: https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/app/DownloadManager.java;l=1569

Comment (Amejia481) [reply components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt:496]: Thanks for the clarification, in that case how should we recover from that or prevent that behavior? At the moment catching the exception prevent the crash, I'm not sure how we could proceed?

**Review by csadilek — APPROVED** [review]
