### PR TITLE
Issue #963: Fretboard: Handle reading corrupt JSON.

### LINKED ISSUE #963: Fretboard: JSONException
From Focus.

```
Caused by: org.json.JSONException: 
  at org.json.JSONTokener.syntaxError (JSONTokener.java:449)
  at org.json.JSONTokener.nextValue (JSONTokener.java:97)
  at org.json.JSONObject.<init> (JSONObject.java:156)
  at org.json.JSONObject.<init> (JSONObject.java:173)
  at mozilla.components.service.fretboard.storage.flatfile.ExperimentsSerializer.fromJson (ExperimentsSerializer.kt:47)
  at mozilla.components.service.fretboard.storage.flatfile.FlatFileExperimentStorage.retrieve (FlatFileExperimentStorage.kt:25)
  at mozilla.components.service.fretboard.Fretboard.loadExperiments (Fretboard.kt:39)
  at org.mozilla.focus.FocusApplication.loadExperiments (FocusApplication.kt:97)
  at org.mozilla.focus.FocusApplication$onCreate$1.doResume (FocusApplication.kt:60)
  at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume (CoroutineImpl.kt:42)
  at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run (Dispatched.kt:162)
  at kotlinx.coroutines.experimental.DispatchedContinuation.run (Dispatched.kt:26)
  at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent (EventLoop.kt:148)
  at kotlinx.coroutines.experimental.BlockingCoroutine.joinBlocking (Builders.kt:82)
  at kotlinx.coroutines.experimental.BuildersKt__BuildersKt.runBlocking (Builders.kt:58)
  at kotlinx.coroutines.experimental.BuildersKt.runBlocking (Unknown Source)
  at kotlinx.coroutines.experimental.BuildersKt__BuildersKt.runBlocking$default (Builders.kt:48)
  at kotlinx.coroutines.experimental.BuildersKt.runBlocking$default (Unknown Source)
  at org.mozilla.focus.FocusApplication.onCreate (FocusApplication.kt:59)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1014)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:4800)
```

### PR DESCRIPTION
**Pull request by pocmo**
Closes #963.

### CODE REVIEW

File: components/service/fretboard/src/test/java/mozilla/components/service/fretboard/storage/flatfile/FlatFileExperimentStorageTest.kt [hunk 1]
```diff
@@ -125,4 +125,17 @@ class FlatFileExperimentStorageTest {
         assertEquals(0, experimentsResult.experiments.size)
         assertNull(experimentsResult.lastModified)
     }
+
+    @Test
+    fun testReadingCorruptJSON() {
+        val file = File(RuntimeEnvironment.application.filesDir, "corrupt-experiments.json")
+        file.writer().use {
+            it.write("""{"experiment":[""")
```
Comment (Amejia481) [inline components/service/fretboard/src/test/java/mozilla/components/service/fretboard/storage/flatfile/FlatFileExperimentStorageTest.kt]: Now, it's not meaningful but In the future, if we're going to test with the same JSON input in multiple test classes, instead of creating it manually, we could have a single JSON file in assets that can reuse in multiple tests this way when we want to change the JSON we only have one point of change to change.
