### PR TITLE
Closes #11360: Strip non-digit characters when calling getCreditCardIIN

### LINKED ISSUE #11360: CreditCardUtils: NumberFormatException: For input string: "[..]"
For https://github.com/mozilla-mobile/fenix/issues/22607

### PR DESCRIPTION
**Pull request by Amejia481**
Fixes #11360

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/support/utils/src/main/java/mozilla/components/support/utils/ext/String.kt [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+ * License, v. 2.0. If a copy of the MPL was not distributed with this
+ * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
+
+package mozilla.components.support.utils.ext
+
+/**
+ * Strips characters other than digits from a string.
+ * Used to strip a credit card number user input of spaces and separators.
+ */
+fun String.toCreditCardNumber(): String {
```
Comment (Amejia481) [inline components/support/utils/src/main/java/mozilla/components/support/utils/ext/String.kt:11]: Couldn't add it to `support-ktx` as we need to use this function on `support-utils` and this creates a circular dependency.

File: components/support/utils/src/test/java/mozilla/components/support/utils/ext/StringTest.kt [hunk 2]
```diff
@@ -0,0 +1,22 @@
+package mozilla.components.support.utils.ext
+
+/* This Source Code Form is subject to the terms of the Mozilla Public
```
Comment (gabrielluong) [inline components/support/utils/src/test/java/mozilla/components/support/utils/ext/StringTest.kt:3]: This should be above the package

File: components/support/utils/src/test/java/mozilla/components/support/utils/ext/StringTest.kt [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+import org.junit.Test
+import org.junit.runner.RunWith
+
+@RunWith(AndroidJUnit4::class)
+class StringTest {
+
+    @Test
+    fun `GIVEN a string credit card number WHEN calling toCreditCardNumber THEN any character that is not a digit will removed`() {
+        val number = "385  -  2 0 0 - 0 0 0 2 3 2 3   7"
+        val validResult = "38520000023237"
```
Comment (gabrielluong) [inline components/support/utils/src/test/java/mozilla/components/support/utils/ext/StringTest.kt:18]:
```suggestion
        val expectedResult = "38520000023237"
```

**Review by gabrielluong — APPROVED** [review]
