### PR TITLE
Fix #4418 - Clear manifest on location change

### LINKED ISSUE #4418: Incorrect PWA added to home screen
On today’s build I first added Twitter to my home screen. Which works and starts the Twitter lite site. Then I went to Starbucks.ca and also added it to my home screen. 

What appeared on my home screen were two icons named Twitter. And they both start Twitter Lite. 

I know Starbucks.com is A PWA but I am not sure if the same is true for Starbucks.ca.

### PR DESCRIPTION
**Pull request by NotWoods**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt [hunk 1]
```diff
@@ -51,6 +51,8 @@ internal class EngineObserver(
             it.reject()
             true
         }
+
+        session.webAppManifest = null
```
Comment (pocmo) [inline components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt]: There are already some similar cases tested in `EngineObserverTest` ... 😜

**Comment by NotWoods** [comment]
bors r=pocmo
