### PR TITLE
 Closes #3195: Ignore UrlParseFailed exceptions coming out of places

### LINKED ISSUE #3195: Catch UrlParseFailed places exceptions in PlacesStorage & friends
Specifically, do this for `noteObservation` calls. We don't want to crash if we fail to record invalid urls into our history store.

Consider similar treatment for others `places` calls as well.

### PR DESCRIPTION
**Pull request by grigoryk**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

File: components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesStorage.kt [hunk 1]
```diff
@@ -48,4 +52,15 @@ abstract class PlacesStorage(context: Context) : Storage, SyncableStore {
         scope.coroutineContext.cancelChildren()
         places.close()
     }
+
+    /**
+     * Runs [block] described by [operation], ignoring and logging any thrown [UrlParseFailed] exceptions.
+     */
+    protected fun ignoreUrlExceptions(operation: String, block: () -> Unit) {
```
Comment (jonalmeida) [inline components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesStorage.kt]: nit: `inline` would probably help performance if we hit this case often. No biggie though.
