### PR TITLE
Closes #5946: HttpIconLoad$toIconLoaderResult can throw an IOException

### LINKED ISSUE #5946: HttpIconLoader’s toIconLoaderResult can throw an IOException
There is a non significant amount of crashes that look like this:

```
java.io.IOException: Timed out
    at org.mozilla.geckoview.GeckoInputStream.read(GeckoInputStream.java:11)
    at org.mozilla.geckoview.GeckoInputStream.read(GeckoInputStream.java:6)
    at androidx.transition.CanvasUtils.copyTo$default(CanvasUtils.java:4)
    at androidx.transition.CanvasUtils.readBytes(CanvasUtils.java:2)
    at mozilla.components.browser.icons.loader.HttpIconLoaderKt$toIconLoaderResult$1.invoke(HttpIconLoader.kt:1)
    at mozilla.components.concept.fetch.Response$Body.useStream(Response.kt:1)
    at mozilla.components.browser.icons.loader.HttpIconLoader.load(HttpIconLoader.kt:21)
    at mozilla.components.browser.icons.BrowserIcons$loadIcon$1.invokeSuspend(BrowserIcons.kt:23)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:919)
```

We catch the IOException from `Fetch` but we should do the same for the call to `toIconLoaderResult`. The problem is that the fetch is not actually done at that point, and calling `read()` on the `GeckoInputStream` can still return an EOF or TimeOut since it is a 'live' read from an active socket.

### PR DESCRIPTION
**Pull request by st3fan**
This patch for #5946 (which is a relatively high crasher) simply pulls `response.toIconLoaderResult` into the existing try/catch so that an IOException originating from `Response.body.readBytes()` will be caught too and be turned into a `IconLoader.Result.NoResult` result.

> I think I have a decent test but I don't know mockito well enough to understand if this is correct. 

---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/browser/icons/src/test/java/mozilla/components/browser/icons/loader/HttpIconLoaderTest.kt [hunk 1]
```diff
@@ -196,4 +197,31 @@ class HttpIconLoaderTest {
...
+
+    @Test
+    fun `Loader will return NoResult for IOExceptions happening during toIconLoaderResult`() {
+        val client: Client = mock()
+
+        val failingStream: InputStream = object : InputStream() {
+            override fun read(): Int {
+                throw IOException("Kaboom")
+            }
+        }
```
Comment (pocmo) [inline components/browser/icons/src/test/java/mozilla/components/browser/icons/loader/HttpIconLoaderTest.kt]: Another option here is to use [Mockito](https://site.mockito.org/) to create a mocked `InputStream` that throws:

```Kotlin
val failingStream: InputStream = mock()
doThrow(IOException("Kaboom")).when(failingStream).read()
```

But creating your own stream is nice too!
