### PR TITLE
Closes #5766: AppLinksFeature should ignore file scheme.

### LINKED ISSUE #5766: android.os.FileUriExposedException: file:///storage/[redacted].html exposed beyond app through Intent.getData()
android.os.FileUriExposedException: file:///storage/[redacted].html exposed beyond app through Intent.getData()
    at android.os.StrictMode.onFileUriExposed(StrictMode.java:1978)
    at android.net.Uri.checkFileUriExposed(Uri.java:2371)
    at android.content.Intent.prepareToLeaveProcess(Intent.java:10286)
    at android.content.Intent.prepareToLeaveProcess(Intent.java:10237)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1669)
    at android.app.ContextImpl.startActivity(ContextImpl.java:927)
    at android.app.ContextImpl.startActivity(ContextImpl.java:898)
    at android.content.ContextWrapper.startActivity(ContextWrapper.java:389)
    at mozilla.components.feature.app.links.AppLinksUseCases$OpenAppLinkRedirect.invoke(AppLinksUseCases.kt:1)
    at mozilla.components.feature.app.links.AppLinksUseCases$OpenAppLinkRedirect.invoke$default(AppLinksUseCases.kt:1)
    at org.mozilla.fenix.components.toolbar.BrowserInteractor.onBrowserToolbarMenuItemTapped(BrowserInteractor.kt:152)
    at org.mozilla.fenix.components.toolbar.BrowserToolbarView$$special$$inlined$with$lambda$3.invoke(BrowserToolbarView.kt:4)
    at -$$LambdaGroup$ks$OXxCWf19-fDzabrXRGiuvG8c2CU.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:157)
    at -$$LambdaGroup$js$LEnS7s7YG-ssjFYEX4prPuSHZ0U.onClick(java-style lambda group:199)
    at android.view.View.performClick(View.java:6608)
    at android.view.View.performClickInternal(View.java:6585)
    at android.view.View.access$3100(View.java:785)
    at android.view.View$PerformClick.run(View.java:25921)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:201)
    at android.app.ActivityThread.main(ActivityThread.java:6806)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

### PR DESCRIPTION
**Pull request by rocketsroger**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt [hunk 1]
```diff
@@ -177,7 +178,10 @@ class AppLinksUseCases(
 
             val appIntent = when (intent.data) {
                 null -> null
-                else -> intent
+                else -> when (alwaysDeniedSchemes.contains(intent?.data?.scheme)) {
+                    true -> null
+                    else -> intent
+                }
```
Comment (pocmo) [inline components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt]: nit: it may be worth flattening this into a single when, e.g. something like

```Kotlin
            val appIntent = when {
                intent.data == null -> null
                alwaysDeniedSchemes.contains(intent?.data?.scheme) -> null
                else -> intent
          }
```

File: components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt [hunk 2]
```diff
@@ -189,12 +193,17 @@ class AppLinksUseCases(
...
+    inner class OpenAppLinkRedirect internal constructor(
         private val context: Context
     ) {
         operator fun invoke(appIntent: Intent?, failedToLaunchAction: () -> Unit = {}) {
             appIntent?.let {
                 try {
+                    val scheme = appIntent.data?.scheme
+                    if (scheme != null && alwaysDeniedSchemes.contains(scheme)) {
+                        return
+                    }
```
Comment (pocmo) [inline components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt]: I do not have the full context here - but is that not too late? If we already know that we are not going to open this - should we ever allow anyone to get here?

File: components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt (hunk 1 above)
Comment (rocketsroger) [reply components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt]: Agreed.  I'll flatten it.

File: components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt (hunk 2 above)
Comment (rocketsroger) [reply components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt]: technically it can still be called directly by the caller.  Fenix currently calls directly like this `appLinksUseCases.openAppLink.invoke(redirect.appIntent)`. Which can still cause a crash when the redirect.appIntent is a file.
