### PR TITLE
Closes #7626: Add download log entries

### LINKED ISSUE #7526: Fennec migration: (Regression) Tapping the app icon dismisses the migration onboarding screen
## Steps to reproduce
1. Install the Fenix migration build over Fennec. Open the updating app.
2. Wait for the migration complete screen, with the "Start Firefox Beta" button;
3. Minimize the app by pressing the home button;
4. Tap the app icon to return to Fenix. 
### Expected behavior
The migration complete onboarding screen is still shown.
### Actual behavior
The migration onboarding is dismissed when you return to the app and the Fenix onboarding screen is displayed. Also, the migration complete notification remains displayed until dismissed.

### Notes:

Seem to be a regression of [#7980](https://github.com/mozilla-mobile/fenix/issues/7980).

### Device information

* Android device: Motorola Moto G6 (Android 8), Huawei MediaPad M3 lite (Android 7), Xiaomi Mi Pad 2 (Android 5.1)
* Fenix version: Beta Migration 78.0.0-beta.1 from 6/26

### LINKED ISSUE #7626: Add download logs entries
In some cases it's pretty difficult to understand what could be the possible reason for a download issue, having some logs that can give us an idea of what may be happening can be really useful.

### PR DESCRIPTION
**Pull request by Amejia481**
To help to debug this https://github.com/mozilla-mobile/fenix/issues/12297 edge cases issue and other future bugs, we need to add some log entries to be able determine the source of an issues.

---

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt [hunk 1]
```diff
@@ -165,6 +167,7 @@ abstract class AbstractFetchDownloadService : Service() {
                         setDownloadJobStatus(currentDownloadJobState, PAUSED)
                         currentDownloadJobState.job?.cancel()
                         emitNotificationPauseFact()
+                        logger.info("ACTION_PAUSE for ${currentDownloadJobState.state.url} PAUSED")
```
Comment (csadilek) [inline components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt:170]: Let's use `debug` instead of `info`? Seems like the perfect case for it :)

File: components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt [hunk 2]
```diff
@@ -595,11 +611,14 @@ abstract class AbstractFetchDownloadService : Service() {
...
                 updateDownloadState(newState)
             }
+            logger.info("verifyDownload for ${download.state.url} COMPLETED")
         }
     }
 
     private fun copyInChunks(downloadJobState: DownloadJobState, inStream: InputStream, outStream: OutputStream) {
         val data = ByteArray(CHUNK_SIZE)
+        logger.info("starting copyInChunks ${downloadJobState.state.url}" +
+                " currentBytesCopied ${downloadJobState.state.url}")
```
Comment (csadilek) [inline components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt:621]: You're logging the URL here twice, instead of `currentBytesCopied`.

File: components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt [hunk 3]
```diff
@@ -612,6 +631,8 @@ abstract class AbstractFetchDownloadService : Service() {
 
             outStream.write(data, 0, bytesRead)
         }
+        logger.info("Finishing copyInChunks ${downloadJobState.state.url} " +
+                "currentBytesCopied ${downloadJobState.state.url}")
```
Comment (csadilek) [inline components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt:635]: See above. Should be `currentBytesCopied`.

File: components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt (hunk 1 above)
Comment (Amejia481) [reply components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt:170]: Should `logger.debug` logs only be available on debug builds and `logger.info` on all builds?

File: components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt (hunk 2 above)
Comment (Amejia481) [reply components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt:621]: Thanks 👍

File: components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt (hunk 1 above)
Comment (Amejia481) [reply components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt:170]: Would mind help me to clarify, I'm bit confused in that aspect as I'm trying to log statements that could help to access an issue even if the app is a release build.

Comment (Amejia481) [reply components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt:170]: Cases like this one https://github.com/mozilla-mobile/fenix/issues/12297, where we don't have enough information to determine what is the issue.

Comment (csadilek) [reply components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt:170]: @Amejia481 Pretty much the same. Hooking up `adb logcat` you will see these as debug log statements which is exactly what you want. You're using them to debug a problem. You don't need a debug build to see them. You can try running `adb logcat` and opening Fenix beta/release. You will see statements marked with "D".

Comment (Amejia481) [reply components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt:170]: Thanks 👍

**Comment by Amejia481** [comment]
I updated the pr :)

**Comment by Amejia481** [comment]
bors r=csadilek
