### PR TITLE
Closes #102: Fix intermittent SearchEngineManagerTest failure

### LINKED ISSUE #102: SearchEngineManagerTest fails when run on its own
The specific tests that fails is `locale update broadcast will trigger reload` .

### PR DESCRIPTION
**Pull request by csadilek**
Problem here is that the broadcasted intent is processed on a different thread than the assert that verifies `loadSearchEngine` was called: https://github.com/mozilla-mobile/android-components/blob/master/components/browser/search/src/test/java/mozilla/components/browser/search/SearchEngineManagerTest.kt#L138

The problem is easy to reproduce by running just this one test in AS (`locale update broadcast will trigger reload`). The assertion then runs before `loadSearchEngines`, and fails.

This fixes the problem by introducing a `CountDownLatch` to make sure `loadSearchEngines` is finished before asserting. Timeout is provided to not have our tests get stuck in case it ever fails.

### CODE REVIEW

File: components/browser/search/src/test/java/mozilla/components/browser/search/SearchEngineManagerTest.kt [hunk 1]
```diff
@@ -135,6 +139,7 @@ class SearchEngineManagerTest {
 
             shadow.sendBroadcast(Intent(Intent.ACTION_LOCALE_CHANGED))
 
+            countDownLatch.await(2, TimeUnit.SECONDS)
```
Comment (pocmo) [inline components/browser/search/src/test/java/mozilla/components/browser/search/SearchEngineManagerTest.kt]: Another option:

```Kotlin
launch(CommonPool) {}.join()
```

Comment (pocmo) [reply components/browser/search/src/test/java/mozilla/components/browser/search/SearchEngineManagerTest.kt]: Could be moved to an extension function too:

```Kotlin
    fun CoroutineDispatcher.waitForDone() {
        val dispatcher: CoroutineDispatcher = this
        runBlocking {
            launch(dispatcher) {}.join()
        }
    }


// ...

CommonPool.waitForDone()
```

Comment (csadilek) [reply components/browser/search/src/test/java/mozilla/components/browser/search/SearchEngineManagerTest.kt]: OK, I think launch(CommoPool) {}.join() is clearer here. Updated.
