### PR TITLE
Closes #8464 ensure prompts are not completed before confirming

### LINKED ISSUE #8464: Cannot confirm/dismiss a Prompt twice (LoginPicker).
```
java.lang.RuntimeException: Cannot confirm/dismiss a Prompt twice.
    at org.mozilla.geckoview.GeckoSession$PromptDelegate$BasePrompt.confirm(GeckoSession.java:5)
    at org.mozilla.geckoview.GeckoSession$PromptDelegate$AutocompleteRequest.confirm(GeckoSession.java:2)
    at mozilla.components.browser.engine.gecko.prompt.-$$LambdaGroup$ks$l04uV7dUmf6bB3wi8mBVf1nzQ3g.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:3)
    at mozilla.components.feature.prompts.login.LoginPicker$onLoginSelected$1.invoke(LoginPicker.kt:3)
    at androidx.core.app.AppOpsManagerCompat.consumePromptFrom(AppOpsManagerCompat.java:5)
    at androidx.core.app.AppOpsManagerCompat.consumePromptFrom$default(AppOpsManagerCompat.java:1)
    at mozilla.components.feature.prompts.login.LoginPicker.onLoginSelected(LoginPicker.kt:1)
    at mozilla.components.feature.prompts.login.LoginSelectBar$listAdapter$1.invoke(LoginSelectBar.kt:3)
    at mozilla.components.feature.prompts.login.LoginViewHolder.onClick(BasicLoginAdapter.kt:1)
    at android.view.View.performClick(View.java:6615)
    at android.view.View.performClickInternal(View.java:6587)
    at android.view.View.access$3500(View.java:784)
    at android.view.View$PerformClick.run(View.java:26047)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6854)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
```

### PR DESCRIPTION
**Pull request by Amejia481**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt [hunk 1]
```diff
@@ -82,7 +82,9 @@ internal class GeckoPromptDelegate(private val geckoEngineSession: GeckoEngineSe
     ): GeckoResult<PromptResponse>? {
         val geckoResult = GeckoResult<PromptResponse>()
         val onConfirmSave: (Login) -> Unit = { login ->
-            geckoResult.complete(prompt.confirm(Autocomplete.LoginSelectOption(login.toLoginEntry())))
+            prompt.runIfNotCompleted {
+                geckoResult.complete(prompt.confirm(Autocomplete.LoginSelectOption(login.toLoginEntry())))
+            }
```
Comment (pocmo) [inline components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt:87]: I'm not sure if this helper is helping much? 🤔 

Without it, this line would be:

```Kotlin
if (!prompt.isComplete) {
   // ...
}
```

It's as long and isn't it easier to understand instead of a new function? 🤔

Comment (Amejia481) [reply components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt:87]: Agree, it helps a bit for testing purpose as we only have to test the logic in one place, maybe we should be testing that individually.

Comment (Amejia481) [reply components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt:87]: I updated the pr :)

**Review by pocmo — APPROVED** [review]
