### PR TITLE
Closes #9073 remove unwanted dots in the file name

### LINKED ISSUE #9073: Remove any additianal dot from filename
In Android 10, we are getting a crash when we try to add a download with a file name that contains multiple dots like (file..txt) to the download System Database, let's sanitize the file name and avoid this issue, for more info see the related Fenix issue https://github.com/mozilla-mobile/fenix/issues/16443

### PR DESCRIPTION
**Pull request by Amejia481**
In Android 10, we are getting a crash when we try to add a download with a file name that contains multiple dots like (file..txt) to the download System Database, let's sanitize the file name and avoid this issue, for more info see the related Fenix issue https://github.com/mozilla-mobile/fenix/issues/16443

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/String.kt [hunk 1]
```diff
@@ -146,7 +146,11 @@ fun String.sanitizeURL(): String {
  * For example for an input of "/../../../../../../directory/file.txt" you will get "file.txt"
  */
 fun String.sanitizeFileName(): String {
-    return this.substringAfterLast(File.separatorChar)
+    val file = File(this.substringAfterLast(File.separatorChar))
+    // Remove unwanted dots in the file name.
+    val name = file.nameWithoutExtension.replace(".", "")
```
Comment (csadilek) [inline components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/String.kt:151]: This will work but I am wondering if we should support file names like `test.2020.12.01.txt`. They would currently come out as `test20201201.txt`. I assume only subsequent "." are a problem, not multiple indiviudal "." in a name which should be fine.

If we want to support this you could change this to just:
```
val file = File(this.substringAfterLast(File.separatorChar))
return file.name.replace("\\.\\.+".toRegex(), ".")
```

To replace 2 or more "." with one, instead of clearing them all.

**Review by csadilek — APPROVED** [review]
This will work, but added a suggestion below to consider.

File: components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/String.kt (hunk 1 above)
Comment (Amejia481) [reply components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/String.kt:151]: Thanks for the feedback, sounds fair, I will do some test to see if it doesn't crash :)

Comment (Amejia481) [reply components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/String.kt:151]: Confirmed the issue is only with subsequent dots, I will add this part!

Comment (Amejia481) [reply components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/String.kt]: I added some additional checks, for cases like `file.` desktop returns `file`, also hidden files `.file` desktop returns `file` and I added the `sanitizeFileName` to `onExternalResponse` on the engine session to have the first prompt to display right file name, from a input of `test.......txt` it displays:
 
image

Comment (Amejia481) [reply components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/String.kt]: I also file https://github.com/mozilla-mobile/android-components/issues/9085 as a discovered that `DownloadUtils.guessFileName` is not working properly for hidden files `.file`, let me know if you want to take a second look on the pr :)

File: components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/String.kt [hunk 2]
```diff
@@ -146,7 +146,13 @@ fun String.sanitizeURL(): String {
  * For example for an input of "/../../../../../../directory/file.txt" you will get "file.txt"
  */
 fun String.sanitizeFileName(): String {
-    return this.substringAfterLast(File.separatorChar)
+    val file = File(this.substringAfterLast(File.separatorChar))
+    // Remove unwanted subsequent dots in the file name.
+    return if (file.extension.trim().isNotEmpty()) {
+        file.name.replace("\\.\\.+".toRegex(), ".")
+    } else {
+        file.name.replace("\\.\\.?+".toRegex(), "")
```
Comment (csadilek) [inline components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/String.kt:154]: Adding as we talked about this and I will forget :). Here we should just be able to do `replace(".", "")` and then we also don't need the `removePrefix` below.

**Review by csadilek — APPROVED** [review]

**Comment by Amejia481** [comment]
Thanks!
