### PR TITLE
Closes #6481: Introduce api to partially update the AddonsManagerAdapter

### LINKED ISSUE #6481: [Bug] Add-on icons flicker after add-on is installed
**Steps to reproduce:**
1. Go to Settings - Add-ons
2. Install NoScript add-on and observe the icons of all the add-ons

**Expected behavior**
An animation is displayed while the icons are loading.

**Actual behavior**
The animation flickers upon installing NoScript

**Device information**
- Android devices: Samsung Galaxy S7 Edge (Android 8.0.0)
- Fenix version: 3/26 Nightly build

fenix flicker

### PR DESCRIPTION
**Pull request by Amejia481**
I noticed that we were updating the add-on list multiple times, in this pr I'm adding APIs to just update partially the list, just the parts that had changed, see the Fenix pr https://github.com/mozilla-mobile/fenix/pull/10086 this pr could also fix https://github.com/mozilla-mobile/android-components/issues/6484

Before adding any tests, I would like to see what do you think of this approach.   

[Fenix Before](https://drive.google.com/file/d/1Mg7XJTFTIaP_qG5ZKvmUvWtNWdVnlMPj/view?usp=sharing)
[Fenix Now](https://drive.google.com/file/d/1lDANVgMAt5yETkYj3MROhj6hVWBosx3N/view?usp=sharing) 

---

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt [hunk 1]
```diff
@@ -339,6 +349,32 @@ class AddonsManagerAdapter(
...
+        addonsMap[addon.id] = addon
+        submitList(createListWithSections(addonsMap.values.toList()))
+    }
+
+    fun refresh(addons: List<Addon>){
+        addonsMap = addons.associateBy({ it.id }, { it }).toMutableMap()
+        submitList(createListWithSections(addons))
+    }
+
+    private object DifferCallback : DiffUtil.ItemCallback<Any>() {
```
Comment (Amejia481) [inline components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt:363]: This help us to create a diff of between the current list and the list that we want to update.

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt [hunk 2]
```diff
@@ -231,10 +231,20 @@ class AddonsManagerAdapter(
     internal fun fetchIcon(addon: Addon, iconView: ImageView, scope: CoroutineScope = this.scope): Job {
         return scope.launch {
             try {
+                // We calculate how much time takes to fetch an icon,
+                // if takes less than a second, we assume it comes
+                // from a cache and we don't show any transition animation.
+                val startTime = System.currentTimeMillis()
```
Comment (Amejia481) [inline components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt:237]: I could find a better way to identify if icon comes from a cache, if you have any alternative please let me know  :)

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt [hunk 3]
```diff
@@ -339,6 +349,40 @@ class AddonsManagerAdapter(
...
+        submitList(createListWithSections(addonsMap.values.toList()))
+    }
+
+    /**
+     * Refresh only the portion of the list that changes between the currentList and the new [addons].
+     * @property addons A list of add-on to replace the actual list.
+     */
+    fun refresh(addons: List<Addon>){
+        addonsMap = addons.associateBy({ it.id }, { it }).toMutableMap()
+        submitList(createListWithSections(addons))
```
Comment (Amejia481) [inline components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt:368]: As the list that we show to the users has multiple sections (**Recommended**, **installed**, **disabled**, **unsupported**), we need to re build a new list to diff it with the current list, because changes to the ad-ons can cause changes to the the sections, for example if we have 2 add-on and all of them are **Recommended**, if we install one the new list will have two new sections **installed**, and  **Recommended**. Now this is not an issue as the list is quite small, but when we have many +200 it could be an issue.

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt [hunk 4]
```diff
@@ -259,7 +269,7 @@ class AddonsManagerAdapter(
 
         addons.forEach { addon ->
             when {
-                addon.inUnsupportedSection() -> unsupportedAddons.add(addon)
+                addon.inUnsupportedSection() && !unsupportedAddons.contains(addon) -> unsupportedAddons.add(addon)
```
Comment (csadilek) [inline components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt:272]: Why do we need that additional guard? How come we add the same addon twice to unsupported addons? If we need to guard for this I would change this to a `Set`,

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt (hunk 2 above)
Comment (csadilek) [reply components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt:237]: Heh, interesting solution to prevent the flickering if the icon comes in later / too late!

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt [hunk 5]
```diff
@@ -339,6 +349,40 @@ class AddonsManagerAdapter(
...
+        addonsMap[addon.id] = addon
+        submitList(createListWithSections(addonsMap.values.toList()))
+    }
+
+    /**
+     * Refresh only the portion of the list that changes between the currentList and the new [addons].
+     * @property addons A list of add-on to replace the actual list.
+     */
+    fun refresh(addons: List<Addon>){
+        addonsMap = addons.associateBy({ it.id }, { it }).toMutableMap()
```
Comment (csadilek) [inline components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt:367]: I don't understand why you need the `addonsMap` here. You don't seem to be reading from it in this case?

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt (hunk 4 above)
Comment (Amejia481) [reply components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt:272]: As [unsupportedAddons](https://github.com/mozilla-mobile/android-components/blob/b25f0bf55a32888632be7186796342c1adbe4e0f/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt#L62) is global,  calling `createListWithSections` causes the side effect of adding multiple times to `unsupportedAddons`. Yes a `Set` could be a good alternative!

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt (hunk 5 above)
Comment (Amejia481) [reply components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt:367]: It's for keeping  `addonsMap` in sync with the latest changes for futures calls to` refresh(addon: Addon) `

Comment (Amejia481) [reply components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt:367]: Using a map offers faster lockups for when consumers want to just update one add-on (`refresh(addon: Addon)`), if I use a list every time that we want to update one add-on, we need to call `indexOf` and then alter the add-on.

```kotlin
    fun refresh(addon: Addon){
        val index = addonList.indexOf(addon)
        addonList[index] = addon
        submitList(createListWithSections(addonList))
    } 
```

Comment (csadilek) [reply components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt:367]: Sure, but that's not what I meant :). Maybe the kdocs aren't correct then. `Refresh only the portion of the list that changes between the currentList and the new [addons].` -> The second method that accepts a list refreshes everything, right? Not just the delta / that's what I was trying to find here?

Comment (csadilek) [reply components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt:367]: In other words, this more of a `refreshAll` function, right? Because if the you only pass in a subset of the add-ons to refresh and you're saving to a new `this.addonsMap`, it would then only have the ones you refreshed, not the entire "list". That's the part I wasn't sure about how you intended this to work.

Comment (Amejia481) [reply components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt:367]: Maybe I should call it `updateData(addon: Addon)` and `updateData(addons: List<Addon>)`, we have two things:

- **The data model** ->  `addonsMap` contains all the add-ons.
- **The visual representation** -> that is kept in the adapter internals, contains the headers + the add-on view items.

Every time, we call `refresh(addon: Addon)` or  `refresh(addons: List<Addon>)`.
`submitList` is calculating a diff and only applying changes to elements that have changed in the **visual representation**, but we don't know exactly what have changed in the **data model**, at least when calling `refresh(addons: List<Addon>)` for this reason I'm updating `addonsMap` with the data.

Comment (csadilek) [reply components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt:367]: Yeah, I think that's better! I would basically point that out in the kDocs that the list must contain all add-ons but the UI supports partial updates on only the add-ons that have changed.

Alternative: `updateAddon` and `updateAddons`.

File: components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt [hunk 6]
```diff
@@ -114,6 +117,43 @@ class AddonsManagerAdapterTest {
         }
     }
 
+    @Test
+    fun `fetching the add-on icon from cache MUST  animate`() {
```
Comment (csadilek) [inline components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt:121]: nit: extra space.

Comment (csadilek) [reply components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt:121]: nit: MUST NOT animate.

File: components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt [hunk 7]
```diff
@@ -114,6 +117,43 @@ class AddonsManagerAdapterTest {
...
+        runBlocking {
+            whenever(mockedCollectionProvider.getAddonIconBitmap(addon)).thenReturn(bitmap)
+
+            adapter.fetchIcon(addon, mockedImageView, scope).join()
+            verify(mockedImageView).setImageDrawable(any())
+        }
+    }
+
+    @Test
+    fun `fetching the add-on icon NON cache MUST animate`() {
```
Comment (csadilek) [inline components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt:137]: nit: uncached, without cache?

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt [hunk 8]
```diff
@@ -339,16 +351,56 @@ class AddonsManagerAdapter(
             }
         }
     }
+
+    /**
+     * Update the portion of the list that contains the provided [addon].
```
Comment (csadilek) [inline components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt:356]: nit: Updates

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt [hunk 9]
```diff
@@ -339,16 +351,56 @@ class AddonsManagerAdapter(
...
+     * @property addon The add-on to be updated.
+     */
+    fun updateAddon(addon: Addon) {
+        addonsMap[addon.id] = addon
+        submitList(createListWithSections(addonsMap.values.toList()))
+    }
+
+    /**
+     * Update only the portion of the list that changes between the current list and the new provided [addons].
```
Comment (csadilek) [inline components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt:365]: nit: Updates

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt [hunk 10]
```diff
@@ -339,16 +351,56 @@ class AddonsManagerAdapter(
...
+     * Be aware, updating a subset of the visible list is not supported, [addons] will replace
```
Comment (csadilek) [inline components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt:366]: nit: Be aware that updating...

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt [hunk 11]
```diff
@@ -339,16 +351,56 @@ class AddonsManagerAdapter(
...
+     * the current list, but only the add-ons that have been changed will be updated in the UI.
+     * if you provide a subset it will replace the current list.
```
Comment (csadilek) [inline components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt:368]: nit: If

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt [hunk 12]
```diff
@@ -339,16 +351,56 @@ class AddonsManagerAdapter(
...
+     */
+    fun updateAddon(addon: Addon) {
+        addonsMap[addon.id] = addon
+        submitList(createListWithSections(addonsMap.values.toList()))
+    }
+
+    /**
+     * Update only the portion of the list that changes between the current list and the new provided [addons].
+     * Be aware, updating a subset of the visible list is not supported, [addons] will replace
+     * the current list, but only the add-ons that have been changed will be updated in the UI.
```
Comment (csadilek) [inline components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt:367]: 👍

**Comment by Amejia481** [comment]
> Some nits and I am seeing crashes in the recyclerview when playing around with this. Still working on reliable STRs:
> 
> ```
>  Process: org.mozilla.samples.browser, PID: 11244
>     java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 8(offset:8).state:9 androidx.recyclerview.widget.RecyclerView{7bd695a VFED..... ......I. 0,0-1080,1868 #7f090047 app:id/add_ons_list}, adapter:mozilla.components.feature.addons.ui.AddonsManagerAdapter@6981780, layout:androidx.recyclerview.widget.LinearLayoutManager@2eb31b9, context:org.mozilla.samples.browser.addons.AddonsActivity@ff2b084
>         at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6183)
>         at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
>         at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
>         at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
>         at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
>         at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
>         at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
>         at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4085)
>         at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3849)
>         at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
>         at android.view.View.layout(View.java:22466)
>         at android.view.ViewGroup.layout(ViewGroup.java:6304)
>         at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
>         at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
>         at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
>         at android.view.View.layout(View.java:22466)
>         at android.view.ViewGroup.layout(ViewGroup.java:6304)
>         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
>         at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
>         at android.view.View.layout(View.java:22466)
>         at android.view.ViewGroup.layout(ViewGroup.java:6304)
>         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
>         at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
>         at android.view.View.layout(View.java:22466)
>         at android.view.ViewGroup.layout(ViewGroup.java:6304)
>         at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:446)
>         at android.view.View.layout(View.java:22466)
>      ...
> ```

Thanks, I will take a look at it!

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt [hunk 13]
```diff
@@ -56,14 +58,15 @@ class AddonsManagerAdapter(
     private val addonsManagerDelegate: AddonsManagerAdapterDelegate,
     addons: List<Addon>,
     private val style: Style? = null
-) : RecyclerView.Adapter<CustomViewHolder>() {
+) : ListAdapter<Any, CustomViewHolder>(DifferCallback) {
```
Comment (psymoon) [inline components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt:61]: ListAdapter<**Any**, CustomViewHolder>(DifferCallback) instead of `Addon` because of the sections, right? I remember doing something similar in the past without needing to declare generic type using DiffUtil 🤔

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt [hunk 14]
```diff
@@ -339,16 +351,56 @@ class AddonsManagerAdapter(
...
+     */
+    fun updateAddons(addons: List<Addon>) {
+        addonsMap = addons.associateBy({ it.id }, { it }).toMutableMap()
+        submitList(createListWithSections(addons))
+    }
+
+    private object DifferCallback : DiffUtil.ItemCallback<Any>() {
+        override fun areItemsTheSame(oldItem: Any, newItem: Any): Boolean {
+            return when {
+                oldItem is Addon && newItem is Addon -> oldItem.id == oldItem.id
```
Comment (psymoon) [inline components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt:379]: `oldItem.id == newItem.id`?

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt [hunk 15]
```diff
@@ -56,14 +58,15 @@ class AddonsManagerAdapter(
...
     private val style: Style? = null
-) : RecyclerView.Adapter<CustomViewHolder>() {
+) : ListAdapter<Any, CustomViewHolder>(DifferCallback) {
     private val scope = CoroutineScope(Dispatchers.IO)
-    private val items: List<Any>
-    private val unsupportedAddons = ArrayList<Addon>()
+    private val unsupportedAddons = mutableSetOf<Addon>()
     private val logger = Logger("AddonsManagerAdapter")
+    @VisibleForTesting
+    internal var addonsMap: MutableMap<String, Addon> = addons.associateBy({ it.id }, { it }).toMutableMap()
```
Comment (psymoon) [inline components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt:66]: What's the purpose of this map? Comment could be useful.

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt (hunk 14 above)
Comment (Amejia481) [reply components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt:379]: Thanks 🎉 
It maybe the source of the issue that @csadilek encountered

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt (hunk 15 above)
Comment (Amejia481) [reply components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt:66]: See https://github.com/mozilla-mobile/android-components/pull/6726#discussion_r412430175, agree a comment can help, I will added it.

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt (hunk 13 above)
Comment (Amejia481) [reply components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt:61]: Exactly, as we have three(Sections,add-ons and unsupported  add-ons section) types that can be pass but don't have any relations between each other.

**Comment by Amejia481** [comment]
bors r=csadilek,psymoon
