### PR TITLE
Closes #1182: Crash reporter prompt: Persist checkbox state

### LINKED ISSUE #1182: Crash reporter prompt: Persist checkbox state
I assume we want to persist the state of the checkbox ("[ ] Send crash report to Mozilla"). Currently it will always be [x] when showing the prompt.

### LINKED ISSUE #1215: Correct README.md file for ui-colors component dependency
In  [ui-colors component README.md file](https://github.com/mozilla-mobile/android-components/blob/master/components/ui/colors/README.md) the gradle dependency is incorrect.

WRONG ❌ 
`implementation "org.mozilla.photon:ui-colors:{latest-version}"`

Must be 🔵 
`implementation "org.mozilla.components:ui-colors:{latest-version}"`

### PR DESCRIPTION
**Pull request by Shubhamurkade**
Modified the file CrashResporterActivity.kt. The value of the send checkbox will be stored in a shared preference.

### CODE REVIEW

File: components/lib/crash/src/main/java/mozilla/components/lib/crash/prompt/CrashReporterActivity.kt [hunk 1]
```diff
@@ -23,6 +25,9 @@ import mozilla.components.lib.crash.R
 class CrashReporterActivity : AppCompatActivity() {
     private val crashReporter: CrashReporter by lazy { CrashReporter.requireInstance }
     private val crash: Crash by lazy { Crash.fromIntent(intent) }
+    private val sendCheckboxKey = "send_checkbox_value"
```
Comment (pocmo) [inline components/lib/crash/src/main/java/mozilla/components/lib/crash/prompt/CrashReporterActivity.kt]: this can be a constant above the class definition:

```Kotlin
private const val PREFERENCE_KEY_SEND_REPORT = "sendCrashReport"
```
```

File: components/lib/crash/src/main/java/mozilla/components/lib/crash/prompt/CrashReporterActivity.kt [hunk 2]
```diff
@@ -23,6 +25,9 @@ import mozilla.components.lib.crash.R
...
+    private lateinit var sharedPreferences: SharedPreferences
+    private val sendCheckboxFile = "mozac_lib_crash_settings.xml"
```
Comment (pocmo) [inline components/lib/crash/src/main/java/mozilla/components/lib/crash/prompt/CrashReporterActivity.kt]: nit: This can be a lazy property:

```Kotlin
private val sharedPreferences by lazy {
    getSharedPreferences("mozac_lib_crash_settings", Context.MODE_PRIVATE)
}
```

File: components/lib/crash/src/main/java/mozilla/components/lib/crash/prompt/CrashReporterActivity.kt [hunk 3]
```diff
@@ -72,6 +81,11 @@ class CrashReporterActivity : AppCompatActivity() {
     }
 
     private fun sendCrashReportIfNeeded(then: () -> Unit) {
+
+        /* Save the state of send checkbox into shared preferences.
+        */
```
Comment (pocmo) [inline components/lib/crash/src/main/java/mozilla/components/lib/crash/prompt/CrashReporterActivity.kt]: nit: I think we can get rid of this comment now. The following line is self explanatory :)

**Comment by pocmo** [comment]
After fixing the last issues, can you please rebase and squash this PR so that there's only a single commit? :)

File: components/lib/crash/src/main/java/mozilla/components/lib/crash/prompt/CrashReporterActivity.kt (hunk 2 above)
Comment (Shubhamurkade) [reply components/lib/crash/src/main/java/mozilla/components/lib/crash/prompt/CrashReporterActivity.kt]: Don't I need to add a separate variable for "mozac_lib_crash_settings" file?

**Comment by Shubhamurkade** [comment]
> After fixing the last issues, can you please rebase and squash this PR so that there's only a single commit

File: components/lib/crash/src/main/java/mozilla/components/lib/crash/prompt/CrashReporterActivity.kt (hunk 2 above)
Comment (pocmo) [reply components/lib/crash/src/main/java/mozilla/components/lib/crash/prompt/CrashReporterActivity.kt]: If it's just in this place then it may be fine.

If you want to you can create a const above the class though:

```Kotlin
private const val SETTINGS_FILE = "mozac_lib_crash_settings"
```

**Comment by Shubhamurkade** [comment]
I think I've screwed my branch during rebase. I'm new to VCS. Could you tell me what can I do about it? I thought deleting this branch and creating a new one would help. But, seems like it'll mess up more things

**Comment by Shubhamurkade** [comment]
> > After fixing the last issues, can you please rebase and squash this PR so that there's only a single commit? :)
> 
> Do I need another review after making the latest changes?

> I'm new to git. I've squashed the commits in my forked repository's branch. What do I need to do next?
