### PR TITLE
Close #9427: Fix intermittent failing test in CustomTabIntentProcessor

### LINKED ISSUE #9427: Intermittent UI test failure - processCustomTabIntentWithAdditionalHeaders mozilla.components.feature.customtabs.CustomTabIntentProcessorTest.processCustomTabIntentWithAdditionalHeaders: sdk=28; resources=binary
Log: https://treeherder.mozilla.org/logviewer?job_id=326854161&repo=android-components

### PR DESCRIPTION
**Pull request by jonalmeida**
Closes #9427 

Ran the test ~4000 times, it fails around 100-300 re-runs without this PR.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Review by Amejia481 — APPROVED** [review]

File: components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabIntentProcessorTest.kt [hunk 1]
```diff
@@ -150,6 +151,7 @@ class CustomTabIntentProcessorTest {
         val sessionCaptor = argumentCaptor<Session>()
         verify(sessionManager).add(sessionCaptor.capture(), eq(false), eq(null), eq(null), eq(null))
 
+        store.waitUntilIdle()
```
Comment (csadilek) [inline components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabIntentProcessorTest.kt:154]: @jonalmeida If we need this here, we should add it to the other tests as well before we call `assertFirstAction`?

**Review by csadilek — CHANGES_REQUESTED** [review]

File: components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabIntentProcessorTest.kt (hunk 1 above)
Comment (csadilek) [reply components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabIntentProcessorTest.kt:154]: Since the follow the same pattern `.process(intent)`, `sessionManager.add()`, then `assertFirstAction`.

Comment (jonalmeida) [reply components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabIntentProcessorTest.kt:154]: Good catch! I was running the tests together without failure, but when I ran them individually I reached the same failure in all of them.

**Review by csadilek — APPROVED** [review]

**Comment by jonalmeida** [comment]
```
[task 2021-01-19T15:01:37.012Z] * What went wrong:
[task 2021-01-19T15:01:37.012Z] Execution failed for task ':browser-engine-gecko-beta:packageDebugAndroidTest'.
[task 2021-01-19T15:01:37.012Z] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[task 2021-01-19T15:01:37.012Z]    > java.lang.OutOfMemoryError (no error message)
[task 2021-01-19T15:01:37.012Z] 
```
