### PR TITLE
Closes #6263 Sanitize the exceptions sent by the SupportedAddonsChecker

### LINKED ISSUE #6263: Sanitize the exceptions sent by DefaultSupportedAddonsChecker
After putting in production the `DefaultSupportedAddonsChecker`, we have been getting a lot of [noise](https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/7510929/?query=is:unresolved) as we are reporting all the exceptions that happen while trying to check for new  supported add-ons. Let's just report only exceptions that are actionable for us.

### PR DESCRIPTION
**Pull request by Amejia481**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt [hunk 1]
```diff
@@ -80,7 +82,7 @@ class DefaultSupportedAddonsChecker(
     override fun registerForChecks() {
         WorkManager.getInstance(applicationContext).enqueueUniquePeriodicWork(
                 CHECKER_UNIQUE_PERIODIC_WORK_NAME,
-                ExistingPeriodicWorkPolicy.KEEP,
+                ExistingPeriodicWorkPolicy.REPLACE,
```
Comment (Amejia481) [inline components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt]: We need this to change how often the worker will run [see](https://developer.android.com/reference/androidx/work/ExistingPeriodicWorkPolicy). If we don't add it, the old constraints will be maintained when consumers (Fenix) change frequency of the worker.

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt [hunk 2]
```diff
@@ -160,7 +162,9 @@ internal class SupportedAddonsWorker(
             }
         } catch (exception: Exception) {
             logger.error("An exception happened trying to check for new supported add-ons, re-schedule ${exception.message}", exception)
-            GlobalAddonDependencyProvider.onCrash?.invoke(exception)
+            if (!exception.isNoise()) {
```
Comment (csadilek) [inline components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt]: Let's just add another catch block to handle `IOException`s first. Let's have the type system do this for you. `SocketTimeOutException`s is an IO exception too. So, we don't need this extensions method.

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt (hunk 1 above)
Comment (csadilek) [reply components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt]: 👍

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt (hunk 2 above)
Comment (Amejia481) [reply components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt]: 👍

Comment (Amejia481) [reply components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt]: It will be very convenient to just add an additional catch block, but unfortunately we are wrapping all exceptions that come from [getAddons as AddonManagerException](https://github.com/mozilla-mobile/android-components/blob/e8e4806526aeb895a69e003c7917d3c0ceb986a2/components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt#L100), as result we need to unwrap them using `exception.cause`

Comment (csadilek) [reply components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt]: Ah, I missed that! OK, maybe just call it `exception.shouldReport()`?

File: components/feature/addons/src/test/java/mozilla/components/feature/addons/migration/SupportedAddonsWorkerTest.kt [hunk 3]
```diff
@@ -92,6 +96,33 @@ class SupportedAddonsWorkerTest {
         }
     }
 
+    @Test
+    fun `doWork - will NOT pass any IOException or SocketTimeoutException  exceptions to the crashReporter`() {
```
Comment (csadilek) [inline components/feature/addons/src/test/java/mozilla/components/feature/addons/migration/SupportedAddonsWorkerTest.kt]: nit: extra space.

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt (hunk 2 above)
Comment (Amejia481) [reply components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt]: Sounds good! :)

**Comment by Amejia481** [comment]
bors r=csadilek
