### PR TITLE
Closes #156: Gecko crashes when activity/app is paused and resumed

### LINKED ISSUE #156: Gecko crashes when activity/app is paused and resumed
This can happen in two different ways:
  - `setSession` is called with the same session which causes an exception
  - `GeckoRuntime.create` is called when the runtime is already initialized which also causes an exception

### PR DESCRIPTION
**Pull request by csadilek**
- Added check to not set session to the same value.
- Switched to `GeckoRuntime.getDefault` for now which includes a check to not initialize if already initialized.

### CODE REVIEW

File: samples/browser/src/main/java/org/mozilla/samples/browser/Components.kt [hunk 1]
```diff
@@ -17,9 +17,9 @@ import org.mozilla.geckoview.GeckoRuntime
 /**
  * Helper class for lazily instantiating components needed by the application.
  */
-class Components(private val applcationContext: Context) {
+class Components(private val applicationContext: Context) {
     private val geckoRuntime by lazy {
-        GeckoRuntime.create(applcationContext)
+        GeckoRuntime.getDefault(applicationContext)
```
Comment (pocmo) [inline samples/browser/src/main/java/org/mozilla/samples/browser/Components.kt]: That's one option. In Fenix I initialize the Components object from the application object instead from the activity which can be re-created multiple times during the process lifetime.

Comment (csadilek) [reply samples/browser/src/main/java/org/mozilla/samples/browser/Components.kt]: Yes, let's address this one separately. I have more thoughts here after debugging #157, that I'd like to share with you.
