### PR TITLE
Closes #5189: Make sure compositor is ready before capturing pixels

### LINKED ISSUE #5189: IllegalStateException: Compositor must be ready before pixels can be captured
Sentry for R-B, but I can actually reproduce when switching tabs in sample browser, but only in debug mode (looks like a race condition):

https://sentry.prod.mozaws.net/operations/reference-browser/issues/6753816/

```
java.lang.IllegalStateException: Compositor must be ready before pixels can be captured
    at org.mozilla.geckoview.GeckoDisplay$ScreenshotBuilder.capture(GeckoDisplay.java:321)
    at org.mozilla.geckoview.GeckoDisplay.capturePixels(GeckoDisplay.java:181)
    at org.mozilla.geckoview.GeckoView$Display.capturePixels(GeckoView.java:216)
    at org.mozilla.geckoview.GeckoView.capturePixels(GeckoView.java:828)
    at mozilla.components.browser.engine.gecko.GeckoEngineView.captureThumbnail(GeckoEngineView.kt:149)
    at mozilla.components.feature.session.ThumbnailsFeature.requestScreenshot(ThumbnailsFeature.kt:60)
    at mozilla.components.feature.session.ThumbnailsFeature.access$requestScreenshot(ThumbnailsFeature.kt:25)
    at mozilla.components.feature.session.ThumbnailsFeature$ThumbnailsFeatureRequestObserver.onLoadingStateChanged(ThumbnailsFeature.kt:53)
    at mozilla.components.browser.session.Session$$special$$inlined$observable$4$lambda$1.invoke(Session.kt:212)
    at mozilla.components.browser.session.Session$$special$$inlined$observable$4$lambda$1.invoke(Session.kt:51)
    at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:137)
    at mozilla.components.browser.session.Session.notifyObservers
    at mozilla.components.browser.session.Session.notifyObservers(Session.kt:511)
    at mozilla.components.browser.session.Session.access$notifyObservers(Session.kt:51)
    at mozilla.components.browser.session.Session$$special$$inlined$observable$4.afterChange(Delegates.kt:71)
    at kotlin.properties.ObservableProperty.setValue(ObservableProperty.kt:41)
    at mozilla.components.browser.session.Session.setLoading
    at mozilla.components.browser.session.engine.EngineObserver.onLoadingStateChange(EngineObserver.kt:99)
    at mozilla.components.browser.engine.gecko.GeckoEngineSession$createProgressDelegate$1$onPageStop$1.invoke(GeckoEngineSession.kt:459)
    at mozilla.components.browser.engine.gecko.GeckoEngineSession$createProgressDelegate$1$onPageStop$1.invoke(GeckoEngineSession.kt:425)
    at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:137)
    at mozilla.components.concept.engine.EngineSession.notifyObservers
    at mozilla.components.browser.engine.gecko.GeckoEngineSession$createProgressDelegate$1.onPageStop(GeckoEngineSession.kt:457)
    at org.mozilla.geckoview.GeckoSession$5.handleMessage(GeckoSession.java:689)
    at org.mozilla.geckoview.GeckoSession$5.handleMessage(GeckoSession.java:678)
    at org.mozilla.geckoview.GeckoSessionHandler.handleMessage(GeckoSessionHandler.java:90)
    at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:373)
    at android.os.Handler.handleCallback(Handler.java:789)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6644)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

### PR DESCRIPTION
**Pull request by csadilek**
GeckoView used to return a `GeckoResult.fromException` when the compositor wasn't ready which we ignored (and tried again later). It recently started throwing the exception instead: https://hg.mozilla.org/integration/autoland/rev/2a8ed7fb920c#l11.59

We now need to either ignore the exception or better check if the session ever had a "contenfulPaint". That's also what FxR does: https://github.com/MozillaReality/FirefoxReality/blob/master/app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java#L472

So, we only capture the pixels now if content was ever rendered for the session.

### CODE REVIEW

File: components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt [hunk 1]
```diff
@@ -65,6 +65,7 @@ class GeckoEngineSession(
     internal lateinit var geckoSession: GeckoSession
     internal var currentUrl: String? = null
     internal var scrollY: Int = 0
+    internal var firstContentfulPaint = false
```
Comment (Amejia481) [inline components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt]: nit: Maybe we could improve the name to something like`canCaptureThumbnails` or something else that is more descriptive ?

Comment (csadilek) [reply components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt]: Hm I don't want to change the name as it's from GV and not specific to capturing thumbnails. So, I've added a description instead.

Comment (Amejia481) [reply components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt]: 👍

**Comment by csadilek** [comment]
bors r=Amejia481
