### PR TITLE
Closes #8242: Keep latest breadcrumbs

### LINKED ISSUE #8242: Keep latest breadcrumbs
Currently we keep the highest priority breadcrumbs.  However, this does not work well.  Update to keep the latest breadcrumbs.  Also increase maximum breadcrumbs to 30 to allow more breadcrumbs to be recorded.

### PR DESCRIPTION
**Pull request by rocketsroger**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by rocketsroger** [comment]
Sample crash report with max set to 5 and higher priority breadcrumbs added first. https://sentry.prod.mozaws.net/operations/reference-browser/issues/9471214/events/50825328/

File: components/lib/crash/src/test/java/mozilla/components/lib/crash/BreadcrumbPriorityQueueTest.kt [hunk 1]
```diff
@@ -33,49 +33,41 @@ class BreadcrumbPriorityQueueTest {
...
-            )
-        }
-        assertEquals(crashBreadcrumbs.size, maxNum)
-
-        repeat(maxNum) {
-            crashBreadcrumbs.add(
-                    Breadcrumb(testMessage, testData, testCategory, Breadcrumb.Level.INFO, testType)
+                Breadcrumb(testMessage, testData, testCategory, Breadcrumb.Level.CRITICAL, testType)
             )
+            sleep(10) /* make sure time elapsed */
```
Comment (pocmo) [inline components/lib/crash/src/test/java/mozilla/components/lib/crash/BreadcrumbPriorityQueueTest.kt:48]: Ideally we'd mock the time to not actually slow down our tests. But it's not much, so probably fine to land.

File: components/support/base/src/main/java/mozilla/components/support/base/crash/Breadcrumb.kt [hunk 2]
```diff
@@ -103,11 +103,7 @@ data class Breadcrumb(
     }
 
     override fun compareTo(other: Breadcrumb): Int {
-        if (this.level.ordinal == other.level.ordinal) {
-            return this.date.compareTo(other.date)
-        }
-
-        return this.level.ordinal.compareTo(other.level.ordinal)
+        return this.date.compareTo(other.date)
```
Comment (pocmo) [inline components/support/base/src/main/java/mozilla/components/support/base/crash/Breadcrumb.kt:106]: Alternatively we could stop using a `PriorityQueue` and add at the end and remove items over the limit from the front?

**Review by pocmo — APPROVED** [review]

File: components/support/base/src/main/java/mozilla/components/support/base/crash/Breadcrumb.kt (hunk 2 above)
Comment (rocketsroger) [reply components/support/base/src/main/java/mozilla/components/support/base/crash/Breadcrumb.kt:106]: That's true.  Originally we did this because we want to sort by priority.  But we don't need that anymore.  I'll update with a simpler implementation.

**Comment by rocketsroger** [comment]
Latest test report with max set to 5 https://sentry.prod.mozaws.net/operations/reference-browser/issues/9471214/events/50826970/

File: components/lib/crash/src/main/java/mozilla/components/lib/crash/BreadcrumbArrayList.kt [hunk 3]
```diff
@@ -0,0 +1,20 @@
...
+internal class BreadcrumbArrayList(
+    private val maxSize: Int
+) : ArrayList<Breadcrumb>() {
+    @Synchronized
+    override fun add(element: Breadcrumb): Boolean {
+        if (this.size >= maxSize) {
+            this.removeAt(0)
+        }
+
+        return super.add(element)
```
Comment (pocmo) [inline components/lib/crash/src/main/java/mozilla/components/lib/crash/BreadcrumbArrayList.kt:18]: Extending `ArrayList` may be overkill here, if we can have this add/remove call inside `CrashReporter`? :)

Technically calling things like `addAll()` on this separate class will not honor the limit.

**Review by pocmo — COMMENTED** [review]
👍

File: components/lib/crash/src/main/java/mozilla/components/lib/crash/BreadcrumbArrayList.kt (hunk 3 above)
Comment (rocketsroger) [reply components/lib/crash/src/main/java/mozilla/components/lib/crash/BreadcrumbArrayList.kt:18]: Agreed.  This is probably a overkill.  Sure, I'll move this into the `crashreporter`

**Comment by rocketsroger** [comment]
After refactored into `CrashReporter` https://sentry.prod.mozaws.net/operations/reference-browser/issues/9471214/events/50829827/

**Review by pocmo — APPROVED** [review]
bors r+
