### PR TITLE
Issue #2571: Add option to recover from crashed sessions...

### LINKED ISSUE #2571: Allow apps to recover crashed sessions by restoring last state
With #2569 and #2568 the app knows when a `Session` (tab) crashed. Since the state refactoring (#2497) we always have a reference to the last state. We can use that to allow the app to restore this last state after crash.

### PR DESCRIPTION
**Pull request by pocmo**
Closes #2571. This is the last piece for better crash handling support.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

File: components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt [hunk 1]
```diff
@@ -244,6 +244,11 @@ abstract class EngineSession(
      */
     abstract fun exitFullScreenMode()
 
+    /**
+     * Tries to recover from a crash by restoring the last know state.
+     */
+    abstract fun recoverFromCrash()
```
Comment (Amejia481) [inline components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt]: Question: As the comment implies  **Tries to recover**, that means that in some cases it won't be able to recover from a crash, should we indicate to the consumer when we are unable to recover like returning a Boolean? This way the consumer can handle the situation properly.

Comment (Amejia481) [reply components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt]: Or  `session.crashed` is the way to communicate it ?

File: components/feature/session/src/main/java/mozilla/components/feature/session/SessionUseCases.kt [hunk 2]
```diff
@@ -174,6 +174,20 @@ class SessionUseCases(
...
+     * Tries to recover from a crash by restoring the last know state.
+     */
+    class CrashRecoveryUseCase internal constructor(
+        private val sessionManager: SessionManager
+    ) {
+        fun invoke(session: Session) {
+            sessionManager.getOrCreateEngineSession(session)
+                .recoverFromCrash()
+
+            session.crashed = false
```
Comment (Amejia481) [inline components/feature/session/src/main/java/mozilla/components/feature/session/SessionUseCases.kt]: What happens when we are unable to recover? Are we communicating a wrong message?

File: components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt (hunk 1 above)
Comment (pocmo) [reply components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt]: We could return a `Boolean` indicating whether we had a state and whether we tried to restore that. I'll add that.

File: components/feature/session/src/main/java/mozilla/components/feature/session/SessionUseCases.kt (hunk 2 above)
Comment (pocmo) [reply components/feature/session/src/main/java/mozilla/components/feature/session/SessionUseCases.kt]: I'll add the `Boolean` above.

Here in this case we tried to recover and that's all we could do. This doesn't mean the Session was fully restored - but we handled the crash. And then Session is operational and you can continue to load sites.

File: components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt (hunk 1 above)
Comment (Amejia481) [reply components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt]: 👍

**Comment by pocmo** [comment]
PR updated. :)

File: components/feature/session/src/main/java/mozilla/components/feature/session/SessionUseCases.kt (hunk 2 above)
Comment (Amejia481) [reply components/feature/session/src/main/java/mozilla/components/feature/session/SessionUseCases.kt]: 👍

**Comment by Amejia481** [comment]
That was fast  "_"

**Comment by Amejia481** [comment]
Some errors on TC

```
> Task :browser-session:compileDebugUnitTestKotlin FAILED
e: /build/android-components/components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt: (36, 29): Object is not abstract and does not implement abstract base class member public abstract fun recoverFromCrash(): Boolean defined in mozilla.components.concept.engine.EngineSession
e: /build/android-components/components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt: (86, 29): Object is not abstract and does not implement abstract base class member public abstract fun recoverFromCrash(): Boolean defined in mozilla.components.concept.engine.EngineSession
e: /build/android-components/components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt: (125, 29): Object is not abstract and does not implement abstract base class member public abstract fun recoverFromCrash(): Boolean defined in mozilla.components.concept.engine.EngineSession
```

**Comment by pocmo** [comment]
Updated once more :)

**Comment by pocmo** [comment]
Ah, one more test in `concept-engine`.
