### PR TITLE
Close #6811: Add breadcrumbs for caught exceptions

### LINKED ISSUE #6811: Add breadcrumbs for caught exceptions
Currently caught exceptions does not submit breadcrumbs.  Add breadcrumbs to crash reports when it is a caught exception.

### LINKED ISSUE #6881: AbstractFetchDownloadService leaks IntentReceiver
```
2020-05-05 17:47:40.646 11531-11531/org.mozilla.samples.browser E/ActivityThread: Service org.mozilla.samples.browser.downloads.DownloadService has leaked IntentReceiver mozilla.components.feature.downloads.AbstractFetchDownloadService$broadcastReceiver$2$1@5531a95 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Service org.mozilla.samples.browser.downloads.DownloadService has leaked IntentReceiver mozilla.components.feature.downloads.AbstractFetchDownloadService$broadcastReceiver$2$1@5531a95 that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1588)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1368)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1515)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1488)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1476)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:627)
        at mozilla.components.feature.downloads.AbstractFetchDownloadService.registerForUpdates(AbstractFetchDownloadService.kt:352)
        at mozilla.components.feature.downloads.AbstractFetchDownloadService.onStartCommand(AbstractFetchDownloadService.kt:216)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4087)
        at android.app.ActivityThread.access$1800(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

### PR DESCRIPTION
**Pull request by rocketsroger**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt [hunk 1]
```diff
@@ -130,7 +130,7 @@ class CrashReporter(
 
         return scope.launch {
             services.forEach {
-                it.report(throwable)
+                it.report(throwable, crashBreadcrumbs.toSortedArrayList())
             }
```
Comment (pocmo) [inline components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt:134]: Since a manual report won't end the app/process: Wouldn't we add and report the same breadcrumbs multiple times if we submit multiple exceptions?
Do we need to somehow clear our list of breadcrumbs after they have been recorded once?

Comment (rocketsroger) [reply components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt:135]: I was back and forth about this.  At the end I decided we shouldn't clear it.  The main reason is if there is a uncaught exception that happens quickly after a caught exception, the breadcrumbs will still help debug the issue.  

I think keeping them is better since we can't be sure which breadcrumb belongs to which report.

Comment (pocmo) [reply components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt:134]: I worry that duplicated breadcrumbs may be misleading and confusing when looking for causes? But then again I guess this can only happen if we are in the same process and reusing the same Sentry instance?
What if we call `clearBreadcrumbs()` on Sentry itself after we reported a crash? This way we can keep them ourselves and re-add them the next time we report something?

Comment (rocketsroger) [reply components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt:134]: I see what you mean.  Make sense.  I'll update.  Thanks,

File: components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SentryService.kt [hunk 2]
```diff
@@ -88,19 +90,25 @@ class SentryService(
...
+        breadcrumbs.forEach {
+            client.context.recordBreadcrumb(it.toSentryBreadcrumb())
+        }
+
         val eventBuilder = EventBuilder().withMessage(createMessage(throwable))
                 .withLevel(Event.Level.INFO)
                 .withSentryInterface(ExceptionInterface(throwable))
 
         client.sendEvent(eventBuilder)
+        client.context.clearBreadcrumbs()
```
Comment (pocmo) [inline components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SentryService.kt:111]: 👍 

Can you double check the breadcrumbs still get out. Now I am afraid that Sentry will read them async later and by then we already have cleared them. 😅 Other than that 👍 👍 👍

Comment (rocketsroger) [reply components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SentryService.kt:111]: Confirmed breadcrumb are still being sent 👍

**Comment by rocketsroger** [comment]
bors r=pocmo
