### PR TITLE
Closes #6685 enable previously unsupported add-ons when available

### LINKED ISSUE #6685: [Bug]Previously installed Privacy Badger isn't enabled by default after migration, enabling it will send a notification on each app start
## Prerequisites
1. Have **Fennec Nightly** installed
2. Install Privacy Badger
3. Perform a migration to a Nightly Build with GV 76
4. Perform a migration to a Nightly Build with GV 77 (not the latest ❗ )
5. Perform a migration to the latest Nightly Build GV 77

## Steps to reproduce
1. Open Fenix 
2. Navigate to the Add-ons manager (check Privacy Badger's state)
3. If disabled, enable it and exit back to the Add-ons Manager
4. Open again Privacy Badger check the state
5. Close the app and re-open it

### Expected behavior
Step 1 -  An Add-on related notification should be displayed.
Step 2 - Privacy Badger should be enabled.
Step 4 - **The disable/enable state should remain set as per the user's choice**. 
Step 5 - **No Add-on related notification should be displayed again**

### Actual behavior
Step 2 - **Privacy Badger is disabled**
Step 3 & 4 - If you enable it, **each time you re-open Privacy Badger it get's enabled over and over again**
Step 5 - **The Add-on related notification is displayed each time the user opens the app** 

### Device information
* Android device: 
• Google Pixel 3a (Android 10)

* Fenix version: Nightly Build #21070609 from 4/16

## Notes
► Video

### PR DESCRIPTION
**Pull request by Amejia481**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt [hunk 1]
```diff
@@ -81,7 +84,7 @@ class DefaultSupportedAddonsChecker(
     override fun registerForChecks() {
         WorkManager.getInstance(applicationContext).enqueueUniquePeriodicWork(
                 CHECKER_UNIQUE_PERIODIC_WORK_NAME,
-                ExistingPeriodicWorkPolicy.REPLACE,
+                ExistingPeriodicWorkPolicy.KEEP,
```
Comment (Amejia481) [inline components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt:87]: This will prevent the worker from running multiple times see, now if we call this function again, it will keep the existing worker in the work manager databes https://developer.android.com/reference/androidx/work/ExistingPeriodicWorkPolicy#KEEP.

[Before we were deleting the exiting work and adding a new one](https://developer.android.com/reference/androidx/work/ExistingPeriodicWorkPolicy#REPLACE), as Fenix  executes `registerForChecks` every time the app starts, the conditions were met and we were executing the worker every time.

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt [hunk 2]
```diff
@@ -154,6 +157,12 @@ internal class SupportedAddonsWorker(
                 addon.isSupported() && addon.isDisabledAsUnsupported()
             }
 
+            withContext(Dispatchers.Main) {
+                newSupportedAddons.map {
```
Comment (csadilek) [inline components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt:161]: nit: Should use `forEach` as we're not doing anything with the result of `map`.

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt [hunk 3]
```diff
@@ -154,6 +157,12 @@ internal class SupportedAddonsWorker(
...
+                    addonManager.enableAddon(it, source = EnableSource.APP_SUPPORT)
```
Comment (csadilek) [inline components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt:162]: Let's pass an error callback and log to Sentry? This way we know if we failed to enable? Wdyt?

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt (hunk 2 above)
Comment (Amejia481) [reply components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt:161]: 👍

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt (hunk 3 above)
Comment (Amejia481) [reply components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt:162]: Agree!

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt [hunk 4]
```diff
@@ -177,11 +178,13 @@ class AddonManager(
      * Enables the provided [Addon].
      *
      * @param addon the [Addon] to enable.
+     * @param source [EnableSource] to indicate why the extension is enabled.
```
Comment (psymoon) [inline components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt:181]: nit: default to EnableSource.USER

Why is that the case? Just curious ..

Comment (Amejia481) [reply components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt]: Fixed :)
When we migrate add-ons we [disabled them with the source EnableSource.APP_SUPPORT](https://github.com/mozilla-mobile/android-components/blob/e796fa7408cd9affa6b38a3bfc07092d89bce2da/components/support/migration/src/main/java/mozilla/components/support/migration/AddonMigration.kt#L176), but users are unable to enable the newly supported add-on using source `EnableSource.USER` that's what   the engine uses by default causing this issue https://github.com/mozilla-mobile/fenix/issues/9994, for this reason, we need to enable the add-on using `EnableSource.USER` for users be able to enable/disable newly supported add-ons.

**Comment by Amejia481** [comment]
bors r=csadilek,psymoon
