### PR TITLE
Fixes #6094: Check if we are able to open url 

### LINKED ISSUE #6094: Crash on handling schemes other than http/https
Fenix issue/crash [here](https://github.com/mozilla-mobile/fenix/issues/8412).

The issue is that we are not handling other schemes than http and https. Basically if a user wants to access `blob:https://mega.nz/...` (like seen in a recent sentry report) the app would not know how to handle this and crash.

### PR DESCRIPTION
**Pull request by ValentinTimisica**
There are cases when a user opens url with scheme that we are not handling in
the app so we need to check if we can resolve them before opening.

---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks.
- [x] **Tests**: This PR includes thorough tests.
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md).
- [x] **Accessibility**: The code in this PR does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabWindowFeature.kt [hunk 1]
```diff
@@ -72,13 +73,23 @@ class CustomTabWindowFeature(
...
+                            handleError()
+                        }
                     }
                 }
         }
     }
 
+    @VisibleForTesting
+    internal fun canHandleIntent(customTabIntent: CustomTabsIntent): Boolean =
+        customTabIntent.intent.resolveActivity(activity.packageManager) != null
```
Comment (pocmo) [inline components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabWindowFeature.kt]: I _think_ `resolveActivity()` will also return activities that may have `exported=false` set and cannot actually be launched? We may need to call `resolveActivity()` on the `PackageManager` and check whether the returned `ActivityInfo` has the exported flag set.

File: components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabWindowFeature.kt [hunk 2]
```diff
@@ -72,13 +73,23 @@ class CustomTabWindowFeature(
                     val windowRequest = state.content.windowRequest
                     if (windowRequest?.type == WindowRequest.Type.OPEN) {
                         val intent = configToIntent(state.config)
-                        intent.launchUrl(activity, windowRequest.url.toUri())
-                        store.dispatch(ContentAction.ConsumeWindowRequestAction(sessionId))
+                        // Setting url for intent in order to check if we are able to open that url
+                        intent.intent.data = windowRequest.url.toUri()
+                        if (canHandleIntent(intent)) {
+                            intent.launchUrl(activity, windowRequest.url.toUri())
+                            store.dispatch(ContentAction.ConsumeWindowRequestAction(sessionId))
```
Comment (pocmo) [inline components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabWindowFeature.kt]: I assume we want to consume the window request in any case? 🤔

File: components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabWindowFeature.kt [hunk 3]
```diff
@@ -72,13 +73,23 @@ class CustomTabWindowFeature(
                     val windowRequest = state.content.windowRequest
                     if (windowRequest?.type == WindowRequest.Type.OPEN) {
                         val intent = configToIntent(state.config)
-                        intent.launchUrl(activity, windowRequest.url.toUri())
-                        store.dispatch(ContentAction.ConsumeWindowRequestAction(sessionId))
+                        // Setting url for intent in order to check if we are able to open that url
+                        intent.intent.data = windowRequest.url.toUri()
+                        if (canHandleIntent(intent)) {
+                            intent.launchUrl(activity, windowRequest.url.toUri())
```
Comment (pocmo) [inline components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabWindowFeature.kt]: nit: We are calling `windowRequest.url.toUri()` twice.

File: samples/browser/src/main/java/org/mozilla/samples/browser/ExternalAppBrowserFragment.kt [hunk 4]
```diff
@@ -68,7 +68,9 @@ class ExternalAppBrowserFragment : BaseBrowserFragment(), UserInteractionHandler
             requireActivity(),
             components.store,
             sessionId!!
-        )
+        ) {
+            // No-op. Client may override this
+        }
```
Comment (pocmo) [inline samples/browser/src/main/java/org/mozilla/samples/browser/ExternalAppBrowserFragment.kt]: Isn't that already the default behavior? Or do you just want to make this explicit here so that people reading the sample code will know about this?

Comment (ValentinTimisica) [reply samples/browser/src/main/java/org/mozilla/samples/browser/ExternalAppBrowserFragment.kt]: This piece of code is for a lambda parameter that I added and will be a breaking change for our clients who will now have to provide a specific behaviour for handling the error.

**Comment by ValentinTimisica** [comment]
Check comments from #6374.

File: components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabWindowFeature.kt [hunk 5]
```diff
@@ -76,17 +76,36 @@ class CustomTabWindowFeature(
...
+                        if (canHandleIntent(intent)) {
+                            intent.launchUrl(activity, url)
+                        } else {
+                            // We could only get here if the above intent is for our application
+                            // and we are not registered to handle its schemes.
+                            // Let's log this to better asses how often this happens in real world and
+                            // if we need to add new schemes to properly support this workflow.
+                            // See Fenix #8412
+                            try {
+                                intent.launchUrl(activity, url)
```
Comment (rocketsroger) [inline components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabWindowFeature.kt]: Looks like both `canHandleIntent(activity, url)` true and false case both calls `intent.launchUrl()`.  Why do the extra check?

File: components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabWindowFeature.kt [hunk 6]
```diff
@@ -33,7 +33,7 @@ class CustomTabWindowFeature(
     private val activity: Activity,
     private val store: BrowserStore,
     private val sessionId: String,
-    private val crashReporter: CrashReporter? = null
+    @VisibleForTesting internal val handleError: (Exception) -> Unit
```
Comment (rocketsroger) [inline components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabWindowFeature.kt]: I don't know if this is what we want as a fix.  This failure to handle the link/intent is an A-C issue.

Comment (ValentinTimisica) [reply components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabWindowFeature.kt]: I have found the issue and I have steps to reproduce in the Fenix issue - https://github.com/mozilla-mobile/fenix/issues/8412#issuecomment-592020541.

Seems like this is a Fenix issue and for fixing it we have to add new intent filter schemes.
Any touch on a link gets to AC which will try to open a client activity (in this case Fenix) and in our case Fenix doesn't know how to handle specific link schemes.

Because at the moment we can't easily add new intent filter schemes without a product decision the best we can do is:
1) Show a message to the user that his touch event on a specific link cannot be handled by the app (UX suggestion, you can check it here https://github.com/mozilla-mobile/fenix/pull/8903#issuecomment-595875216).
2) Log the error to our crashstats to better assess how many users are affected by this. (solution inspired by your patch).

Because the issue actually is in the AC client (it doesn't handle all schemes) AC will simply pass this error to the client and it will be its responsibility to handle this case. We on Fenix will use both of the above two solutions:
https://github.com/mozilla-mobile/fenix/blob/fdecc03b19b3f6b46874bafe14cb85fd278ee45a/app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserFragment.kt#L87

File: components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabWindowFeature.kt (hunk 5 above)
Comment (ValentinTimisica) [reply components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabWindowFeature.kt]: When `canHandleIntent` returns:
- true: 
We know that the client can open the link and we simply delegate it to do so.
- false:
We know that the client can't handle the link but we try to give to it a stacktrace with even more information about why the call to open the link failed.
In this case the `intent.launchUrl(activity, url)` it's clear that it will not actually open the url, but just throw an exception which we'll forward to the client.
To give a bit more context about this I wrote the comment above the `try-catch`.

Comment (rocketsroger) [reply components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabWindowFeature.kt]: I see.  But couldn't we (like the change I landed) just call `launchUrl` in the try catch and handle the error?

File: components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabWindowFeature.kt (hunk 6 above)
Comment (rocketsroger) [reply components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabWindowFeature.kt]: This is interesting.  I think this makes sense.

File: components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabWindowFeature.kt (hunk 5 above)
Comment (ValentinTimisica) [reply components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabWindowFeature.kt]: I just found it to be more clear and I already had the patch and tests for that scenario. I think the difference is minor.

Comment (rocketsroger) [reply components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabWindowFeature.kt]: Agreed.  I would preferred we go straight to try catch without the extra check.  Thanks,

Comment (ValentinTimisica) [reply components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabWindowFeature.kt]: Hello @rocketsroger, I agree with you that we should only keep the `try catch` without the extra check and I updated the PR accordingly. Thanks!

**Comment by rocketsroger** [comment]
> Looks good. Can you please squash the changes together?
> https://github.com/wprig/wprig/wiki/How-to-squash-commits

Looks clean enough.  Probably don't need to squash.  I'll approve.

**Comment by rocketsroger** [comment]
bors r=rocketsroger
