### PR TITLE
Close #7476: Persists lastAccess to SnapshotSerializer 

### LINKED ISSUE #7476: Add lastAccess property to SnapshotSerializer
We should try to serialize the last used property so that we don't wrongfully update the sync servers with incorrect timestamps on a cold-boot restore.

See original comment here: https://github.com/mozilla-mobile/android-components/pull/7277#issuecomment-644250888

### PR DESCRIPTION
**Pull request by jonalmeida**
---

Close #7476 

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/browser/session/src/main/java/mozilla/components/browser/session/engine/middleware/LastAccessMiddleware.kt [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+    override fun invoke(
+        context: MiddlewareContext<BrowserState, BrowserAction>,
+        next: (BrowserAction) -> Unit,
+        action: BrowserAction
+    ) {
+        if (action is TabListAction.SelectTabAction) {
+            context.dispatchUpdateActionForId(action.tabId)
+        } else if (action is TabListAction.AddTabAction && action.select) {
+            context.dispatchUpdateActionForId(action.tab.id)
+        }
```
Comment (pocmo) [inline components/browser/session/src/main/java/mozilla/components/browser/session/engine/middleware/LastAccessMiddleware.kt:28]: nit: Just a nit... should we first select/add (invoking `next`) and *then* update the time? Especially the "add tab" case. How does this work if you update before the tab is added?

File: components/browser/session/src/test/java/mozilla/components/browser/session/engine/middleware/LastAccessMiddlewareTest.kt [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+        val captor = argumentCaptor<TabSessionAction.UpdateLastAccessAction>()
+        val tab = createTab("https://mozilla.org", id = "456")
+
+        middleware.invoke(context, { nextInvoked = true }, TabListAction.AddTabAction(tab, true))
+
+        verify(store).dispatch(captor.capture())
+
+        assertEquals("456", captor.value.tabId)
+        assertTrue(captor.value.lastAccess != 0L)
+        assertTrue(nextInvoked)
```
Comment (pocmo) [inline components/browser/session/src/test/java/mozilla/components/browser/session/engine/middleware/LastAccessMiddlewareTest.kt:64]: See question above about updating the time before the tab is added. I'd recommend testing with an actual store instance, no need to mock that in test if you want to test a middleware.

File: components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt [hunk 3]
```diff
@@ -115,6 +115,22 @@ sealed class TabListAction : BrowserAction() {
     object RemoveAllNormalTabsAction : TabListAction()
 }
 
+/**
+ * [BrowserAction] implementations related to updating the [TabSessionState] inside [BrowserState].
+ */
+sealed class TabSessionAction : BrowserAction() {
```
Comment (pocmo) [inline components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt:121]: nit: TabSessionAction is very generic and may be confusing if there's nothing else in here? Others like `TrackingProtectionAction` are more specific. I fear that this action group may end up becoming a dumping ground. :)

Comment (jonalmeida) [reply components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt:121]: This was my fear as well. I was hesitant to put this under `TabListAction` since it wasn't acting on the list, and it didn't fit into `ContentAction` as well since it isn't content.

Maybe I should change the name to something else, like `TabSelectionAction`? 🤔

File: components/browser/session/src/main/java/mozilla/components/browser/session/engine/middleware/LastAccessMiddleware.kt (hunk 1 above)
Comment (jonalmeida) [reply components/browser/session/src/main/java/mozilla/components/browser/session/engine/middleware/LastAccessMiddleware.kt:28]: I haven't noticed any side-effects in my testing, but I think your suggestion makes a lot more sense than the current behaviour.

File: components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt (hunk 3 above)
Comment (csadilek) [reply components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt:121]: It's a bit of a special case, maybe just `LastAccessAction` and `UpdateLastAccessAction` to prevent from becoming a dumping ground?

**Comment by jonalmeida** [comment]
Thanks, I've addressed the comments and squash the changes into one!

**Comment by jonalmeida** [comment]
I'd like to re-run this PR after https://github.com/mozilla-mobile/android-components/pull/8268 lands. I'm certain I've broken some more tests since I've changed the behaviour from reverting the changes to `SelectTabAction` where we altered the tests when that change originally landed.

**Comment by jonalmeida** [comment]
The CI changes that I wanted to land first before landing this PR will [only happen on Monday](https://github.com/mozilla-mobile/android-components/pull/8268#pullrequestreview-477529803), which may be too late to get this into the next release in time.

My concern is that we may have broken tests in other components that depend on this change when [landing the original feature](https://github.com/mozilla-mobile/android-components/pull/7277) which we have not fixed correctly and CI may not run have run on them. My plan of action is to run all the component tests locally, correct them if needed, and only then merge this PR.

**Comment by jonalmeida** [comment]
From local testing the `ReaderViewFeatureTest` changes that were changed in the original PR needed to be changed. I think I'm more comfortable with landing this change now.

**Comment by jonalmeida** [comment]
bors r=csadilek
