### PR TITLE
Closes #7879 Provide an error message when non translation is found for an add-on field

### LINKED ISSUE #7879: AddonsManagerAdapter: Key zh-CN is missing in the map.
https://sentry.prod.mozaws.net/share/issue/835b3160fa0a4208a222fd163612c392/

```
java.util.NoSuchElementException: Key zh-CN is missing in the map.
    at kotlin.collections.GroupingKt.getValue
    at mozilla.components.feature.addons.ui.AddonsManagerAdapterKt.translate(AddonsManagerAdapter.kt:2)
    at org.mozilla.fenix.addons.AddonDetailsView.bind(AddonDetailsView.kt:2)
    at org.mozilla.fenix.addons.AddonDetailsFragment.onViewCreated(AddonDetailsFragment.kt:5)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:21)
    at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:25)
    at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:5)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:53)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:11)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:4)
    at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:1)
    at android.os.Handler.handleCallback(Handler.java:900)
    at android.os.Handler.dispatchMessage(Handler.java:103)
    at android.os.Looper.loop(Looper.java:219)
    at android.app.ActivityThread.main(ActivityThread.java:8347)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

### PR DESCRIPTION
**Pull request by Amejia481**
Fenix pr https://github.com/mozilla-mobile/fenix/pull/16190 waiting  for to https://github.com/mozilla-mobile/reference-browser/pull/1350 to put the RB pr

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/Extensions.kt [hunk 1]
```diff
@@ -57,9 +57,12 @@ val Addon.updatedAtDate: Date get() = dateParser.parse(updatedAt)!!
 /**
  * Try to find the default language on the map otherwise defaults to [Addon.DEFAULT_LOCALE].
  */
-internal fun Map<String, String>.translate(addon: Addon): String {
+internal fun Map<String, String>.translate(addon: Addon, context: Context): String {
     val lang = Locale.getDefault().language
-    return get(lang) ?: getValue(addon.defaultLocale)
+    return get(lang) ?: getOrElse(addon.defaultLocale) {
+        // No translation found $lang and not default
```
Comment (csadilek) [inline components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/Extensions.kt:63]: nit: not translation found for $lang and $addon.defaultLoca?

**Review by csadilek — APPROVED** [review]
🚢

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/Extensions.kt (hunk 1 above)
Comment (Amejia481) [reply components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/Extensions.kt:63]: The comment wasn't intentional was a leftover of our chat, I will remove it 😄
