### PR TITLE
Closes #7896: Change failure messages to not rely on Kotlin reflection

### LINKED ISSUE #7896: Some migration exception messages rely on Kotlin reflection
Just saw that we have a few error messages where we attempt to append the class name of the underlying exception using "text {e::class}".

This will be reported as "text (Kotlin reflection is not available)".

### PR DESCRIPTION
**Pull request by csadilek**
Another option would be to use the entire `toString` of the exception, instead of just the class name, but sticking to what we had so we don't expose anything by mistake.

The `Exception.uniqueId` extension function should also be affected by this so changed it here as well.

@grigoryk @pocmo Relatively minor, but maybe we want land this / fix it and cherry-pick on the branch for next round?

### CODE REVIEW

File: components/support/migration/src/main/java/mozilla/components/support/migration/Exception.kt [hunk 1]
```diff
@@ -10,5 +10,5 @@ package mozilla.components.support.migration
 fun Exception.uniqueId(): String {
     // In extreme cases, VM is allowed to return an empty stacktrace.
     val topStackFrameString = this.stackTrace.getOrNull(0)?.toString() ?: ""
-    return "${this::class.java.canonicalName} $topStackFrameString"
+    return "${this.javaClass.canonicalName} $topStackFrameString"
```
Comment (grigoryk) [inline components/support/migration/src/main/java/mozilla/components/support/migration/Exception.kt:13]: i guess this continues to work as designed, right?

Comment (csadilek) [reply components/support/migration/src/main/java/mozilla/components/support/migration/Exception.kt:13]: @grigoryk yeah, it does, but there's also no need to change that here as the original works fine. I will remove.

Comment (grigoryk) [reply components/support/migration/src/main/java/mozilla/components/support/migration/Exception.kt:13]: Does the original not rely on the reflection lib? it _looks_ like it does

Comment (csadilek) [reply components/support/migration/src/main/java/mozilla/components/support/migration/Exception.kt]: Yeah, it's deceiving but the original actually works, I think `this::class.java` is equivalent to `this.javaClass`.

**Comment by csadilek** [comment]
Updated this now to use the exception's `toString`, rather than just the class name. This should give us some more information too.

**Comment by grigoryk** [comment]
🚢 🇮🇹 

bors r+

**Comment by csadilek** [comment]
Fixed the tests, but let's take another look tomorrow. Need rest :).

**Comment by csadilek** [comment]
bors r=pocmo,grigoryk

**Comment by csadilek** [comment]
@pocmo Should I cherry-pick this on the release branches or wait / label somehow?

**Comment by pocmo** [comment]
Yeah, that seems not risky to uplift :)

**Comment by pocmo** [comment]
Uplifted to 52.0.
