### PR TITLE
Closes #383 and #392: FxA fixes / refactorings.

### LINKED ISSUE #383: Refactor FxA method names to use Java/Kotlin convention (camelCase not snake_case)

### PR DESCRIPTION
**Pull request by csadilek**
First of many refactorings :).

This is to hide the snake_case Rust method wrappers from our public API. There's no value in having the app call `init`. If a project adds the library to the classpath, but doesn't use it, the FxaClient class won't be loaded and therefore not initialized. So, there's no need for extra control.

### CODE REVIEW

File: components/service/fxa/src/main/java/mozilla/components/service/fxa/RustObject.kt [hunk 1]
```diff
@@ -29,7 +29,7 @@ abstract class RustObject<T> : Closeable {
         return p
     }
 
-    protected abstract fun destroyPointer(p: T)
+    abstract fun destroyPointer(p: T)
```
Comment (csadilek) [inline components/service/fxa/src/main/java/mozilla/components/service/fxa/RustObject.kt]: This shouldn't be protected. It's currently called from a finalizer, which needs to be fixed as well: #396

**Comment by csadilek** [comment]
I am adding another commit to address #396.
