### PR TITLE
Closes #6855: Do not use unsupportedAddon as global value

### LINKED ISSUE #6855: Fennec migration: List of unavailable add-ons is not refreshed
## Preconditions:
Have unavailable add-ons for Fenix Beta added to Fennec Beta.
## Steps to reproduce
1. Replace Fennec Beta with Fenix Beta;
2. Launch Fenix and go to the Add-ons list;
3. Scroll to the end of the list and tap the "Not yet available" section;
4. Delete one add-on from the list and tap the back button;
5. Tap the "Not yet available" and observe add-ons from the list; 
### Expected behavior
The deleted add-on is not displayed in the list.
### Actual behavior
The deleted add-on is displayed in the list and cannot be deleted, the "Failed to remove" pop-up message is displayed.
### Notes:
[Video](https://drive.google.com/open?id=1A81so8pvA8NIgBpm6OxGvc7KwaZ3zCKD)
The list is refreshed after leaving the Add-ons list and then going back.
### Device information

* Android device: Nexus 5 (Android 6.0.1); Motorola Moto G6 (Android 8), Huawei MediaPad M3 lite (Android 7).
* Fenix version: Beta migration build 76.0.0-beta.1 from 5/1.

A similar issue was filed by @csadilek in https://github.com/mozilla-mobile/android-components/issues/5815, that is fixed.

### PR DESCRIPTION
**Pull request by Amejia481**
As we updated the `AddonsManagerAdapter` for doing partial updates, we kept the `unsupportedAddon` list as a global value, this caused when we deleted items from it the list wasn't updated properly. Instead of using the `unsupportedAddon` list now we are querying `addonsMap` as now is our source of truth.

---

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt [hunk 1]
```diff
@@ -167,6 +166,7 @@ class AddonsManagerAdapter(
         holder: UnsupportedSectionViewHolder,
         section: NotYetSupportedSection
     ) {
+        val unsupportedAddons = addonsMap.values.filter { it.inUnsupportedSection() }
```
Comment (psymoon) [inline components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt:169]: nit: maybe add test for when we are creating sections, we have the correct unsupportedAddons list?

Comment (Amejia481) [reply components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt:169]: We have already have one :)
https://github.com/mozilla-mobile/android-components/blob/01cfc5e581678fe6ed9700c5872711cd2967eeda/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt#L58

**Comment by Amejia481** [comment]
bors r=psymoon
