### PR TITLE
Closes #6171: Simplify push error handling; reduce non-fatal reporting

### LINKED ISSUE #6171: Add better error vs info logging for non-fatal push exceptions
Related to https://github.com/mozilla-mobile/android-components/issues/5691, we don't need to log exceptions that are device network connectivity issues to our CrashReporter.

We need a better way to filter the valuable ones from the non-fatal.

### PR DESCRIPTION
**Pull request by jonalmeida**
Based on the our crash reporting there are only a hand few of exceptions
that are non-fatal. For the rest, we can simply notify the crash
reporter.

 - Simplified state requirements for native invocation by replacing the
 `DeliveryManager.with` to an extension `PushConnection.ifInitialized`.
 - The new `CoroutineExceptionHandler` now notifies the crash reporter
 of fatal or unknown exceptions.
 - Moved extension functions to their equivalent files in an `.ext`
 package.
 - Added more tests to increase coverage. 🎉

---

Closes #6171

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

**Comment by jonalmeida** [comment]
cc: @grigoryk

File: components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt [hunk 1]
```diff
@@ -340,53 +323,18 @@ class AutoPushFeature(
...
-internal object DeliveryManager {
-    /**
-     * Executes the block if the Push Manager is initialized.
-     */
-    fun with(connection: PushConnection, block: PushConnection.() -> Unit) {
-        if (connection.isInitialized()) {
-            block(connection)
-        }
+    if (isFatal) {
+        onError(PushError.Rust(e, e.message.orEmpty()))
```
Comment (grigoryk) [inline components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt:337]: maybe at least log the non-fatal ones?

File: components/feature/push/src/main/java/mozilla/components/feature/push/ext/Connection.kt [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+import mozilla.components.support.base.log.logger.Logger
+
+/**
+ * Executes the block if the Push Manager is initialized.
+ */
+internal inline fun PushConnection.ifInitialized(block: PushConnection.() -> Unit) {
+    if (isInitialized()) {
+        block()
+    } else {
+        Logger.error("Native push layer is not yet initialized.")
```
Comment (grigoryk) [inline components/feature/push/src/main/java/mozilla/components/feature/push/ext/Connection.kt:17]: do we never need to hard-assert this condition and crash out?

File: components/feature/push/src/main/java/mozilla/components/feature/push/ext/CoroutineScope.kt [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+
+package mozilla.components.feature.push.ext
+
+import kotlinx.coroutines.CoroutineScope
+import kotlinx.coroutines.Job
+import kotlinx.coroutines.launch
+import mozilla.appservices.push.PushError
+
+/**
+ * Catches all known non-fatal push errors to notify the callback before re-throwing.
```
[the remark this answers is not in the document]
Comment (jonalmeida) [reply components/feature/push/src/main/java/mozilla/components/feature/push/ext/CoroutineScope.kt:13]: Yeah, that's bad documentation. It's a known _fatal_ push error.

File: components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt (hunk 1 above)
Comment (jonalmeida) [reply components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt:337]: This is the extension function, at the calling site, we use the logger there.

File: components/feature/push/src/main/java/mozilla/components/feature/push/ext/Connection.kt (hunk 2 above)
Comment (jonalmeida) [reply components/feature/push/src/main/java/mozilla/components/feature/push/ext/Connection.kt:17]: We spent some time thinking about this: push fatal errors are limited to those are not in this list: https://github.com/mozilla-mobile/android-components/pull/6397/files#diff-c2cb12518c4508eaf1fb172996e64fd5R328

The fatal errors we can receive are malformed messages or unrecoverable database errors. Fatal for push doesn't mean we should crash out for the user because we have no real recovery process aside using `verifyConnection` on the AutoPush side and `renewRegistration` for resetting our push tokens.

So for now, the best we can do is report those fatal errors to Sentry and fix them in future releases. App services, could always handle or expose a way to reset the internal db, but that's out of the scope right now until we know what are the situations we want to handle for that solution.

Comment (jonalmeida) [reply components/feature/push/src/main/java/mozilla/components/feature/push/ext/Connection.kt:17]: This was our way of avoiding any timing issues where a message or token could be received from the push service _before_ our rust code had initialized. This shouldn't happen in practice since we don't allow receiving messages until everything is initialized first - it ends up being a way to satisfy the compiler checks that what could happen in practice.

If we lose:
 - A message, this would a lost push message that we cannot recover. In theory we could create a buffer to process these messages layer but in the worse case this would be only the first message loss (see above why this wouldn't happen).
- A push token, we still store the token in our prefs and re-init our native layer with it on the next initialization.

**Comment by jonalmeida** [comment]
bors r=grigoryk

**Comment by jonalmeida** [comment]
bors retry
