### PR TITLE
Fixes #3612: Fixes cursor issue when clearing (🧠: @ekager)

### LINKED ISSUE #3612: Cursor disappears after clearing autocomplete URL (InlineAutocompleteEditText issue)
See https://github.com/mozilla-mobile/fenix/issues/733 for more info.

cursor bug 2019-07-01 14_06_16

### PR DESCRIPTION
**Pull request by sblatz**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

File: components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt [hunk 1]
```diff
@@ -99,7 +99,7 @@ internal class EditToolbar(
         scaleType = ImageView.ScaleType.CENTER
 
         setOnClickListener {
-            urlView.text.clear()
+            urlView.setText("")
```
Comment (pocmo) [inline components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt]: Oh, I remember we fixed such a thing in Focus too. It would be super helpful to add a comment here explaining why we use `setText("")` here. Otherwise someone will come along and change it to clear() again. :)
You could even look into adding a test that makes sure `setText()` is called in this situation.

**Comment by pocmo** [comment]
Merging to get this into the 2.0.0 release. Maybe you can add the comment in a follow-up PR?
