### PR TITLE
Closes #1935: Fix Downloads not working with Custom Tabs.

### LINKED ISSUE #1935: Downloads do not work in Custom Tabs
We need to pass in the sessionId to the feature.

Related: mozilla-mobile/reference-browser#538

### PR DESCRIPTION
**Pull request by jonalmeida**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes a changelog entry or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

File: components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt [hunk 1]
```diff
@@ -53,7 +54,8 @@ class DownloadsFeature(
      * to be processed.
      */
     override fun start() {
-        super.observeSelected()
+        val session = sessionId?.let { sessionManager.findSessionById(sessionId) }
+        session?.let { observeFixed(it) } ?: observeSelected()
```
Comment (pocmo) [inline components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt]: Since that is exactly the same code as in the other PR. Maybe that could just be a method on `SelectionAwareSessionObserver` (which takes an optional session id)?

Comment (jonalmeida) [reply components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt]: Heh, left this comment in the other PR. I'll file an issue to do that.
