### PR TITLE
Fix #5603 - Implement notification for when the migration is complete.

### LINKED ISSUE #5603: Fennec migration: No notification displayed when the migration is complete
## Preconditions:
Have Fennec installed and logged in.
## Steps to reproduce
1. Replace Fennec with Fenix using a build from https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration;
2. Observe the ongoing notification while the migration is in progress.
3. Observe the notification change when the migration is complete
### Expected behavior
The notification is displayed and the Firefox logo is visible, [specs](https://app.abstract.com/share/b1b9f719-fbb5-4c94-b45d-556232a3cd52?collectionLayerId=8170061f-90bc-400b-b505-3e59d89d4c8a&present=true&preview=false&sha=87a74c3651c6a5f2af3e74888ab119f9b25f5dd7).
### Actual behavior
The notification is not displayed.

### Device information

* Android device: Samsung Galaxy S8 (Android 9), HTC Desire 820 (Android 6.0.1)
* Fenix version: Nightly migration build 01/16

### PR DESCRIPTION
**Pull request by Sparky93**
Currently a notification is being shown for migration progress status, but no notification is being
displayed to the user for when the migration is complete.
In order to properly handle this notification's remove or click action, a broadcast receiver is
required that listens for this specific actions so it can remove the notification's channel.

---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks
- [x] **Tests**: This PR doesn't include tests as it contains changes for component not yet tested.
- [x] **Changelog**: This PR does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md)

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/support/migration/src/main/java/mozilla/components/support/migration/AbstractMigrationService.kt [hunk 1]
```diff
@@ -75,29 +78,61 @@ abstract class AbstractMigrationService : Service() {
         scope.cancel()
     }
 
-    private fun showForegroundNotification() {
-        val channel = ensureChannelExists()
+    private fun showStatusNotification(isInProgress: Boolean) {
```
Comment (pocmo) [inline components/support/migration/src/main/java/mozilla/components/support/migration/AbstractMigrationService.kt]: nit: let's keep the method as-is and create a separate method for showing the completion notification. that will prevent all those `if/else` statements here.

File: components/support/migration/src/main/java/mozilla/components/support/migration/AbstractMigrationService.kt [hunk 2]
```diff
@@ -121,14 +156,4 @@ abstract class AbstractMigrationService : Service() {
 
         return NOTIFICATION_CHANNEL_ID
     }
-
-    private fun removeChannel() {
```
Comment (pocmo) [inline components/support/migration/src/main/java/mozilla/components/support/migration/AbstractMigrationService.kt]: I've been thinking about this recently and I think we should just keep the channel. It will not hurt much and we have a bunch of "after migration" cleanup that we want to ship eventually and removing the channel could be one of that. This will just simplify everything.
