### PR TITLE
Closes #2887: Allow reporting exceptions without crashing

### LINKED ISSUE #2887: lib-crash: Allow reporting exceptions without crashing
In some situations you need to catch a certain type of exception (famous example: `JSONException`). In those situations often you can continue without crashing the app. In the case of an `JSONException` the cause is often that the JSON was different than what you expected. In those situations it would be nice to not only silently continue running but also report this exception (like a crash) via `lib-crash`. With that this error is visible to us and we can fix our code.

### PR DESCRIPTION
**Pull request by rocketsroger**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/lib/crash/src/main/java/mozilla/components/lib/crash/service/GleanCrashReporterService.kt [hunk 1]
```diff
@@ -34,6 +34,7 @@ class GleanCrashReporterService(
         // These keys correspond to the labels found for crashCount metric in metrics.yaml as well
         // as the persisted crashes in the crash count file (see above comment)
         const val UNCAUGHT_EXCEPTION_KEY = "uncaught_exception"
+        const val CAUGHT_EXCEPTION_KEY = "caught_exception"
```
Comment (travis79) [inline components/lib/crash/src/main/java/mozilla/components/lib/crash/service/GleanCrashReporterService.kt]: Please also update the label [here](https://github.com/mozilla-mobile/android-components/blob/6c6dc3ce553b1032c5d3e183fb61201e4be39ed2/components/lib/crash/metrics.yaml#L19) in the metrics.yaml to match.  You may need to do a clean and then build for the changes to the metrics.yaml to be picked up by the Glean_Parser.  I don't think that there are any pipeline changes to make as a result of this, but I'm looking into that just to be sure.

Comment (travis79) [reply components/lib/crash/src/main/java/mozilla/components/lib/crash/service/GleanCrashReporterService.kt]: Nope, looks like the pipeline treats the labels as arbitrary string keys so nothing to change beyond this.

Comment (rocketsroger) [reply components/lib/crash/src/main/java/mozilla/components/lib/crash/service/GleanCrashReporterService.kt]: Thanks for catching this.

**Comment by rocketsroger** [comment]
bors r=travis79

**Comment by pocmo** [comment]
bors r-

Let's get an AC review too. I'll do that quickly. :)

File: components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt [hunk 2]
```diff
@@ -28,8 +28,14 @@ import java.util.concurrent.TimeUnit
...
 
-private val defaultServerUrl = "https://crash-reports.mozilla.com/submit?" +
+private const val DEFAULT_SERVER_URL = "https://crash-reports.mozilla.com/submit?" +
         "id=${BuildConfig.MOZ_APP_ID}&version=${BuildConfig.MOZILLA_VERSION}&${BuildConfig.MOZ_APP_BUILDID}"
+
+@VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
+internal const val CAUGHT_EXCEPTION_PREFIX = "Not a crash"
+
+@VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
+internal const val UNCAUGHT_EXCEPTION_PREFIX = "Fatal crash"
```
Comment (pocmo) [inline components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt]: Are those for distinguishing both types on Crashstats? I wonder if we should use some kind of prefix like on mailing lists, e.g. `[CRASH]`. Not sure about the other though. :) `[INFO]`, `[REPORT]`, ..

File: components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SentryService.kt [hunk 3]
```diff
@@ -104,3 +118,11 @@ private fun createMessage(crash: Crash.NativeCodeCrash): String {
 
     return "NativeCodeCrash(fatal=$fatal, minidumpSuccess=$minidumpSuccess)"
 }
+
+private fun createMessage(crash: Crash.UncaughtExceptionCrash): String {
+    return "Fatal crash: ${crash.throwable.message})"
+}
```
Comment (pocmo) [inline components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SentryService.kt]: Won't that mess with our existing crashes since they now start to have a different message? Maybe we should only add a prefix for the new type of "non-crashes"? 🤔

Comment (rocketsroger) [reply components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SentryService.kt]: Agreed.  Sure, I'll remove the prefix for crashes.  Only do it for non-crashes

File: components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt (hunk 2 above)
Comment (rocketsroger) [reply components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt]: I'll use the [INFO] tag.  Assuming we won't put a prefix for the uncaught exception since we don't want to affect uncaught exceptions.

**Comment by rocketsroger** [comment]
bors = travis79, pocmo

**Comment by rocketsroger** [comment]
bors r=[travis79, pocmo]

**Comment by rocketsroger** [comment]
bors r=[travis79, pocmo]
