### PR TITLE
For #12711 - Use a separate reader for autocomplete suggestions

### LINKED ISSUE #12711: Awesomebar autocomplete may fail to show history suggestions
Issue seen in https://github.com/mozilla-mobile/fenix/issues/26687 and reported as intermittent.

Debugging I indeed saw cases in which the [getAutocompleteSuggestion from `ToolbarAutocompleteFeature`](https://github.com/mozilla-mobile/android-components/blob/19d85f964578a32f25f2c96226de48af52a56da0/components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/ToolbarAutocompleteFeature.kt#L38) will return null and so the app will show results from the shipped in domain providers.

My working theory is that the interrupted reads for history suggestions https://github.com/mozilla-mobile/android-components/blob/52e2fc78d6b1e6ea1ad977e47fb3d8e09e3792f0/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/HistoryStorageSuggestionProvider.kt#L57 are in a race with the autocomplete suggestions which use [the same `reader`](https://github.com/mozilla-mobile/android-components/blob/1b490c833c9935a250b7b4c1e29eb7f272d3e75f/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt#L154).

### PR DESCRIPTION
**Pull request by Mugurell**
Decouple this functionality from search suggestions allowing for individual
control over the readers used.

Result:

https://user-images.githubusercontent.com/11428869/187237078-c6d468cf-0571-4aec-8977-1439f0fd02a6.mp4

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### GitHub Automation
Fixes #12711

### CODE REVIEW

File: components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt [hunk 1]
```diff
@@ -151,7 +159,8 @@ open class PlacesHistoryStorage(
 
     override fun getAutocompleteSuggestion(query: String): HistoryAutocompleteResult? {
         val url = handlePlacesExceptions("getAutoCompleteSuggestions", default = null) {
-            places.reader().matchUrl(query)
+            autocompleteReader.interrupt()
```
Comment (csadilek) [inline components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt:162]: @Mugurell So before this fix here we didn't interrupt autocompletes. We only interrupted history suggestions. How did sharing the reader cause us to lose history suggestions?

**Review by csadilek — COMMENTED** [review]
Thanks for taking this on so quickly. Have a question below :).

File: components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt (hunk 1 above)
Comment (Mugurell) [reply components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt:162]: I assume parallel queries on the same reader - for reading suggestions and for reading autocomplete and a race between these requests which would explain the intermittent nature of the issue. 
Given that both queries happen in `PlacesHistoryStorage` they will share the same reader. 
If [`cancelReads`](https://github.com/mozilla-mobile/android-components/blob/52e2fc78d6b1e6ea1ad977e47fb3d8e09e3792f0/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/HistoryStorageSuggestionProvider.kt#L57) from before new suggestions requests happen after the `getAutocompleteSuggestion` gets to make a request to `places.reader().matchUrl` but before this completes then `places.reader().matchUrl` would also be interrupted [and so it would return null](https://github.com/mozilla-mobile/android-components/blob/1b490c833c9935a250b7b4c1e29eb7f272d3e75f/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt#L152-L155).

Comment (csadilek) [reply components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt:162]: @Mugurell Yes, I'd understand that code path, but that would mean we'd lose autocomplete suggestions, not history search suggestions. The way I understand the ticket is that search suggestions are missing from the awesomebar, right?

Comment (csadilek) [reply components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt:162]: (If it's speculative and you can't repro anymore, but we don't know exactly why, I am also fine landing this and asking folks for feedback.)

Comment (Mugurell) [reply components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt:162]: Sorry, didn't touch the "history suggestions" part.
Based on the user reports from https://github.com/mozilla-mobile/fenix/issues/26145 the issue is with autocomplete not showing result from history but from the list of shipped domains.
And indeed while debugging I saw that although there should be matching history entries in this call
https://github.com/mozilla-mobile/android-components/blob/19d85f964578a32f25f2c96226de48af52a56da0/components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/ToolbarAutocompleteFeature.kt#L37-L42
`historyResults` would be null and so we would show `domainResults`.

**Review by csadilek — APPROVED** [review]
🚢

**Comment by Mugurell** [comment]
@Mergifyio backport releases/105.0

**Comment by Mugurell** [comment]
@Mergifyio backport releases/104.0
