### PR TITLE
Closes #7244: PlacesHistoryStorage crash in Sample Browser

### LINKED ISSUE #7244: PlacesHistoryStorage crash in Sample Browser
This seems to be a regression. Sample browser is crashing quite frequently now when moving from background to foreground or loading a new page.

```
 java.lang.IllegalStateException: must call init first
        at mozilla.components.browser.storage.sync.RustPlacesConnection.writer(Connection.kt:95)
        at mozilla.components.browser.storage.sync.PlacesHistoryStorage$recordObservation$2.invokeSuspend(PlacesHistoryStorage.kt:63)
        at mozilla.components.browser.storage.sync.PlacesHistoryStorage$recordObservation$2.invoke(Unknown Source:10)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:154)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
        at mozilla.components.browser.storage.sync.PlacesHistoryStorage.recordObservation$suspendImpl(PlacesHistoryStorage.kt:59)
        at mozilla.components.browser.storage.sync.PlacesHistoryStorage.recordObservation(Unknown Source:0)
        at mozilla.components.feature.session.HistoryDelegate.onTitleChanged(HistoryDelegate.kt:28)
        at mozilla.components.browser.engine.gecko.GeckoEngineSession$createContentDelegate$1$onTitleChange$$inlined$let$lambda$1.invokeSuspend(GeckoEngineSession.kt:700)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

### PR DESCRIPTION
**Pull request by csadilek**
Removes the `cleanup` call as it permanently leaves the `Connection` unusable and we're not re-initializing or creating a new instance of it. It's not clear to us how this should be used right now.

Also makes all access to `api` thread-safe.

### CODE REVIEW

File: components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/Connection.kt [hunk 1]
```diff
@@ -61,6 +61,7 @@ internal interface Connection : Closeable {
 /**
  * A singleton implementation of the [Connection] interface backed by the Rust Places library.
  */
+@Suppress("TooManyFunctions")
```
Comment (grigoryk) [inline components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/Connection.kt:64]: lol; i wonder if there is any value to these linters, we just keep suppressing them when they pop up.
