### PR TITLE
Close #6535: Add breadcrumbs to CrashReporting interface

### LINKED ISSUE #6535: Add option for adding bread crumbs to CrashReporting interface
For debugging some crashes it would be very helpful if components could add breadcrumbs too.

### PR DESCRIPTION
**Pull request by rocketsroger**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SentryService.kt [hunk 1]
```diff
@@ -17,8 +17,8 @@ import io.sentry.event.Event
 import io.sentry.event.EventBuilder
 import io.sentry.event.interfaces.ExceptionInterface
 import mozilla.components.Build
-import mozilla.components.lib.crash.Breadcrumb as crashBreadCrumbs
 import mozilla.components.lib.crash.Crash
+import mozilla.components.support.base.crash.Breadcrumb as crashBreadCrumb
```
Comment (pocmo) [inline components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SentryService.kt:21]: nit: This has been the case before, but I just noticed it here... A class name that starts with a lower letter is confusing to read in code imo. Can we just name it `CrashBreadCrumb`? :) Or since the original class name doesn't use that camel-casing maybe `CrashBreadcrumb`?

File: docs/changelog.md [hunk 2]
```diff
@@ -24,7 +24,13 @@ permalink: /changelog/
 
 * **feature-push**
   * Simplified error handling and reduced non-fatal exception reporting.
+ 
+* **lib-crash**
+  * ⚠️ **This is a breaking change**: breadcrumbs now have `support-base` dependency.
```
Comment (pocmo) [inline docs/changelog.md:29]: The wording on this changelog entry is not super clear, I think. Just from reading this I wouldn't be sure what that means. 🤔 
I also wonder if we should make `support-base` an `api` dependency in `build.gradle` so that a consumer of `lib-crash` does not have to import `support-base` manually to get access to breadcrumbs. `support-base` is something that helps us internally but an end-user should not have to bother with it.

File: components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SentryService.kt (hunk 1 above)
Comment (rocketsroger) [reply components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SentryService.kt:21]: Agreed, I'll fix it.  Thanks,

File: docs/changelog.md (hunk 2 above)
Comment (rocketsroger) [reply docs/changelog.md:29]: Ok, I'll remove this entry.

**Comment by rocketsroger** [comment]
bors r=pocmo
