### PR TITLE
Closes #5174: Add telemetry crash service in lib-crash.

### LINKED ISSUE #5174: Crash Reporter: Allow collecting crash metrics without confirmation in the crash prompt
Our other products send crash statistics based on the telemetry setting. However in our case `GleanCrashReporterService` pretends to be a crash reporter and therefore only gets triggered if the user decides to send a crash report (and has telemetry enabled).

We should make it possible to trigger a service without showing the prompt first (for that particular service).

### PR DESCRIPTION
**Pull request by rocketsroger**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt [hunk 1]
```diff
@@ -96,13 +97,33 @@ class CrashReporter(
         }
     }
 
+    /**
+     * Submit a crash report to all registered services.
```
Comment (pocmo) [inline components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt]: nit: "to all registered services" -> "to all registered telemetry services"?

I wonder if that needs to be public at all. Are we expecting anyone to call this?

File: components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt [hunk 2]
```diff
@@ -96,13 +97,33 @@ class CrashReporter(
...
+                when (crash) {
+                    is Crash.NativeCodeCrash -> telemetryService.report(crash)
+                    is Crash.UncaughtExceptionCrash -> telemetryService.report(crash)
+                }
+            }
+
+            logger.info("Crash report submitted to ${services.size} telemetry services")
+            withContext(Dispatchers.Main) {
+                then()
+            }
```
Comment (pocmo) [inline components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt]: Is this callback mechanism with `then` even needed here?

File: components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt [hunk 3]
```diff
@@ -129,17 +150,22 @@ class CrashReporter(
 
         logger.info("Received crash: $crash")
 
-        if (CrashPrompt.shouldPromptForCrash(shouldPrompt, crash)) {
-            if (shouldSendIntent(crash)) {
-                // This crash was not fatal and the app has registered a pending intent: Send Intent to app and let the
-                // app handle showing a confirmation UI.
-                launchCrashIntent(context, crash)
+        /* Telemetry services does not require user prompts */
+        submitTelemetryCrashReport(crash)
```
Comment (pocmo) [inline components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt]: I am wondering here whether we may be executing this on the crashing process here (e.g. uncaught exception case) and whether that is problematic (after the crash it is not guaranteed that anything is working). But since we are also submitting here for the non-prompt case ... maybe that is fine? But then again we never run a non-prompt configuration in an app we ship right now.
If we step back from what we have right now... then I assume we should always launch our service here and the service will take care of uploading (non prompt case) and/or invoking telemetry from a new process? 🤔

Comment (rocketsroger) [reply components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt]: Agreed.  I'll simplify this so even non-prompt cases go through the service.  This way there is less that can go wrong.

File: components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt (hunk 2 above)
Comment (rocketsroger) [reply components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt]: I left it in so its available if needed.  But you're right that if we can always add it in later.    I'll remove it.

File: components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt (hunk 1 above)
Comment (rocketsroger) [reply components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt]: I don't think this needs to be public.  Are you thinking that someone would want to submit a caught exception to telemetry services?

Comment (rocketsroger) [reply components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt]: Actually I take that back.  If I'm moving this to the service then I'll have to make this public.

File: components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt [hunk 4]
```diff
@@ -80,7 +85,7 @@ class CrashReporter(
     /**
      * Submit a crash report to all registered services.
      */
-    fun submitReport(crash: Crash, then: () -> Unit = {}): Job {
+    fun submitCrashReport(crash: Crash, then: () -> Unit = {}): Job {
```
[the remark this answers is not in the document]
Comment (rocketsroger) [reply components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt]: Maybe at this stage I shouldn't make this API change.  This will require a fix in Fenix if I rename it.

File: components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt (hunk 2 above)
Comment (rocketsroger) [reply components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt]: FYI this is now needed since its now called from a service.

**Comment by rocketsroger** [comment]
bors r=pocmo

**Comment by rocketsroger** [comment]
bors r=pocmo

**Comment by rocketsroger** [comment]
bors retry
