### PR TITLE
Closes #5041: Fix migration post-processing to understand FxA migrations

### LINKED ISSUE #5041: Fennec migration: Fenix crashes at start
## Preconditions:
Have Firefox Release installed and logged in.
## Steps to reproduce
1. Replace Fennec with Fenix using a build from https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration;
2. Launch Fenix.
### Expected behavior
Fenix opens.
### Actual behavior
Fenix crashes.
### Notes:
[logcat-crash.txt](https://github.com/mozilla-mobile/android-components/files/3840189/logcat-crash.txt)
[Video](https://drive.google.com/file/d/1ERAMHz0FlvcAbjgXUoOEF19udlHCZI4s/view)
### Device information

* Android device: Nexus 6P (Android 8.1.0) - ARM; Samsung Galaxy S8 (Android 9) - ARM; Google Pixel 2 (Android 9) - ARM64.
* Fenix version: Nightly 191109 GV 71

### PR DESCRIPTION
**Pull request by grigoryk**
When FxA migration was added, I forgot to adjust "read and parse past migrations" code
to account for a new migration type. This patch fixes that problem, and adds tests that
would have cought it.

---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/support/migration/src/main/java/mozilla/components/support/migration/MigrationResultsStore.kt [hunk 1]
```diff
@@ -57,6 +57,7 @@ internal class MigrationResultsStore(context: Context) : SharedPreferencesCache<
                 Migration.Bookmarks.javaClass.simpleName -> Migration.Bookmarks
                 Migration.OpenTabs.javaClass.simpleName -> Migration.OpenTabs
                 Migration.Gecko.javaClass.simpleName -> Migration.Gecko
+                Migration.FxA.javaClass.simpleName -> Migration.FxA
```
Comment (pocmo) [inline components/support/migration/src/main/java/mozilla/components/support/migration/MigrationResultsStore.kt]: This has happened to me too when I added the code for Gecko. I wish we would have used the power of static types and exhaustive when statements to make the compiler just fail if we miss a case here. Anyhow, for now let"s get that landed. :)
