### PR TITLE
Closes #5229: Remove the Need to Have Atleast One Engine Observer to Load URI

### LINKED ISSUE #5229: Remove the Need to Have At Least One Engine Observer to Load URI
Currently `GeckoEngineSession` have the assumption that there is always atleast one `EngineObserver` associated with it.  This assumption is incorrect.  Add check so if there's no `EngineObserver` then return Allow to GeckoView so it can continue to load the page.

### PR DESCRIPTION
**Pull request by rocketsroger**
Tested with sample browser to confirm the feature is still working as expected.

---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- [ ] **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### CODE REVIEW

File: components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt [hunk 1]
```diff
@@ -1963,6 +1963,17 @@ class GeckoEngineSessionTest {
         fakePageLoad(true)
     }
 
+    @Test
+    fun `onLoadRequest will complete GeckoResult if no observers is available`() {
```
Comment (csadilek) [inline components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt]: nit: no observer is available...

Comment (rocketsroger) [reply components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt]: Agreed.  Thanks,

**Comment by rocketsroger** [comment]
bors r=csadilek
